### ISSUE TITLE
Adding Access-Control-Expose-Headers for X-GraphQL-Event-Stream header

### ISSUE THREAD

**Issue by imolorhe** [graphile/postgraphile#1001]
I'm submitting a ... 

* [ ] bug report
* [x] feature request
* [ ] question 

PostGraphile version: 4.3.3

Steps to reproduce: Try making a request from any browser client with the `--watch` flag enabled on postgraphile, and attempt to retrieve the `X-GraphQL-Event-Stream` header. It would return `null`.

Current behavior: Trying to get the `X-GraphQL-Event-Stream` header from a browser would return nothing.

Expected behavior: Trying to get the `X-GraphQL-Event-Stream` header should return the header from any client. For this, you would need to add the `Access-Control-Expose-Headers` header in the server response as well, specifying the `X-GraphQL-Event-Stream` header. More details about the header can be found [here](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Expose-Headers).

**Comment by benjie** [comment]
A pull request to provide this would be very welcome; here's the relevant bit of code:

https://github.com/graphile/postgraphile/blob/1326f896cda4d2134a1246d765bf63d2dfa8fd36/src/postgraphile/http/createPostGraphileHttpRequestHandler.ts#L901-L922

And here's where you'd add a test:

https://github.com/graphile/postgraphile/blob/a1d1402b13f0a3fe5eaa594fe114e161912bef7f/src/postgraphile/http/__tests__/createPostGraphileHttpRequestHandler-test.js#L235-L253

**Comment by imolorhe** [comment]
Created PR #1002.

**Comment by benjie** [comment]
Merged in #1002
