### ISSUE TITLE
Count estimate

### ISSUE THREAD

**Issue by pencilcheck** [graphile/postgraphile#1010]
I'm submitting a ... 

* [ ] bug report
* [x] feature request
* [x] question 

PostGraphile version: 4.3.3

Minimal SQL file that can be loaded into a clean database:

```sql

```

Steps to reproduce:

Current behavior:

totalCount is adding time to the query (I think, since it is fast on sql viewer but everytime I request totalCount for pagination, the query slow to a crawl). We need a way to make it faster.

Expected behavior:

Maybe a feature request, but maybe there is already a way to workaround it.

I wonder if it is possible to request a count estimate as an alternative to totalCount if accuracy is not the top priority?

I found the link that shows some related queries for tables only (might not be good enough for postgraphile but might be interesting?)
https://wiki.postgresql.org/wiki/Count_estimate

**Comment by benjie** [comment]
That’s only useful if you want to know how many rows in a table. As soon as you add a filter (condition, relation, RLS policy) it’s no longer useful.

Adding a relevant index should make totalCount faster 👍

**Comment by pencilcheck** [comment]
It should be, but it would be very nice to have a more speedy totalCount regardless if the filter and condition.

**Comment by benjie** [comment]
@pencilcheck I think this might be something that would be best served by a plugin. You could, for example, hook all collections and add a field that uses these count estimation techniques. I don't plan to add this functionality to core at this time.
