### ISSUE TITLE
@foreignKey doesn't work with custom types

### ISSUE THREAD

**Issue by davbeck** [graphile/postgraphile#1014]
I'm submitting a ... 

* [ ] bug report
* [x] feature request
* [ ] question 

PostGraphile version: 4.3.2

Minimal SQL file that can be loaded into a clean database:

```sql
CREATE TABLE foo (id serial primary key);
INSERT INTO foo (id) VALUES (1), (2), (3);

CREATE TYPE bar AS (foo_id int);
COMMENT ON TYPE bar IS E'@foreignKey (foo_id) references foo (id)';

CREATE OR REPLACE FUNCTION bars()
	RETURNS SETOF bar
	LANGUAGE plpgsql STABLE STRICT AS $$
DECLARE
   counter INTEGER := 0; 
BEGIN
	LOOP 
	EXIT WHEN counter = 3; 
	counter := counter + 1; 
	RETURN NEXT ROW(counter)::bar;
	END LOOP ;
END;
$$;
```

Current behavior:
The @foreignKey comment doesn't seem to be processed. Digging through the source code a little bit, it looks like Graphile only looks for this tag on "classes". Custom types seem to have their own class, but their comment isn't included on the class.

Expected behavior:
If I have something that returns a custom type, I should be able to define a relationship to a table, just like I would be able to with a view.

**Comment by benjie** [comment]
I’m not at my computer, but it could be that you’ve not defined a primary key on foo so it has nothing to reference?

**Comment by davbeck** [comment]
You're right, that wouldn't work anyway. Updated the example to include primary key but still not seeing it get applied.

Thinking about this a little bit more, this might not make sense after all. If you have a reference to a type, you can get a relation, but it's not possible to go the other direction (at least with any type that is more complicated than the example), which foreignKey would imply.

As a workaround, computed columns do work:

```sql
CREATE FUNCTION bar_foo(bar bar) RETURNS foo AS $$
  SELECT * FROM foo WHERE foo.id = bar.foo_id;
$$ LANGUAGE sql STABLE;
```

**Comment by benjie** [comment]
Agreed; I think this is best. I'll probably add support for single-direction relations at some point in the future but computed columns are a simple solution for now.
