### ISSUE TITLE
ndjson

### ISSUE THREAD

**Issue by catalinconstant** [graphile/postgraphile#1025]
I'm submitting a ... 

* [ ] bug report
* [x ] feature request
* [ ] question 

PostGraphile version: v4.4.0-beta-8

Minimal SQL file that can be loaded into a clean database:

```sql

```

Steps to reproduce:

Current behavior:

Expected behavior:
I think that if postgraphile will have an option for ndjson format response will be very useful for client apps in the case of large json responses,
see (https://davidwalsh.name/streaming-data-fetch-ndjson)

**Comment by benjie** [comment]
How do you see that working with GraphQL? I can’t figure out where the newlines would go. Do any GraphQL clients support this in a standard way?

**Comment by catalinconstant** [comment]
Dear Benjie, 
You are very right, thinking in the GraphQl framework,and  GraphQl clients, but let's take those cases:
1. fetch(/graphql {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({
      query: input.query,
      variables: input.variables ? input.variables : undefined
    })
  })
    .then(res => res.json()) etc. this mean that if we have for example 1M JSON objects we should wait all them till we can process them 
2.  fetch(/graphql {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({
      query: input.query,
      variables: input.variables ? input.variables : undefined
    })
  }).then((res) => {
	return ndjsonStream(res.body); 
}).then((stream) => {
	let read;
	stream.getReader().read().then(read = (result) => {
		if (result.done) return;
		stream.getReader().read().then(read); 
	});
});
in this way we can process the chunks (stream)  as they arrive whiteout waiting for the whole response to be packed in memory and then processed. 
There are other methods to do such stream processes both in server or client side.
For the client side is oboe.js and in the server side the response could be processed  outside postgraphile in many other ways.
Anyway the request for ndjson is a nice to have, if you consider outside postgraphile  main stream please close it.if 
At the end, I consider GraphQl to be more a server side process  The client side should be handled by a developer without a help of a client library, but if client library bring  old ways of doing things  why not to use it ?
We can think also of webworkers and the way to handle Graphql  requests and responses 
PS
Many thanks for the great job you are doing, Postgresql is a far far far away of any other open source  databases  and with postgraphile you bring back Postgresql in the web development mainstream

**Comment by benjie** [comment]
What would the implementation of `ndjsonStream` look like? I still can't see how ndjson (which seems to be optimised for things like log lines and other things that return large lists at the root level) will work with GraphQL (which primarily returns objects rather than arrays).

If you just want to change the result stream from PostGraphile into another format then that's possible with a [server plugin](https://www.graphile.org/postgraphile/plugins/) - I'd love to see an implementation of that!

**Comment by catalinconstant** [comment]
One of the use case of large array of objects is for postgis extension where postgres can return objects in geojson format in hundred of thousands of features some thing like
 CREATE OR REPLACE FUNCTION "app"."get_points_bbox"("xmin" float8, "ymin" float8, "xmax" float8, "ymax" float8)
  RETURNS "pg_catalog"."jsonb" AS $BODY$
SELECT
	jsonb_agg ( feature ) AS points
FROM
	(
SELECT
	jsonb_build_object ( 'type', 'Feature', 'id', T.value, 'geometry', ST_AsGeoJSON ( T.geom ) :: jsonb ) AS feature 
FROM
	(
SELECT
	value,
	st_collect ( geom ) AS geom 
FROM
	table
WHERE
	ST_MakeBox2D( st_makepoint( xmin, ymin) , st_makepoint(xmax,ymax)) ~ geom
GROUP BY
	1
	) AS T 
	) AS feature
  $BODY$
  LANGUAGE sql STABLE
  COST 1000
where xmin, ymin, xmax, ymax define the current view of the map.
With streaming capabilities is possible to start rendering features on the map (openlayers,  arcgis js api, etc) as soon as they arrive in the browser. More than that is possible to handle the fetch to a webworker and to use Transferable interface  to move them in the main context as soon as they are available. 
At the moment   I am just in the 70% users of postgraphile using it as a library in express app orchestrated  by **nginx unit** (by the way,  in my opinion it  very nicely substitute the need for docker), behind a nginx web server. As always in software development there are many ways an to handle a problem.
In this situation, for the server side:
1. In postgres database through function in sql, psql, plv8 etc.
2. In postgraphile with as you indicate a  server plugin 
3. In nginx web server using lua or the njs, nginx server  javascript,  implementation
4 In express app ( a little bit problematic since postgraphile use "finally" library)  
Anyway now I started to dig in the postgraphile source code and third party plugins in order to figure out how to implement a server plugin. For sure I will need some help/directions in the future on how to integrate it in postgraphile. 
In the end, indeed GraphQl main focus is for "primarily returning objects", but with the use of gis, or ml capabilities of database as postgres in the server side and webgl in the client side you can handle/display large large list of objects in the browser trough graphql api

**Comment by benjie** [comment]
I'm thinking that using the `@defer` directive might be a good solution in GraphQL (rather than `ndjson`). This isn't something we support in PostGraphile currently but we could certainly entertain looking at it.

https://www.apollographql.com/docs/react/features/defer-support
