### ISSUE TITLE
Should `jwtRole` be required?

### ISSUE THREAD

**Issue by cazzer** [graphile/postgraphile#1028]
The [interface says this is required](https://github.com/graphile/postgraphile/blob/6fd13e71d06fa57c8760a9bfbef64feab2b16326/src/interfaces.ts#L305) but the [documentation seems to disagree](https://www.graphile.org/postgraphile/usage-library/#api-postgraphilepgconfig-schemaname-options). Happy to open a PR if it helps...

**Comment by benjie** [comment]
No; it should not. Great catch 👍 PR welcome

**Comment by cazzer** [comment]
Closing since it was fixed by #1031
