### ISSUE TITLE
@primaryKey smart comment returning an error

### ISSUE THREAD

**Issue by alex-ald** [graphile/postgraphile#1030]
I'm submitting a ... 

* [x] bug report
* [ ] feature request
* [ ] question 

PostGraphile version: 4.3.3

Minimal SQL file that can be loaded into a clean database:

```sql
CREATE TABLE part (
    uuid uuid PRIMARY KEY,
    ....
);

CREATE TABLE completed_build_part (
    part_uuid uuid NOT NULL REFERENCES part(uuid),
    completed_build_uuid uuid
    ....
);

CREATE OR REPLACE VIEW part_build_detail AS  SELECT part.uuid AS part_uuid,
    count(cbp.completed_build_uuid) AS build_count
   FROM part
     LEFT JOIN completed_build_part cbp ON cbp.part_uuid = part.uuid
  GROUP BY part.uuid, completed_build_uuid;
COMMENT ON VIEW part_build_detail is E'@primaryKey part_uuid\n@foreignKey (part_uuid) references part (uuid)';
```

Steps to reproduce:

I created a two tables a Part table and a CompletedBuildPart table, then I created a view to obtain some additional information about each row in the Part table. I add a  foreign key smart comment on the view so I could get the additional information when querying for a part. Initially I was using the view without the `@primaryKey` as a smart comment, which correctly allowed me to query the view as a nested property on the allParts query. But once I added the `@primaryKey` so it wouldn't return a list as a response in the query, this is when I encountered the error.

Current behavior:
The `@primaryKey` smart comment should allow me to obtain the data as an object instead of a list when using the foreign key relation to query it as a property on Part. But this error is returned:

```json
{
  "errors": [
    {
      "message": "table row type and query-specified row type do not match",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "allParts"
      ]
    }
  ],
  "data": {
    "allParts": null
  }
}
```

Expected behavior:
The `@primaryKey` should return the details as an object in the allParts query instead of a list and not throw an error.

**Comment by alex-ald** [comment]
Found the issue, still new to postgres so think this issue was from my View and not with postgraphile. The issue was caused by my GROUP BY.
instead of: `GROUP BY part.uuid, completed_build_uuid;`
solution: `GROUP BY part.uuid;`

**Comment by benjie** [comment]
Ah; thanks for the update 👍
