### ISSUE TITLE
Pass full koa context through pgSettings

### ISSUE THREAD

**Issue by jwickens** [graphile/postgraphile#1045]
I'm submitting a ... 

* [ ] bug report
* [x] feature request
* [ ] question 

PostGraphile version: latest

Current behavior: pgSettings receives req object, which when using Koa includes a _koaCtx with only a few of the properties of _koaCtx:
```js
app.use(ctx => {
  ctx.user = 'hi'
})
```
```js
  pgSettings: (...req) => console.log(req) || null
```
```js
{
  ...
    _koaCtx:
     { request: [Object],
       response: [Object],
       app: [Object],
       originalUrl: '/graphql',
       req: '<original node req>',
       res: '<original node res>',
       socket: '<original node socket>' },
  ...
}
```

(I strongly suspect that the _koaCtx is not set by postgraphile, but just wanted to show that I tried looking for it in req)

Desired behavior:

Pass the ctx object as the second argument when using Koa

**Comment by benjie** [comment]
It is set by us and it should be the whole context (I cannot see how it wouldn’t be...):

https://github.com/graphile/postgraphile/blob/master/src/postgraphile/http/koaMiddleware.ts#L17

PR / tests welcome 👍

**Comment by jwickens** [comment]
Hi Benjie, thank you for your response. Yes, you are correct, thank you! For future reference console.loging the koa context will only print a few attributes, not the whole object.

**Comment by benjie** [comment]
Thanks for confirming 👍
