### ISSUE TITLE
It's not super clear what --no-ignore-rbac does

### ISSUE THREAD

**Issue by jayp** [graphile/postgraphile#1057]
I'm submitting a ... 

* [ ] bug report
* [ ] feature request
* [x] question 

PostGraphile version: 4.3.3

This [section of the documentation](https://www.graphile.org/postgraphile/tables/#permissions 
) explains what `--no-ignore-rbac` does. 

However, not sure who the user here is. Is the user that we passed on to connection string to postgraphile cli? Or is this the "user" attached to the current context/resolver?

I ran the forum example and seems to be the former (user passed in connection string). However, given that you are talking about specific user `postgraphile_visitor` in the documentation, I took it to mean the latter (based on current context/resolver). 

Can you confirm?

**Comment by benjie** [comment]
It’s the union of the role in the connection string, and any role that that role can become. PostGraphile generates one GraphQL schema that is shared by all clients.

I’ll remove or reword the example.

**Comment by jayp** [comment]
Based on the bot in Discord, I can contribute a patch for this doc change.  One thing off your plate cc @jemgillam

**Comment by jemgillam** [comment]
@jayp Nice one, thank you.
