### ISSUE TITLE
Rename materialized view

### ISSUE THREAD

**Issue by kiliankoe** [graphile/postgraphile#1063]
I'm submitting a ... 

* [ ] bug report
* [ ] feature request
* [x] question 

PostGraphile version: 4.3.3

Hi! I literally just started playing around with PostGraphile a few hours ago and am loving it so far! ❤️ 

I am experiencing a minor issue when trying to rename a materialized view however. I currently have one called `data_dresden` in my db schema. The query for this is exposed as `allDataDresdens` via Postgraphile, I would like it to be `dataDresden` however. 

Following the docs I added the following comment:

```sql
COMMENT ON MATERIALIZED VIEW data_dresden IS E'@name dataDresden';
```

Unfortunately this doesn't appear to be picked up by PostGraphile. I'm assuming I'm doing something wrong here. Other smart comments appear to be working correctly.

Thanks for any help!

**Comment by benjie** [comment]
That’s the name before it gets inflected; if you give it the singular name then it will conflict with the singular record finder (if you were to add a primary key). You’re probably going to need a custom inflection rule for this view.

Check out the following:

https://www.graphile.org/postgraphile/inflection/

https://github.com/graphile-contrib/pg-simplify-inflector

You need to write an exception to the allRows inflector. https://github.com/graphile-contrib/pg-simplify-inflector/blob/master/index.js#L134

https://www.graphile.org/postgraphile/make-add-inflectors-plugin/

**Comment by kiliankoe** [comment]
Thanks for the info! I'll spend some time looking into those resources 😊
