### ISSUE TITLE
Fresh install, errors about missing pg-native

### ISSUE THREAD

**Issue by chadfurman** [graphile/postgraphile#1067]
I'm submitting a ... 

* [X] bug report
* [ ] feature request
* [ ] question 

PostGraphile version:

^4.4.0

Minimal SQL file that can be loaded into a clean database:

No SQL needed -- error on startup.

Steps to reproduce:

Install postgraphile library
Use it as express middleware
Point it to "postgres:///" without an actual postgres database at that URI
Run the app

Current behavior:
Get an error about missing pg-native bindings

Expected behavior:
all dependencies should be available when I install postgraphile

**Comment by benjie** [comment]
I cannot reproduce this. Steps I tried:

```
mkdir chad-yarn
cd chad-yarn
yarn add postgraphile express
pbpaste > server.js
DATABASE_URL="pggql_test" node server.js
```

```
mkdir chad-npm
cd chad-npm
npm install postgraphile express
pbpaste > server.js
DATABASE_URL="pggql_test" node server.js
```

Both worked as expected. `pbpaste` is the clipboard contents, which were:


```js
const express = require("express");
const { postgraphile } = require("postgraphile");

const app = express();

app.use(postgraphile(process.env.DATABASE_URL || "postgres:///", ["a","b","c"], {graphiql: true}));

app.listen(process.env.PORT || 3000);
```

---

Without the full error message text I can't be sure, but I believe the error is originating in the `pg` module which should only try and load the native driver under the following circumstances:

- `require('pg').native` is accessed somehow
- the `NODE_PG_FORCE_NATIVE` envvar is set

Can you share the server code you're using that causes this, and the full error message? I'm guessing it's this one:

```
➜ ~/Dev/TESTING/chad-npm  node
Welcome to Node.js v12.0.0.
Type ".help" for more information.
> require('pg')
PG {
[...snip...]
}
> require('pg').native
Cannot find module 'pg-native'
Require stack:
- /Users/benjiegillam/Dev/TESTING/chad-npm/node_modules/pg/lib/native/client.js
- /Users/benjiegillam/Dev/TESTING/chad-npm/node_modules/pg/lib/native/index.js
- /Users/benjiegillam/Dev/TESTING/chad-npm/node_modules/pg/lib/index.js
- /Users/benjiegillam/Dev/TESTING/chad-npm/[eval]
null
>
```

---

If you wish to use the PG native bindings, I advise that you install `pg` and `pg-native` manually, and pass a pre-built native pg.Pool to PostGraphile. I don't think you can install `pg-native` under Node 12 currently though. On Node 10 it's possible to do it with an envvar:

```
cd chad-yarn
yarn add pg-native
NODE_PG_FORCE_NATIVE=1 DATABASE_URL=pggql_test node server.js
```

**Comment by chadfurman** [comment]
Hmm so I managed to get it installed. Looks like some node_modules permission issues or something. Strange it would manifest like this.

Maybe the issue was not having postgres installed locally. I think it ultimately worked when I put it in a docker container by itself though so I don't think that's it.

Thanks for you effort in trying to reproduce. Probably safe to close this ticket.

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by chadfurman** [comment]
P.s. my server code is dead simple from your example. If it happens again, I'll reopen this ticket I guess.

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by chadfurman** [comment]
Here's more error details:

```
ERROR in ../node_modules/pg/lib/native/client.js
Module not found: Error: Can't resolve 'pg-native' in '/home/Lotus/code/rpg-next/node_modules/pg/lib/native'
 @ ../node_modules/pg/lib/native/client.js 10:13-33
 @ ../node_modules/pg/lib/native/index.js
 @ ../node_modules/pg/lib/index.js
 @ ../node_modules/postgraphile/build/postgraphile/postgraphile.js
 @ ../node_modules/postgraphile/build/postgraphile/index.js
 @ ../node_modules/postgraphile/build/index.js
 @ ./index.js
```

P.S. it has nothing to do with docker.  I run this command locally:

```
webpack index.js -o build/index.js --target='node'
```

This is the command that previously triggered the error; however, I no longer get the error. 

Thank you for your time and effort.

**Comment by chadfurman** [comment]
```
import { dotenv } from "dotenv"
import express from "express"
import { postgraphile } from "postgraphile"

dotenv.config()
const app = express()

app.use(postgrahpile(process.env.DATABASE_URL))

app.listen(process.env.PORT)
```

^ index.js

**Comment by benjie** [comment]
Ah, didn't realise you were using webpack! It is likely that webpack is invoking the native module - I had that issue when I was working on the lambda example, solved it with a `NormalModuleReplacementPlugin`:

https://github.com/graphile/postgraphile-lambda-example/blob/64bc50f1a560d9ead102a14e5fcfb684a2920f7b/webpack.config.js#L28

which just points it at the non-native client.

I don't think there's anything that PostGraphile can do to directly influence this.
