### ISSUE TITLE
PostGraphile watch flag not working as expected

### ISSUE THREAD

**Issue by alexisrolland** [graphile/postgraphile#1069]
I'm submitting a ...
* [ ] bug report
* [ ] feature request
* [x] question

PostGraphile version:
I am using PostGraphile in Docker. Latests image: `graphile/postgraphile   latest              f07ca419c2e5        3 months ago        91.9MB`

I am running my PostGraphile container using docker-compose. Here is the configuration:
```
version: '3.1'
services:

  db:
    container_name: listof-db
    restart: always
    image: listof-db
    build:
      context: ./db
    volumes:
      - db:/var/lib/postgresql/data
    env_file:
        - ./.env
    networks:
      - network
    expose:
      - 5432
    ports:
      - 5432:5432

  graphql:
    container_name: listof-graphql
    restart: always
    image: graphile/postgraphile
    env_file:
      - ./.env
    depends_on:
      - db
    networks:
      - network
    command: ["postgraphile",
      "--connection", "${DATABASE_URL}",
      "--port", "5433",
      "--schema", "base,public",
      "--default-role", "anonymous",
      "--jwt-secret", "${SECRET_KEY}",
      "--jwt-token-identifier", "base.sys_token",
      "--cors",
      "--watch"]

networks:
  network:

volumes:
  db:
```

Current behavior:
As you can see, I'm running PostGraphile with the `watch` argument to detect database changes. For some reason after a while, PostGraphile stops to detect the database changes and I have to restart my container to re-detect them and regenerate queries and mutation names... It is difficult to reproduce because the issue happens "randomly" after a while. Not based on a specific user action. Note the database change which was not detected was a table being renamed.

Expected behavior:
PostGraphile would continuously detect database changes.

Is this a know issue seen before? What could be the potential reasons for such a behavior? Where could I investigate?

Thanks
Alexis

**Comment by benjie** [comment]
Hi @alexisrolland; do you get the same issue when you use PostGraphile directly, rather than in Docker?

Also, can you ask docker to run `postgraphile --version` please?

**Comment by alexisrolland** [comment]
Hi @benjie 

I've actually never ran PostGraphile outside of Docker and I would have to install it on a server and let it run for a while to see if the issue would happen again. I'd like to avoid that.

The version I am running is `PostGraphile v4.3.2`.
The issue happend twice today. I'll continue to monitor the issue to see if it happens again and will let you know.

**Comment by benjie** [comment]
v4.4.0 solves a lot of things around database watching for users who reset their databases (e.g. by restarting docker instances); try upgrading to that.

**Comment by alexisrolland** [comment]
Cool thanks for the info @benjie 

I'm actually using the latest Docker image from Docker Hub: https://hub.docker.com/r/graphile/postgraphile/tags

I've deleted my Docker image and re-pulled the image but it seems it's still using `v4.3.2`. Any idea why it's not upgrading to `v4.4.0` automatically?

The image Dockerfile does not specify any version:
https://hub.docker.com/r/graphile/postgraphile/dockerfile
```
FROM node:alpine
LABEL description="Instant high-performance GraphQL API for your PostgreSQL database https://github.com/graphile/postgraphile"

RUN npm install -g postgraphile

EXPOSE 5000
ENTRYPOINT ["postgraphile", "-n", "0.0.0.0"]
```

**Comment by benjie** [comment]
Yeah, we need to sort out the DockerHub situation. It's on my list for next week. It always trails behind master. Though I'd expect it to be on 4.3.3 rather than 4.3.2, so seems it may be worse than I realised. Our dockerfile is only a few lines, you might be better off using that yourself directly:

https://github.com/graphile/postgraphile/blob/master/Dockerfile

**Comment by alexisrolland** [comment]
Ok I'll build a custom image reusing the Dockerfile!
Thanks again for your support.

**Comment by benjie** [comment]
`graphile/postgraphile:4` is now available on Docker hub and should solve this issue. 👍
