### ISSUE TITLE
Future roadmap

### ISSUE THREAD

**Issue by purplemana** [graphile/postgraphile#1076]
I'm submitting a ... 

* [ ] bug report
* [ ] feature request
* [x] question 

Is there a roadmap with a list of planned features and help needed info? It should help people interested in contributing. We can vote on the features as well.

**Comment by benjie** [comment]
No, we don’t have a roadmap (or deadlines, etc); instead we solve the issues that most need solving at the time. The GitHub issues that are open are a good indicator of things that need doing, and the v5 project (see the projects tab) indicates things planned for the next major release (however we’ll probably have a few more minor releases before then). The thing I’m currently working on is improving the Docker situation. A great place to stay up to date with what’s going on is our chat: http://discord.gg/graphile
