### ISSUE TITLE
Self-referencing one to many relations with postgraphile

### ISSUE THREAD

**Issue by purplemana** [graphile/postgraphile#1080]
I'm submitting a ... 

* [x] bug report
* [ ] feature request
* [x] question 

PostGraphile version: 4.4.0

I have two tables in my schema:

## services
Contains *id* and *name* of service

## dependencies
Contains *id* and *dependency_id* columns and stores service dependencies. Both of these columns reference the `services.id` column. This way a service can have other services as its dependencies.

With this schema, the GraphQL query for service type is generated as:

![Capture](https://user-images.githubusercontent.com/41626667/57931816-01805480-78d7-11e9-91bd-114336f3c554.PNG)

This won't allow a query where you can find all service dependencies of a service.

Is there an alternate schema where self-referencing one-to-many relations can work with pg?

Minimal SQL file that can be loaded into a clean database:

```sql

CREATE TABLE public.services
(
    id uuid NOT NULL DEFAULT uuid_generate_v1(),
    name text COLLATE pg_catalog."default" NOT NULL,
    chart text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "Services_pkey" PRIMARY KEY (id),
    CONSTRAINT "Services_name_unique" UNIQUE (name)
)

CREATE TABLE public.service_dependencies
(
    id uuid NOT NULL,
    dependency uuid NOT NULL,
    CONSTRAINT "ServiceDependencies_pkey" PRIMARY KEY (id, dependency),
    CONSTRAINT "fk_Services_dependency" FOREIGN KEY (id)
        REFERENCES public.services (id) MATCH SIMPLE
        ON UPDATE CASCADE
        ON DELETE CASCADE,
    CONSTRAINT "fk_Services_id" FOREIGN KEY (id)
        REFERENCES public.services (id) MATCH SIMPLE
        ON UPDATE CASCADE
        ON DELETE CASCADE,
    CONSTRAINT "Services_id_not_equal_dependency" CHECK (id <> dependency)
)
```

**Comment by benjie** [comment]
Sorry, I don't quite follow what you're asking. Maybe you're after a many-many relationship? If so, check out https://github.com/graphile-contrib/pg-many-to-many

**Comment by benjie** [comment]
Ohhh; I get it. You have `services -< service_dependencies >- services`. I think there's a bug in your schema, `fkServices_dependency declares a foreign key on `(id)` whereas I think you meant `(dependency)`.


If you're trying to walk the tree to find the entire list of dependencies, a function that uses a `WITH RECURSIVE` common table expression may be your best bet.

**Comment by purplemana** [comment]
Thanks! Missed that somehow. And thanks for the `WITH RECURSIVE` tip! I am new to Postgres, will read up on it.

Cheers mate!
