### ISSUE TITLE
Support for cross-schema computed columns

### ISSUE THREAD

**Issue by purplemana** [graphile/postgraphile#1082]
I'm submitting a ... 

* [ ] bug report
* [ ] feature request
* [x] question 

PostGraphile version:
v4.4.0

Currently computed columns are only added if the function is present in the same schema as the table. However, if my graphile instance is connected with say two schemas, is it somehow possible for a function defined in the second schema to be considered as a computed column for a table defined in the first schema?

An example is say `[auth]` schema has table `users` and `[todo_app]` schema has table `todos`. I wish to add a `Users.todos` computed column to get the todos of a user. However, the `[auth]` schema has been granted with SELECT only for my graphile engine. I cannot add a `users_todos` function in it. But having full access to the `[todo_app]` schema, I can add this function there.

Per the current docs, and I tried as well, graphile won't add the computed column this way. Is there some other way, e.g. with smart comments that I can do this? This would be an excellent way to allow query extensions while keeping separate schemas.

Thanks!

**Comment by benjie** [comment]
We don't currently have a bypass for this. Here's the line of logic enforcing that currently:

https://github.com/graphile/graphile-engine/blob/e68291bdd065b5711f066f1f11c0ac3539518cf0/packages/graphile-build-pg/src/plugins/PgComputedColumnsPlugin.js#L12

A smart comment such as "@forceComputedColumn" may be appropriate, should you wish to implement that (with tests):

```js
  if (proc.namespaceId !== table.namespaceId && !proc.tags.forceComputedColumn) return null;
```

Another approach is to use `makeExtendSchemaPlugin`

**Comment by purplemana** [comment]
Thanks @benjie, will explore adding support for smart comment. Closing this issue.
