### ISSUE TITLE
Can not run example queries on example DB

### ISSUE THREAD

**Issue by speller** [graphile/postgraphile#1084]
I'm submitting a ... 

* [ ] bug report
* [ ] feature request
* [x] question 

Hello, 
I'm trying to setup examples DB and use example queries https://www.graphile.org/postgraphile/examples/ . I've set up the DB. I've set up Graphile in AWS Lambda. I can see the GraphiQL interface. But I can not see schema (it tells Schema not found) and I can not run any query.

```
{
  forums {
    nodes {
      nodeId
      id
      slug
      name
      description
    }
  }
}
```

```
{
  "errors": [
    {
      "message": "Cannot query field \"forums\" on type \"Query\". Did you mean \"forum\", \"allForums\", \"forumById\", or \"forumBySlug\"?",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ]
    }
  ]
}
```

Okay, let's try something more simple and follow error suggestions.

```
{
  forum {
    nodes {
      nodeId
      id
    }
  }
}

```
```
{
  "errors": [
    {
      "message": "Cannot query field \"nodes\" on type \"Forum\". Did you mean \"nodeId\"?",
      "locations": [
        {
          "line": 3,
          "column": 5
        }
      ]
    },
    {
      "message": "Field \"forum\" argument \"nodeId\" of type \"ID!\" is required but not provided.",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ]
    }
  ]
}
```

```
{
  forum {
    name
  }
}
```

```
{
  "errors": [
    {
      "message": "Field \"forum\" argument \"nodeId\" of type \"ID!\" is required but not provided.",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ]
    }
  ]
}
```

And the same on any other query. What does it wants? What the `nodes` and `nodeId` mean if I don't have such fields in DB? I just need to get the list of forums. What should I do to perform a simplest query in the out of the box Graphile?

I didn't set up the `PgSimplifyInflectorPlugin` because I don't know how to set it up in `postgraphile-lambda-example`

**Comment by benjie** [comment]
The lambda example is advanced and easy to get wrong, I suggest you try and run PostGraphile locally first before graduating to lambda. Lambda is not intended to use the bundled GraphiQL; have you tried an external GraphiQL? Try following these steps: https://www.graphile.org/postgraphile/debugging/ - it could be that CORS or similar is causing issues.

**Comment by speller** [comment]
With the local instance of Graphile this works:

```
{
  allForums {
    nodes {
      name
    }
  }
}
```

But this not (the first example from the docs):

```
{
  forums {
    nodes {
      name
    }
  }
}
```

What's the difference?

**Comment by benjie** [comment]
Please be aware that these examples use the @graphile-contrib/pg-simplify-inflector plugin to simplify the field names over the defaults. You can use this via the following commands:

```
yarn add postgraphile @graphile-contrib/pg-simplify-inflector
yarn postgraphile --append-plugins @graphile-contrib/pg-simplify-inflector
```

`allForums` is the default name, if you use pg-simplify-inflector it becomes named `forums` as in the examples. Using `pg-simplify-inflector` is recommended.

**Comment by speller** [comment]
Thank you for the explanations! It's clear now.

**Comment by benjie** [comment]
Excellent! I shall close this issue.
