### ISSUE TITLE
Make order by case insensitive

### ISSUE THREAD

**Issue by alexisrolland** [graphile/postgraphile#1087]
I'm submitting a ...

* [ ] bug report
* [ ] feature request
* [x] question

PostGraphile version: v4.4.0
Minimal SQL file that can be loaded into a clean database:
```sql
CREATE TABLE public."my_table" ("name" TEXT NULL DEFAULT NULL);
INSERT INTO PUBLIC."my_table" ("name") VALUES ('a'),('B'),('c'),('D');
```

Steps to reproduce: Execute the GraphQL query below:
```sql
{
  allMyTables (orderBy: [NAME_ASC]) {
    nodes {
      name
    }
  }
}
```

Results are as follow:
```
{
  "data": {
    "allMyTables": {
      "nodes": [
        {
          "name": "B"
        },
        {
          "name": "D"
        },
        {
          "name": "a"
        },
        {
          "name": "c"
        }
      ]
    }
  }
}
```

Current behavior: Sort on values is case sensitive and orders uppercase letters in priority

Expected behavior: Sort on value is case insensitive and result for the data set above would be: a, B, c, D

Would you have any idea how to make the order by case insentive while still being able to use PostGraphile default queries / order by feature?

Thanks

**Comment by benjie** [comment]
Maybe name should use type “citext” rather than “text”?

**Comment by alexisrolland** [comment]
I'll try, thanks

**Comment by alexisrolland** [comment]
It works, thanks

**Comment by barbalex** [comment]
And how would I achieve this in a computed value?

Adding computed field `label` to the users table:
```sql
CREATE FUNCTION apflora.user_label (u apflora.user)
  RETURNS text
  AS $$
  SELECT
    coalesce(u.name || ' (' || replace(u.role, 'apflora_', '') || ')', '(kein Name)')
$$
LANGUAGE sql
STABLE;

-- make label sortable, as of postgraphile 4.4/postgraphile@next
COMMENT ON FUNCTION apflora.user_label (apflora.user) IS e'@sortable';
```

Querying it:
```graphql
query userQuery {
  allUsers(orderBy: LABEL_ASC) {
    nodes {
      label
    }
  }
}
```

The weird thing is: On my local dev PC this sorts case insensitive. Not so on the production server.

**Comment by benjie** [comment]
`returns citext` instead?

**Comment by barbalex** [comment]
@benjie what a great and simple idea. Sorry I had to bug you and did not notice myself.

For others finding this:

```sql
CREATE EXTENSION IF NOT EXISTS citext;

CREATE FUNCTION apflora.user_label (u apflora.user)
  RETURNS citext
  AS $$
  SELECT
    coalesce(u.name || ' (' || replace(u.role, 'apflora_', '') || ')', '(kein Name)')
$$
LANGUAGE sql
STABLE;

COMMENT ON FUNCTION apflora.user_label (apflora.user) IS e'@sortable';
```

**Comment by CarlosNZ** [comment]
Hmm, is there any other way to do this?

Changing the data type to be `citext` is not really an option in my case, as I don't want the field in question to be case-insensitive (it should accept "Name" and "nAme" as unique values), and we need pretty much every text field to be case-insensitive sortable. 

In SQL it's as simple as changing`ORDER BY first_name` to `ORDER BY lower(first_name)`. Is this something that could be controlled via a plugin (overriding the default Postgraphile `orderBy` mapping)? If so, I might have a look at building one.

**Comment by CarlosNZ** [comment]
> In SQL it's as simple as changing`ORDER BY first_name` to `ORDER BY lower(first_name)`

Or would you be open to making this a configurable [option](https://www.graphile.org/postgraphile/usage-cli/#cli-options) (if `true`, all text fields use SQL `ORDER BY lower(..)` for postgraphile `orderBy`) ?

**Comment by benjie** [comment]
That would be a really bad thing for performance, unless all of your indexes are also created over `lower(columnname)`. You can turn off the built in ordering (by adding `@omit order` to everything, which you can do via a plugin), and then add your own ordering (also via a plugin) if you really really need this. I do not want to add this as an option to core; you're the first person to ask for it in 6+ years where `citext` is not a more appropriate solution, and making it an option would make it more likely that people will use that rather than the typically more correct solution of using citext.
