### ISSUE TITLE
Result of transaction with non postgraphile client is invisible to selectGraphQLResultFromTable

### ISSUE THREAD

**Issue by jwickens** [graphile/postgraphile#1091]
I'm submitting a ... 

* [ ] bug report
* [ ] feature request
* [x] question 

PostGraphile version: 4.4.0

Is there a way to start a new transaction for selectGraphQLResultFromTable?

I have a custom resolver using extendSchemaPlugin that uses a postgres client in a transaction to insert the record I want to return. 

I commit this transaction and then try to use selectGraphQLResultFromTable, however this does not find the inserted row, presumably because postgraphile started a transaction before the non postgraphile client started and commited its transaction.

Using the provided initialized sql client is not possible as I need to use a legacy client (ORM).

**Comment by benjie** [comment]
In 4.x this is not possible without some hackery. In 5.x this will hopefully be possible.

Is it possible to use the existing transaction to insert the record you currently do in a separate transaction? You can use the pre-authenticated `pgClient` in the context object. If necessary, a PostgreSQL SECURITY DEFINER function might be the best bet to work around any permissions issues.

```js
async myResolver(obj, args, context, info) {
  const { pgClient } = context;
  await pgClient.query('insert into ...');
  return info.graphile.selectGraphQLResultFromTable(...);
}
```

**Comment by jwickens** [comment]
I'm sorry, this works perfectly well. For posterity and clarification here's what you can do:

```js
async myResolver(obj, args, context, info) {
  const createdId = await someThirdPartyTransaction();
  return info.graphile.selectGraphQLResultFromTable(...);
}
```

The reason I had the problem was because I was trying to select the result before the transaction completed.
