### ISSUE TITLE
@foreignKey on VIEW not work when ignoreIndexes: false

### ISSUE THREAD

**Issue by roytan883** [graphile/postgraphile#1101]
I'm submitting a ... 

* [*] bug report
* [ ] feature request
* [ ] question 

PostGraphile version: "4.4.0",

Steps to reproduce:

`comment on view test.roy_test_view is E'@foreignKey (author_uid) references basic.basic_user';` and postgraphile start with `ignoreIndexes: false`.

Current behavior:

```
Disabled 'read' permission for constraint "FAKE_test_roy_test_view_foreignKey_0" on view "test"."roy_test_view" because it isn't indexed. For more information see https://graphile.org/postgraphile/best-practices/ To fix, perform

CREATE INDEX ON "test"."roy_test_view"("author_uid");
```

Expected behavior:

@foreignKey on VIEW should work when `ignoreIndexes: false`. Because I can't add index on VIEW.

**Comment by mikeroelens** [comment]
@roytan883 did you find any simple workaround for this?

**Comment by benjie** [comment]
Fixed in https://github.com/graphile/graphile-engine/pull/496 (going out later today hopefully)
