### ISSUE TITLE
Possible typo in Schema Design docs

### ISSUE THREAD

**Issue by bstro** [graphile/postgraphile#1116]
* [ ] bug report
* [ ] feature request
* [x] question 

Hi there, I'm a beginner with Graphile and Postgres in general. I am following the [Schema Design](https://www.graphile.org/postgraphile/postgresql-schema-design/) doc closely (while making some naming changes as appropriate to my use case) and one of the commands throws an error upon execution.

The errant command in question is the definition for the `forum_example.register_person` function. In my case, the function looks like this:
```
create function hexagrams.register_user(
	name text,
	email text,
	password text
) returns hexagrams.user as $$
	declare
		user hexagrams.user;
	begin
		insert into hexagrams.user (name) values
		(name)
		returning * into user;
	
		insert into hexagrams_private.user_account (user_id, email, password_hash) values
			(user.id, email, crypt(password, gen_salt('bf')));
			
		return user;
end;
$$ language plpgsql strict security definer;
```

Upon execution, I receive the following error:

```
ERROR:  syntax error at or near "."
LINE 14:    (user.id, email, crypt(password, gen_salt('bf')));
```

Not sure why it seems to take issue with me accessing the `id` column on `user`. Any ideas?

**Comment by bstro** [comment]
Should the line `(user.id, email, crypt(password, gen_salt('bf')));` instead read `(user_id, email, crypt(password, gen_salt('bf')));` ?

**Comment by bstro** [comment]
Just to add some potentially helpful context, here's all the commands I've run so far:
https://gist.github.com/bstro/557eabacbf2f4cd69f6c1cb64cf20085

**Comment by benjie** [comment]
`user` is a reserved word in PostgreSQL; I believe that’s why Caleb used person as the name. Personally I prefer using plurals to avoid conflicts with built-ins; also I prefix my variables with `v_` to help avoid conflicts. If you put user in quotes `"user".id` should work.

**Comment by bstro** [comment]
Thanks a bunch! That makes sense.
