### ISSUE TITLE
Unable to access jwt.* variables in functions

### ISSUE THREAD

**Issue by speller** [graphile/postgraphile#1118]
I'm submitting a ... 

* [ ] bug report
* [ ] feature request
* [x] question 

PostGraphile version: current master

Function:
```
CREATE FUNCTION platform_public.test_func2() RETURNS text
    LANGUAGE sql IMMUTABLE PARALLEL SAFE
    AS $$select current_setting('jwt.claims.id')$$;
```

Graph query:
```
{
  testFunc2
}
```

Result:
```
{
  "errors": [
    {
      "message": "unrecognized configuration parameter \"jwt.claims.id\"",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "testFunc2"
      ]
    }
  ],
  "data": {
    "testFunc2": null
  }
}
```

What I'm doing wrong?

PS: Can not ask on http://discord.gg/graphile anymore, it says I have no rights to post. So writing here.

**Comment by speller** [comment]
My fail, the auth header was suddenly lost.

**Comment by benjie** [comment]
You should use `current_setting(..., true)`

Weird about Discord ?!!
