### ISSUE TITLE
Write-only fileds cannot be updated via mutation

### ISSUE THREAD

**Issue by angelosarto** [graphile/postgraphile#1120]
I'm submitting a ...

* [x] bug report
* [ ] feature request
* [ ] question 

PostGraphile version: 4.4.1

Minimal SQL file that can be loaded into a clean database:
Assuming schema, $SCHEMA and user $USER
```sql
CREATE TABLE $SCHEMA.test_write_only (
                                             "id" integer, PRIMARY KEY ("id"),
                                             normal text,
                                             write_only text
);
REVOKE SELECT ON $SCHEMA.test_write_only FROM $USER;
GRANT SELECT(id, normal) ON $SCHEMA.test_write_only TO $USER;
INSERT into $SCHEMA.test_write_only(id, normal, write_only) VALUES (1, 'you can see this', 'you can update me but not see me');
```

Steps to reproduce:
Load the table above replacing SCHEMA and USER with the postgraphile user
Run postgraphile (I am using this command,but I don't think it is relevant.
```bash
npx postgraphile -s $SCHEMA -p 35106 --dynamic-json --no-ignore-rbac \
 -c postgresql://l$USERl:$PASSWORD@localhost:32002/local_dev_db
```

Current behavior:

_This query works as expected_ 
```graphql
{
  allTestWriteOnlies {
    nodes {
      id
      normal
      #writeOnly cannot be querried and is not in api
    }
  }
}
```
_this query fails with error message: "permission denied for relation test_write_only"_
```graphql
mutation {
  updateTestWriteOnlyById(input: {
    id: 1
    testWriteOnlyPatch: {
     normal: "should be able to change and read"
		 writeOnly: "should be able to update but not read"
    }})
  { testWriteOnly
     {
      id
      normal
      # writeOnly -- cant see it so shouldn't be able to return it
    }
  }
}
```

Expected behavior:
It should be able to update the field, even if it cannot return it.

Use Case (if not a bug):
There are a small, but important set of fields that often users should be able to change but not retrieve - passwords, token secrets, etc.

Work Around Options:
* Allow the user read access and accept small risk
* DB Trigger on insert/update to copy the field content to a shadow field that the user has no-access to and clear the original fields content.

**Comment by benjie** [comment]
This is a known restriction: we don't support CRUD mutations on tables that you can't do `SELECT *` from (see "Don't use column-based SELECT grants" in [the PostGraphile requirements](https://www.graphile.org/postgraphile/requirements/)).

A better approach ("workaround") is to define a [custom mutation](https://www.graphile.org/postgraphile/custom-mutations/) to do exactly what you want.

You're probably right that `--no-ignore-rbac` should omit the mutation if column-level select grants are used.

**Comment by angelosarto** [comment]
Got it Sorry I didn't read this portion of the documentation. I think I had been using column grants only on update/delete.  I will define a custom mutation that uses security definer to write to the field.
I just wrote my first custom function / mutation today for another use case and It works so flawlessly.

Thanks for the response - This is awesome!
