### ISSUE TITLE
Add a smart comment to omit pagination arguments (e.g. @noPagination)

### ISSUE THREAD

**Issue by jazblueful** [graphile/postgraphile#1122]
I'm submitting a ...

* [ ] bug report
* [x] feature request
* [ ] question

PostGraphile version: 4.4.1

Connections (both simple and relay) are overkill for one-to-many relationships with only a handful of records.

For example user has e-mails. I'm sure my UI can handle if at most 5 e-mails are all displayed in my app without pagination. Therefore I'd like to get a basic list of all emails with the AppUser graphql type: 
```graphql
type AppUser {
   ...
   emails: [AppUserEmail]
}
```

Currently there is no easy way to denote this kind of desired behavior and I had to use smart comment to omit fk constraint completely and manually construct the graphql relationships using computed columns:

```sql
comment on constraint app_user_email__app_user_id__fkey on users.app_user_email is
  E'@omit';

create function users.app_user_emails(u users.app_user) returns users.app_user_email[] as $$
select array_agg(result::users.app_user_email)
from (
       select app_user_email.*
       from users.app_user_email
       where app_user_id = u.id
     ) result;
$$ language sql stable;

create function users.app_user_email_user(e users.app_user_email) returns users.app_user as $$
   select app_user.*
   from users.app_user
   where app_user.id = e.app_user_id
$$ language sql stable;
```
Maybe I have missed something, but it's way too much work for something that could be made automatic using an additional smart comment.

**Comment by benjie** [comment]
This should do the trick:
```
comment on constraint app_user_email__app_user_id__fkey on users.app_user_email is
  E'@simpleCollections only';
```

(If not, try `simpleCollection`, I cannot remember if it was plural or not.)

**Comment by jazblueful** [comment]
I already tried that. It gives me:
```graphql
appUserEmails(
  first: Int
  offset: Int
  orderBy: [AppUserEmailsOrderBy!]
  condition: AppUserEmailCondition
): [AppUserEmail!]!
```

**Comment by jazblueful** [comment]
Would be great if there was smart comment '@simpleCollections neither' or even better yet '@collections simple|relay|none|both', but that would be a breaking change

**Comment by benjie** [comment]
Ah; so your issue isn't the connection but the args. We don't have a smart comment to disable the args currently (maybe we'd do this via `@noPagination`? I think that implies non-filterable and non-orderable), but you can achieve it with a plugin currently. 

I think an arg-remover plugin would look something like this:

```js
function makeRemoveArgsPlugin(type, field) {
  return builder => {
    builder.hook('GraphQLObjectType:fields:field', (field, build, context) => {
      const {
        Self,
        scope: { fieldName },
      } = context;
      if (Self.name !== type || fieldName !== field) {
        return field;
      }
      return {
        ...field,
        args: {}
      };
    });
  }
}
```

Then use it like:

```js
appendPlugins: [
  makeRemoveArgsPlugin('AppUser', 'emails')
]
```

**Comment by jazblueful** [comment]
I tried
```javascript
makeRemoveArgsPlugin(type, field) {
  return builder => {
    builder.hook('GraphQLObjectType:fields:field', (f, build, context) => {
      const {
        Self,
        scope: { fieldName },
      } = context;
      if (Self.name !== type || fieldName !== field) {
        return f;
      }
      console.log(f);
      return {
        ...f,
        args: {},
      };
    });
  };
}
```
Console prints out:
```
{
  description: 'Reads and enables pagination through a set of `AppUserEmail`.',
  type: [AppUserEmail!]!,
  args: {},
  resolve: [Function: resolve]
}
```
It seems args are already empty so this plugin doesn't do anything and sure enough the args are still in the graphql schema.

**Comment by benjie** [comment]
Oh bother, you're right - I forgot there was another hook. This is what happens if you just write plugins straight into GitHub comment boxes 🤷‍♂️ 

Here's an updated plugin generator that hopefully will work:

```js
function makeRemoveArgsPlugin(targetTypeName, targetFieldName) {
  return builder => {
    builder.hook('GraphQLObjectType:fields:field:args', (args, build, context) => {
      const {
        Self,
        scope: { fieldName },
      } = context;
      if (Self.name !== targetTypeName || fieldName !== targetFieldName) {
        return args;
      }
      return {};
    });
  }
}
```

**Comment by jazblueful** [comment]
No worries, I got a very nice primer into writing custom plugins. Thank you for that. This plugin works yay! :)

**Comment by benjie** [comment]
I'm closing this since it's only been requested once and a solution exists.
