### ISSUE TITLE
The requested module 'postgraphile' does not provide an export named 'postgraphile'

### ISSUE THREAD

**Issue by AntonAL** [graphile/postgraphile#1124]
I'm submitting a ... 

* [x] bug report
* [ ] feature request
* [ ] question 

PostGraphile version:

4.4.1

Steps to reproduce:

I'm having simple middleware at `/server/postgraphile.js`:

```js
import {postgraphile} from 'postgraphile';

export default function (app) {
  app.use(postgraphile(process.env.DATABASE_URL, 'public', {
    /* settings, that does't matter here */
  }));
}
```

node --experimental-modules --es-module-specifier-resolution=node server.js

Current behavior:

I'm getting following error:
```
(node:3217) ExperimentalWarning: The ESM module loader is experimental.
file:///path_to_my_app/server/postgraphile.js:1
import {postgraphile} from 'postgraphile';
        ^^^^^^^^^^^^
SyntaxError: The requested module 'postgraphile' does not provide an export named 'postgraphile'
    at ModuleJob._instantiate (internal/modules/esm/module_job.js:93:21)
    at async ModuleJob.run (internal/modules/esm/module_job.js:108:20)
    at async Loader.import (internal/modules/esm/loader.js:134:24)
```

Expected behavior:

Server should start without errors.

**Comment by AntonAL** [comment]
Figured it out.

Postgraphile middleware function should be accessed by destructuring assignment as following:

```js
import postgraphile from 'postgraphile';

const {postgraphile: initPostgraphile} = postgraphile;

app.use(initPostgraphile(process.env.DATABASE_URL, 'public', {
    /* settings, that does't matter here */
  }));
```

**Comment by benjie** [comment]
I believe this is an issue with the experimental modules implementation in Node; we don’t currently support that (we only support commonjs), but I appreciate you finding the workaround and sharing it - hopefully it’ll help others who search for it. I’m going to close this issue for now, though we may add support for Node’s ES6 modules at some point (currently we only support it for TypeScript/Babel)
