### ISSUE TITLE
Tables not visible in graphql when created with UNLOGGED

### ISSUE THREAD

**Issue by brent-williams** [graphile/postgraphile#1135]
I'm submitting a ... 

* [ ] bug report
* [x] feature request
* [ ] question

PostGraphile version: 4.4.1

Minimal SQL file that can be loaded into a clean database:

```sql
create unlogged table "test1" (
  id serial primary key not null
);
```

Steps to reproduce:
```
npx postgraphile \
  --plugins @graphile/pg-pubsub \
  --connection "XXX" \
  --schema public \
  --watch \
  --append-plugins @graphile-contrib/pg-simplify-inflector,@graphile/subscriptions-lds \
  --port XXX \
  --export-schema-graphql ./graphql/XXX.graphql \
  --export-schema-json ./graphql/XXX.json \
  --cors \
  --enhance-graphiql \
  --simple-collections only \
  --live 
```

Current behavior:
test1 not visible in graphql (e.g. http://localhost:5001/graphiql) when unlogged is specified in the sql.  test1 works fine when unlogged is not specified.

Expected behavior:
test1 visible in graphql with or without unlogged.

Note:
Would like to specify unlogged in order to speed up inserts (measured 2x speedup).

**Comment by benjie** [comment]
We avoid unlogged/temporary tables here:

https://github.com/graphile/graphile-engine/blob/ae44c9800bb016de0e29138db5e3978b32bd0224/packages/graphile-build-pg/src/plugins/introspectionQuery.js#L181

I'd be happy to accept a PR that adds support for unlogged tables (definitely not temporary tables!), but it should be opt-in via a variable defined here:

https://github.com/graphile/graphile-engine/blob/ae44c9800bb016de0e29138db5e3978b32bd0224/packages/graphile-build-pg/src/plugins/introspectionQuery.js#L12

Which should be added to postgraphile-core here:

https://github.com/graphile/graphile-engine/blob/ae44c9800bb016de0e29138db5e3978b32bd0224/packages/postgraphile-core/src/index.ts#L381

(And also add tests in the postgraphile-core subpackage for it.)

If you're interested in taking this on feel free to ask for more guidance either here or on [our Discord](https://discord.gg/graphile).

**Comment by brent-williams** [comment]
Thanks @benjie, understood current behavior is by design but support possible with further effort.
