### ISSUE TITLE
Q: Using postgraphile w/ custom sockets

### ISSUE THREAD

**Issue by akaRem** [graphile/postgraphile#1137]
Let's say I want to use something like https://www.npmjs.com/package/express-ws or https://www.npmjs.com/package/ssh2 or just unix socket.
- Is it possible to connect graphile and custom WSS/event emitter? is it hard? what could you recommend?
- It looks like postgraphile creates own WSS.. is it possible to authenticate/authorize w/o passing extra auth middlewares?
- is it possible to somehow extract event handler from postgraphile and use it on other sockets/independent from http.

___

I'm interested in requests & subscriptions w/ non-standard transport , so I'm trying to understand how to solve this w/o extra coding and rewriting "everything" on each release.
At the same time I'd like to have "upstream" http server with current feature set.

Thanks in advance!

**Comment by benjie** [comment]
Our websocket support used to be implemented via an external plugin (it’s since been merged) so yes, all of this should be possible. The first place to start is to look at our server (as opposed to schema) plugin support:

https://www.graphile.org/postgraphile/plugins/

What auth do you have in mind? Is there a reason you’re not comfortable passing a `(req, res, next) => { /* ... */ next()}` middleware function?

**Comment by akaRem** [comment]
I think I've found my problem.
Postgraphile is awesome project, but it's too "entangled". I'm trying not to loose anything from its great functionality, but compose my server differently.

`postgraphile()` encapsulates too much and does too much. 
And I'm loosing myself while diving deeper into codebase.

Here is an example.
`[e/p]` for exported and private functions `/N` for number of lines: `[e]postgraphile/75` -> `[p]createPostGraphileHttpRequestHandler/766`-> `[p]withPostGraphileContextFromReqResGenerator/30` `[p]setupServerSentEvents/62` + lots of other private functions.
Exported functions are just small adapters for quite large all-in-one functions which hard to reuse and explore. And postgraphile looks like monolith when you either use it as is or don't use at all. And it feels like customisation is limited to settings and plugins.

Do you have any examples on how to create http/ws server from scratch?

**Comment by benjie** [comment]
If you're not happy with the PostGraphile server you can replace it and just use the PostGraphile schema directly, wrapped in whatever server you like; instructions on how to use the schema-only mode are here:

https://www.graphile.org/postgraphile/usage-schema/

**Comment by akaRem** [comment]
👍 Cool! thanks!
Do you have anything similar related to WS and subscriptions?

**Comment by akaRem** [comment]
I mean `subscriptions: Enable GraphQL websocket transport support for subscriptions (you still need a subscriptions plugin currently)
` from https://www.graphile.org/postgraphile/usage-schema/#api-createpostgraphileschemapgconfig-schemaname-options doesn't explain much..

**Comment by akaRem** [comment]
.. and I'm not saying that I'm not happy (this framework is really awesome and I didn't find anything comparable).. but I'm really missing some flexibility.

**Comment by benjie** [comment]
`subscriptions` just enables a bunch of subscriptions-related features in Graphile Engine, it doesn't actually add subscription _fields_ to the schema. You can do that any how you want depending on what subscriptions you want, e.g. you could use `makeExtendSchemaPlugin` to add your own custom subscriptions:

```graphql
type MySubscriptionFieldPayload {
  ...
}
extend type Subscription {
  mySubscriptionField: MySubscriptionFieldPayload
}
```

Once you've got a GraphQL schema you can serve it however you want; GraphQL is just a function call at the end of the day. You don't have to use websockets for subscriptions, GraphQL will give you back an event stream (technically in JS it's an async iterator) and you can serve that up over any transport you like; e.g.

```js
const mySchema = await createPostGraphileSchema(...);
const asyncIterator = await performQuery(mySchema, `subscription MySubscription { mySubscriptionField { ... } }`);
```

We only have one websocket implementation.

As for event emitters there's one supplied by the `@graphile/pg-pubsub` plugin but you can switch that out for whatever event emitters you want by using an alternate plugin.

**Comment by benjie** [comment]
> I mean subscriptions: Enable GraphQL websocket transport support for subscriptions (you still need a subscriptions plugin currently) from graphile.org/postgraphile/usage-schema/#api-createpostgraphileschemapgconfig-schemaname-options doesn't explain much..

Read more here:

https://www.graphile.org/postgraphile/subscriptions/

**Comment by akaRem** [comment]
Thanks!
