### ISSUE TITLE
Why I receive NULL in integer column when the postgres query returns NOT NULL?

### ISSUE THREAD

**Issue by arochoab** [graphile/postgraphile#1140]
I'm submitting a ... 

* [ ] bug report
* [ ] feature request
* [X ] question 

PostGraphile version:

4.4.3
<!--

Tested with PostgreSQL 9.4.6 and PostgreSQL 10.4.
I have this table:

`create table tc_hardware_acceso (id_hardware_acceso integer      not null primary key default nextval('id_hardware_acceso'),
                                 hardware_acceso    varchar(50)  not null unique,
                                 firma1_hardware    varchar(100) not null unique,
                                 id_printer_tickets integer              ,
                                 status_hardware    varchar(1)   not null,
                                 foreign key (id_printer_tickets) references tc_printers_tickets on update no action on delete no action,
                                 check (status_hardware in ('A', 'I')));
create index i1_tc_hardware_acceso on tc_hardware_acceso (id_printer_tickets);
grant ...` 

This table has 39 rows and 4 of them have not null value in column id_printer_tickets. When I run the following graphql query, I receive null in two of them and the correct value in the other 2 (only showed one example of each case):

Query 1:

`{
  tcHardwareAccesoByIdHardwareAcceso(idHardwareAcceso: 38) {
    firma1Hardware
    idPrinterTickets
    statusHardware
  }
}`

Result 1 (ok):

`{
  "data": {
    "tcHardwareAccesoByIdHardwareAcceso": {
      "firma1Hardware": "98-22-EF-16-08-F2",
      "idPrinterTickets": 1,
      "statusHardware": "A"
    }
  }
}
`
Query 2:

`{
  tcHardwareAccesoByIdHardwareAcceso(idHardwareAcceso: 2) {
    firma1Hardware
    idPrinterTickets
    statusHardware
  }
}
`

Result 2 (Wrong!):

`{
  "data": {
    "tcHardwareAccesoByIdHardwareAcceso": {
      "firma1Hardware": "54-EE-75-49-B2-47",
      "idPrinterTickets": null,
      "statusHardware": "A"
    }
  }
}
`

If I run directly on Postgres the generated query by postgraphile, I always receive the correct result:

`postgraphile:postgres select to_json((__local_0__."firma1_hardware")) as "firma1Hardware",
to_json((__local_0__."id_printer_tickets")) as "idPrinterTickets",
to_json((__local_0__."status_hardware")) as "statusHardware"
from "public"."tc_hardware_acceso" as __local_0__
where (
  __local_0__."id_hardware_acceso" = $1
) and (TRUE) and (TRUE)
`

Query in pgAdmin:

`select to_json((__local_0__."firma1_hardware")) as "firma1Hardware",
to_json((__local_0__."id_printer_tickets")) as "idPrinterTickets",
to_json((__local_0__."status_hardware")) as "statusHardware"
from "public"."tc_hardware_acceso" as __local_0__
where (
  __local_0__."id_hardware_acceso" = 2
) and (TRUE) and (TRUE)
`

Result from pgAdmin:

firma1Hardware       idPrinterTickets    statusHardware
"54-EE-75-49-B2-47"	   1	                      "A"

What am I doing wrong?

Thanks for your attention!

**Comment by benjie** [comment]
@arochoab Please use the issue template to file issues; I can't even begin to help you with this one as there is nowhere near enough information.
