### ISSUE TITLE
x-graphql-event-stream is invalid when graphqlRoute is "/"

### ISSUE THREAD

**Issue by mathroc** [graphile/postgraphile#1143]
when `graphqlRoute` is "/", `x-graphql-event-stream` become `//stream` and that's understood as a protocol relative uri by browsers, so they try to connect to https://stream/

one easy option would be to remove trailling "/" from `graphqlRoute` when building the `x-graphql-event-stream` header

I'd like it if `graphqlRoute: ""` was not mapped to `graphqlRoute: "/graphql"` but only when `null` or `undefined` but this would break backward compatibility

**Comment by benjie** [comment]
👍 we should check for trailing slash.
