### ISSUE TITLE
PostGraphile hanging on Google App Engine when feeding it a ridiculously complex GraphQL query 😈

### ISSUE THREAD

**Issue by garretteklof** [graphile/postgraphile#1155]
> Sorry, can't really help you - if it's a timeout then it's most likely a connectivity issue - the packets are literally not getting through (or getting back) - hence the timeout. Unless you think the server is hanging for some reason, but I've not known PostGraphile to hang except if you feed it a ridiculously complex GraphQL query 😈

_Originally posted by @benjie in https://github.com/graphile/postgraphile/issues/84#issuecomment-397224112_

Hello! First and foremost thanks so much for all your work on this library. It kicks a$$!

I'm currently running Postgraphile as the backend to a vast, intensive, data visualization platform. I've recently run into an issue where queries will seemingly hang (coming back as CORS 500 errors). It does not happen every time, but particularly beefy queries will set it off. It also only seems to happen on a staged environment on Google App Engine, and not on when running on a local Node server. Again, the queries are intensive -- I'm running Postgraphile with the PostGIS plugin -- and the queries involve pulling geometric boundaries in a table with (currently) ~850K rows and then via a foreign key finding properties on these fields in a table with ~18+ million rows. And there are a few filters (equalTo, greaterThan) on this query as well. The necessary columns are indexed.

Essentially, I'm just trying to figure out what my options are. I am not entirely sure how feasible shrinking the queries will be. The filtering and conditions are necessary, and unfortunately I do have to pull swaths of data. I have prepared to deal with it from a UI perspective (an extended wait time). My confusion is mainly coming from the discrepancy when coming from the local server onto the development environment, along with the CORS 'timeout'. Is there a way to set the timeout to zero ? (although of course not best practice). Then just wait the query out?

Any help / suggestions / pointing in the right direction would be greatly appreciated. I can also provide any more specifics if needed. Thanks so much!

**Comment by benjie** [comment]
Is pagination an option? I suspect your issue is insufficient RAM on the server, which may explain why it’s fine locally as you have more RAM? Everything gets loaded from the DB, unloaded into memory where it then runs through the various resolvers which may include plugins/etc, before finally being reserialised and sent to the end user. Using a newer version of Node may help a little also.

**Comment by garretteklof** [comment]
Unfortunately pagination isn't really an option (spitting all the data onto a Leaflet map on a US county-by-county basis). You were right about upping the RAM - I'm no longer getting 500's. Performance still leaves a lot to be desired, but this is of course little to do with Postgraphile, and far more due to the limitations of my GAE server (not to mention drawing thousands of little vector grid geometries from a single browser click event). Thanks again for your hard work on the library as well as your ridiculously expedient response times.
