### ISSUE TITLE
JSON[] Column Treated As TEXT[]

### ISSUE THREAD

**Issue by chris-guidry** [graphile/postgraphile#1178]
I'm submitting a question.

PostGraphile version: 4.4.3

I created a view with a column defined as JSON[]. In GraphiQL, the Docs show the field as [JSON], which seems correct, but then the GraphQL output is an array of strings like this:
```
"roles": [
  "{\"id\":5,\"name\":\"Data Viewer\"}",
  "{\"id\":3,\"name\":\"Device Manager\"}"
]
```

Is there a way to output it as an array of JSON objects rather than an array of strings?

**Comment by benjie** [comment]
Are you using the `dynamicJson` setting?

**Comment by chris-guidry** [comment]
@benjie I didn't know about that setting. Enabling it did the trick. Thank you for the quick response!
