### ISSUE TITLE
makeAddPgTableConditionPlugin only works with reeelay connections not normal connections

### ISSUE THREAD

**Issue by jefbarn** [graphile/postgraphile#1193]
I'm submitting a ... 

* [ x] bug report
* [ ] feature request
* [ ] question 

PostGraphile version:
4.4.5 and 4.5.0

makeAddPgTableConditionPlugin only works on the facebooky connections not normal connenctions. Also should probably update the docs that this deprecates postgraphile-plugin-custom-filter (which also doesn't work).

**Comment by benjie** [comment]
What do you mean by "normal connections"? Could you please post the steps to reproduce your issue?

**Comment by jefbarn** [comment]
Sorry 'Simple Collections', the kind you get with
simpleCollections: 'both',
