### ISSUE TITLE
Support For Docker Secrets

### ISSUE THREAD

**Issue by dargmuesli** [graphile/postgraphile#1194]
I'm submitting a ...

* [ ] bug report
* [x] feature request
* [ ] question

Docker supports secrets, so why not use them. Storing secrets as environment variables is [no good practice](https://diogomonica.com/2017/03/27/why-you-shouldnt-use-env-variables-for-secret-data/).
The postgres Docker image allows to define certain data as secrets (see https://hub.docker.com/_/postgres/ section "Docker Secrets"). So PostGraphile's cli script section that [loads data from environment variables](https://github.com/graphile/postgraphile/blob/6d82347db527ab54e6980c4ba1deb2579e336870/src/postgraphile/cli.ts#L556) only has to be extended in a way similar to what [the postgres Dockerfile's entrypoint script does](https://github.com/docker-library/postgres/blob/4a82eb932030788572b637c8e138abb94401640c/12/docker-entrypoint.sh#L9): check if there is e.g. a `POSTGRES_PASSWORD_FILE` environment variable and if that's the case load the data for the cli script's `password` variable from the file defined in the `..._FILE` environment variable! 🥳
Of course this would be needed for script parameters like `--owner-connection` and `--jwt-secret` too.

**Comment by benjie** [comment]
In library mode this isn't a concern - you can pull your settings in however you want.

In CLI mode (and by extension Docker mode) you can write your settings to a `.postgraphilerc.js` file; we bundle one with our Dockerfile but you're welcome to overwrite it with your own settings.

https://github.com/graphile/postgraphile/blob/master/docker/.postgraphilerc.js

Is that sufficient for your needs/concerns?

A PR enhancing the built in docker `.postgraphilerc.js` with support for `POSTGRES_PASSWORD_FILE` would be considered.

**Comment by dargmuesli** [comment]
Thanks for the hint! Your documentation [says](https://www.graphile.org/postgraphile/usage-cli/)

> Please note that this interface is deprecated and will be removed in v5 (but its replacement hasn't been built yet...). You're encouraged to use PostGraphile as a library rather than using a .postgraphilerc.js.

So is it really a good idea to enhance this file? Or is Docker's `.postgraphilerc.js` excluded from this?

Using this file would indeed be a good option, though. As its placement is limited to the to the current directory though, one would need to use the [long secret syntax for compose files](https://docs.docker.com/compose/compose-file/#long-syntax-2) to specify a custom path (just a hint for others).

**Comment by benjie** [comment]
I'm planning to replace it with an equivalent file that uses the library options rather than weird CLI options that are an artifact of how the CLI parsing library works. Since in Docker we have to use the CLI, `.postgraphilerc.js` is currently the right way of handling this.

You may want to track https://github.com/graphile/postgraphile/issues/705

**Comment by dargmuesli** [comment]
Alrighty, I'll give it a try :)
