### ISSUE TITLE
[RLS] How can I ban user_id and created_at fields update with updateMessage GraphQL mutation ?

### ISSUE THREAD

**Issue by harobed** [graphile/postgraphile#1208]
I'm submitting a

* [ ] bug report
* [ ] feature request
* [x] question

PostGraphile version: `4.5.0`

I have this table example:

```
CREATE TABLE messages (
    id          UUID PRIMARY KEY DEFAULT uuid_generate_v4() NOT NULL,
    msg         TEXT,
    user_id     UUID NOT NULL,
    created_at  TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
);
```

How can I ban `user_id` and `created_at` fields update with `updateMessage` GraphQL mutation ?

I have this mutation :

```
CREATE POLICY user_can_update_own_message
    ON
        public.messages
    FOR
        UPDATE
    TO
        user
    USING (
        user_id = (
            SELECT
                id
            FROM
                public.current_user()
        )
    )
    WITH CHECK (
        ...
    );
```

but how do I setup `WITH CHECK`?

Best regards,
Stéphane

**Comment by harobed** [comment]
Response from `ben-pr-p` (from Discord):

> @omit create,update – https://www.graphile.org/postgraphile/smart-comments/

Response from `Benjie` (from Discord):

> Or use noIgnoreRBAC and don’t grant those permissions :thumbsup:
> https://github.com/graphile/starter/blob/master/%40app/db/migrations/committed/000001.sql#L125
> Keep RLS; but you can use column-based grants to govern INSERT/UPDATE column permissions

**Comment by benjie** [comment]
:+1: 

A little more details... Permissions in Postgres primarily come in two flavours: role-based access control (RBAC) which governs access to tables, columns, functions, etc; and row-level security (RLS) which govers access to specific rows. RLS does not have column concerns, and RBAC does not have row concerns, so you use them both to achieve what you're after.
