### ISSUE TITLE
CRUD mutations with foreign key fields should accept a nodeId in those fields

### ISSUE THREAD

**Issue by RedShift1** [graphile/postgraphile#1212]
I'm submitting a ...

* [ ] bug report
* [X] feature request
* [ ] question

PostGraphile version: 4.5.5

In create/update mutations with foreign keys, the mutation needs to be supplied with the actual foreign key as known in the database, for example (users that can create posts):

```
mutation MyMutation
{
  createPost(input: {post: {text: "blabla", **userId: 10**}})
}
```
This is problematic because:

- The client performing the mutation needs to be aware of the userId, thus will need to fetch both nodeId and userId AND know where to use which one
- It reveals implementation details of the database

Ideally the createPost mutation should look something like this:

```
mutation MyMutation
{
  createPost(input: {post: {text: "blabla", **user: "some_user_nodeId"**}})
}
```

And then postgraphile automatically translates user into user_id from decoding "some_user_nodeId".

**Comment by benjie** [comment]
We have a plugin for this:

https://github.com/graphile/global-ids/blob/master/README.md

PRs to it welcome.
