### ISSUE TITLE
gql2pg generates wrong values in the case of json or numeric

### ISSUE THREAD

**Issue by obabichev** [graphile/postgraphile#1219]
I'm submitting a ... 

* [x] bug report

PostGraphile version: 4.5.0

Hallo, we are trying to implement a plugin for postgraphile to add mutations for the editing list of entities. At the current moment, I pushed the code into repo: [postgraphile-plugin-list-mutations](https://github.com/obabichev/postgraphile-plugin-list-mutations/blob/master/index.js). 

In the code of the plugin I use function `gql2pg` to insert values into SQL query. But in the case when I am trying to apply mutation to update `numeric` or `json` field it fails with the error: `column \"field\" is of type numeric but expression is of type text`

How to reproduce: [here is the code](https://github.com/obabichev/postgraphile-plugin-list-mutations/blob/master/bugs-reproducing/gql2pg-numeric-json.js) without workaround for this problem. 

For example, if we have the table:
```sql
CREATE TABLE partner
(
    id                   BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    money                  NUMERIC                NOT NULL,
);
```

The plugin will provide the possibility to make the next mutation:

```
mutation UpdatePartners {
  updatePartners(
    input: {
      partners: [
        { patch: { money: "300" }, id: "1" }
        { patch: { money: "400" }, id: "2" }
      ]
    }
  ) {
    clientMutationId
    partner {
      id
      money
    }
  }
}
```

To input values into future query I use line like `gql2pg(val, attr.type)` there `attr` took from `pgIntrospectionResultsByKind.attribute`. The source code of the genrating the query might be found in the repo linked above, and without workaround looks like:

```js
const joinValues = values => sql.join(values, ', ');

const query = sql.query`
    update ${sql.identifier(table.namespace.name, table.name)} t
    set ${sql.join(sqlColumns.map(col => sql.fragment`${col} = s.${col}`), ', ')}
    from ( values 
            ${joinValues(sqlValues.map(values => sql.fragment`(${joinValues(values)})`))}
        ) as s (id, ${joinValues(sqlColumns)})
    where t.id = s.id::bigint
    returning *;
    `;
```

For the case above it will generate query:
```sql
update "pricing"."partner" t
set
    "money" = s."money"
from (values
          ($1, $2),
          ($3, $4)
     ) as s (id, "money")
where t.id = s.id::bigint
returning *;
```
And values:
```js
["1", "300", "2", "400"]
```

And this query fails with error:
```
[42804] ERROR: column "money" is of type numeric but the expression is of type text Hint: You will need to rewrite or cast the expression.
```

The same thing with the json type, and maybe with some another (I checked only on these two).

I looked at the [source code](https://github.com/graphile/graphile-engine/blob/b3c4d0754f03a1319cfd119c542d4a987bc4df2f/packages/graphile-build-pg/src/plugins/PgTypesPlugin.js#L134) of gql2pg, and seem like it should work with this types, so I think that we are doing smth wrong, but we can not realize what.

The main questions:
- Ho to make the plugin to work with different postgres types
- Is what we are doing, in general, the right way to implement plugins

I think that this plugin might be open sourced if other developers need it (and we adapt for more generic cases), but we need to make it in the right way for it.

Current workaround: explicitly add casts for these types like `::numeric` or `::json`, but with this, it might be broken when a new field with the same problem appears.

**Comment by obabichev** [comment]
I tried to reproduce the problem by the implementation without the usage of postgraphile code:

```js
const sql = require("pg-sql2");
const {Client} = require('pg');

const connectionString = 'postgresql://pricing@localhost:5433/pricing';
const client = new Client({
    connectionString: connectionString,
});

const tableName = 'test_table';
const namespace = 'testing';

const inputData = [
    {
        "id": "1",
        "patch": {
            "value": {test: "JSON"}
        }
    },
    {
        "id": "3",
        "patch": {
            "value": {test: "JSON"}
        }
    }
];

const columns = Object.keys(inputData[0].patch);

const joinValues = values => sql.join(values, ', ');

const sqlColumns = joinValues(columns.map(column => {
    return sql.identifier(column);
}));

const sqlValues = joinValues(inputData.map(entity => {
    return sql.fragment`(${joinValues([sql.value(entity.id), ...columns.map(column => {
        return sql.value(entity.patch[column]);
    })])})`;
}));

const query = sql.query`
    update ${sql.identifier(namespace, tableName)} t
    set ${joinValues(sqlColumns.map(column => sql.fragment`${column} = s.${column}`))}
    from ( values ${sqlValues} ) as s (id, ${sqlColumns})
    where t.${sql.identifier('id')} = s.id::bigint
    returning *;
    `;

const {text, values} = sql.compile(query);

console.log('text', text);
console.log('values', values);

client.connect();
client.query(text, values, (err, res) => {
    if (err) {
        console.log('err', err);
    } else {
        console.log('rows', res.rows);
    }
    client.end()
});
```

In this case I get query:
```sql
    update "testing"."test_table" t
    set "value" = s."value"
    from ( values ($1, $2), ($3, $4) ) as s (id, "value")
    where t."id" = s.id::bigint
    returning *;
```

values:
```
[ '1', { test: 'JSON' }, '3', { test: 'JSON' } ]
```

And an error:
```
error: column "value" is of type JSON but the expression is of type text
```

And it's quite logical because this code doesn't know anything about types. If I am right `gql2pg` function should solve this problem, but this function is the part of `graphile-engine`, so I can not simply take it from there... 

In general, I already feel a bit better with the parts of postgraphile. I understood how the introspection process works and how it takes the description of the DB by one SQL query (`makeIntrospectionQuery` function). But I need to understand how this information connected with GraphQL types and why methods of `inflection` object are deprecated (and what to use instead)

**Comment by benjie** [comment]
>  why methods of inflection object are deprecated (and what to use instead)

Use `build.inflection`; the old inflection file is not used any more. See https://www.graphile.org/postgraphile/inflection/

---

Regarding gql2pg, it's not designed to add casts everywhere; it's up to you to do that if you need to. You can do so using something like `${gql2pg(value, attr.type)}::${sql.identifier(attr.type.namespaceName, attr.type.name)}` I think? (Not sure if this handles array types off-hand.)

We mostly use gql2pg in places where PostgreSQL can infer the type, but by using it in the `VALUES()` you're doing it's being casted to text (because Postgres doesn't know any better) and then that's causing issues.

**Comment by obabichev** [comment]
Thanks a lot, it was really helpful, I think, the plugin became much cleaner. If someone needs the code, it's here: https://github.com/obabichev/postgraphile-plugin-list-mutations/blob/master/index.js

I understood that problems of returning row data from DB (for example, JSONs return as a string at the current moment), because of I don't use `getDataFromParsedResolveInfoFragment`, `viaTemporaryTable` and so on, I will spend time for it, but it should be ok.

I think this issue might be closed, I hope if it will be useful for people how will write plugins.
