### ISSUE TITLE
Possible to mark composite type fields as nonNull?

### ISSUE THREAD

**Issue by davbeck** [graphile/postgraphile#1228]
I'm submitting a ... 

* [ ] bug report
* [ ] feature request
* [x] question 

PostGraphile version: 4.5.5

I'm trying to create a custom create function that matches the style of the auto generated create mutations. Here's what it looks like:

```sql
CREATE TYPE volunteer.membership_individual_input AS (
  name text, 
  phone text,
  team_id uuid,
  role volunteer.team_role
);
COMMENT ON COLUMN volunteer.membership_individual_input.name IS E'@nonNull\nThe name of the new individual.';
COMMENT ON COLUMN volunteer.membership_individual_input.phone IS E'A phone number to add to the new individual.';
COMMENT ON COLUMN volunteer.membership_individual_input.team_id IS E'@nonNull\nThe team to add the new individual to.';
COMMENT ON COLUMN volunteer.membership_individual_input.name IS E'@nonNull\nThe role of the new individual in the team.';

CREATE FUNCTION volunteer.create_membership_individual(
  input volunteer.membership_individual_input
)
RETURNS volunteer.membership
LANGUAGE plpgsql STRICT
AS $$
DECLARE
  individual volunteer.individual;
  membership volunteer.membership;
BEGIN
  INSERT INTO volunteer.individual (name) 
    VALUES (input.name)
    RETURNING * INTO individual;

  IF input.phone IS NOT NULL THEN
    INSERT INTO volunteer.phone
      (individual_id, number) 
      VALUES (individual.id, input.phone);
  END IF;
  
  INSERT INTO volunteer.membership (team_id, individual_id, role)
    VALUES (input.team_id, individual.id, input.role)
    RETURNING * INTO membership;

  return membership;
END;
$$;
```

It's a shortcut for creating 3 objects at once (which depend on the output of the first) since the clients do this as a single operation in the UI. The GraphQL schema that gets generated from this marks `input` and `phone` as nullable (good) but also `name`, `team_id` and `role` as nullable (not so good).

Is it possible to customize the nullability of these fields from smart comments? The documentation comment gets applied correctly. Is there a better way to create custom create mutations?

**Comment by davbeck** [comment]
I just realized I'm getting a nested `input` for the mutation. So I guess this is what the function should look like:

```sql
CREATE FUNCTION volunteer.create_membership_individual(
  individual_id uuid,
  name text, 
  phone text,
  team_id uuid,
  role volunteer.team_role
)
-- ...
```

But that still leaves the issue of having individual nullable arguments. If I add `STRICT` they are all marked as non-nullable, and if I omit it, they are all nullable.

**Comment by benjie** [comment]
For arguments, have a look at `pgStrictFunctions`; it's a Graphile Engine setting that's really good and will probably be enabled in v5 by default, but it's not currently documented.

For the input types, is it treating the input as a "patch"? You might need to tell it to use the "create" variant which you can do with the `@arg0variant` smart comment.

**Comment by davbeck** [comment]
I don't think `@arg0variant` applies here because this is a completely custom composite type, not the type of a table.

**Comment by benjie** [comment]
Indeed; we only generate the patch type if the `pg_class` (table, type, etc) is selectable:

https://github.com/graphile/graphile-engine/blob/9dca5c8631e6c336b59c499d901c774d41825c60/packages/graphile-build-pg/src/plugins/PgTablesPlugin.js#L225

This code suggests that the `@notNull` comment should work:

https://github.com/graphile/graphile-engine/blob/9dca5c8631e6c336b59c499d901c774d41825c60/packages/graphile-build-pg/src/plugins/PgColumnsPlugin.js#L157-L162

Oh :man_facepalming: I see your mistake - you've written `@nonNull` rather than `@notNull`. I should have spotted this faster.

**Comment by davbeck** [comment]
Oh my 😳. This is not the first time I've made that exact typo.

Thank you so much for your patience.

**Comment by benjie** [comment]
No problem. This is one of the issues of the tags system being so open... Perhaps I'll bake something into v5 where you get warnings if you use unknown tags.
