### ISSUE TITLE
How to replace field type with another type

### ISSUE THREAD

**Issue by jazblueful** [graphile/postgraphile#1231]
I'm submitting a ... 

* [ ] bug report
* [ ] feature request
* [x] question 

PostGraphile version: 4.6.0

I'm trying to write a plugin that works on a type's (targetTypeName) field (targetFieldName) so that it transforms the connection field into singular one by resolving the first item in the connection.

```js
const createTransformManyToFirstPlugin = (targetTypeName, targetFieldName) => {
  return builder => {
    builder.hook('GraphQLObjectType:fields:field', (field, build, context) => {
      const {
        Self,
        scope: { fieldName },
      } = context;

      if (Self.name !== targetTypeName || fieldName !== targetFieldName) {
        return field;
      } else {
        const { graphql } = build;
        const fieldType = graphql.getNamedType(field.type);

        return {
          ...field,
          // Even though the type is valid,
          // changing it makes console.log(result.data) undefined.
          type: graphql.getNamedType(fieldType._fields().nodes.type),
          async resolve(...args) {
            const result = await field.resolve(...args);
            console.log(result.data); // undefined
            return result.data[0]['@edges']['@node'];
          },
        };
      }
    });
  };
};
```
The problem is that as soon as I modify the returned type, the original resolve function returns undefined for data.

I hope you can guide me to the right direction. Thank you!

**Comment by benjie** [comment]
You’d be much better off omitting the field and adding a replacement; however if you’re expecting exactly one result you may be able to solve this by adding the relevant unique constraint to the database, then we’ll automatically make it singular.

**Comment by jazblueful** [comment]
Thank you @benjie, I was using pg-many-to-many plugin, but the problem was that it wasn't really many-to-many relationship but inheritance instead. I solved it by using postgres builtin inheritance feature.
