### ISSUE TITLE
respect variables in query string when using application/graphql with POST

### ISSUE THREAD

**Issue by dobe** [graphile/postgraphile#1240]
I'm submitting a ... 

* [ ] bug report
* [ X] feature request
* [ ] question 

PostGraphile version: 4.4.4

postgraphile should honor variables in query string as defined in https://github.com/graphql/express-graphql#http-usage when the query is provided as post body.

with the following example request postgraphile does not honor the variables in the query string:

```
curl -XPOST 'localhost:5000/graphql?variables={"id":1}' -H 'content-type: application/graphql'  -d '
query MyQuery($id: Int) {
  something(id:$id) {
    name
  }
}
'
```
it would be nice if postgraphile  could do this out of the box in order to support static query bodies from the client.

**Comment by benjie** [comment]
I don't intend to support this feature; the GraphQL over HTTP spec (which I'm a member of the working group on) agree that parameters should be sent via the POST body:

https://github.com/graphql/graphql-over-http/blob/master/spec/GraphQLOverHTTP.md#post

You can solve this problem in your own applications by using the [schema-only usage](https://www.graphile.org/postgraphile/usage-schema/) and implementing your own GraphQL middleware.
