### ISSUE TITLE
How to make a simple query not using the id or the nodeid as a parameter?

### ISSUE THREAD

**Issue by CarlFMateus** [graphile/postgraphile#1242]
I do not speak English well. I am trying to make this kind of query but you can't. What do I need to add in the database to generate this query without using a postgresql function?

query{
  tbuser(id: 1, alias: 1122312){
    id
    name
  }
}

`query{
  tbuser(id: 1, alias: 1122312){
    id
    name
  }
}`

**Comment by CarlFMateus** [comment]
Can you somehow generate this in postgresql?

**Comment by benjie** [comment]
What do you intend `tbuser` to do?

**Comment by CarlFMateus** [comment]
In the database that the company has tbuser means one of the many tables in the database. what I want is for the aliasId to be part of the simple query

**Comment by benjie** [comment]
Please can you share the definition of `tbuser`? Include all constraints (primary keys, foreign keys, etc) and any unique indexes.

**Comment by CarlFMateus** [comment]
What a pity I can not send you the columns or what is part of that table since it is confidential information, the tbuser refers to the name of the table that is made in postgres

**Comment by benjie** [comment]
The following table:

```sql
create table tbuser (
  id int,
  alias text,
  name text,
  primary key (id, alias)
);
```

should generate the query:

```graphql
type Query {
  tbuserByIdAndAlias(id: Int!, alias: String!): Tbuser
}
```

which you can query in the way you have specified.
