### ISSUE TITLE
Question around renaming/aliasing

### ISSUE THREAD

**Issue by cazzer** [graphile/postgraphile#1245]
I'm submitting a ... 

* [ ] bug report
* [ ] feature request
* [x] question 

Postgraphile version: 4.6.0

**Very general question:**

Are there any ways to rename tables/columns _without_ smart comments? My team using comments in Postgres as our documentation, so cluttering it with annotations for specific libraries that access the database is a heavier lift. It seems like I might be able to use a custom inflector, but that also feels like overkill for just changing a couple works here and there. It would also be valuable to map enum values...

**Comment by benjie** [comment]
It seems like you might be interested in smart tags; it’s basically smart comments but in a JSON file. https://www.graphile.org/postgraphile/smart-tags/
