### ISSUE TITLE
Discord link is broken/invalid

### ISSUE THREAD

**Issue by stevelizcano** [graphile/postgraphile#1254]
I'm submitting a ... 

* [ x] bug report
* [ ] feature request
* [ ] question 

Steps to reproduce:

Click the discord link on the homepage, says invalid invite link.

Current behavior: Failure to join discord

Expected behavior: Amazing discord channel.

**Comment by benjie** [comment]
Hey @stevelizcano I've tried finding the broken link, but I cannot. All the links I can find are to `http://discord.gg/graphile` or `https://discord.gg/graphile` which both seem to work correctly for me, even incognito. Could you take a screenshot of the relevant link to help me track it down please?

**Comment by stevelizcano** [comment]
Hi Benjie,

It's a weird error. It worked on my mobile when visiting, and on Chrome latest on MacOS when clicking the big "JOIN CHAT" button here:

![image](https://user-images.githubusercontent.com/25097587/78268886-28ed0980-7509-11ea-934e-dc0675512fed.png)

I then see:

![image](https://user-images.githubusercontent.com/25097587/78268956-3f936080-7509-11ea-982b-d7348925b98e.png)

**Comment by benjie** [comment]
The source for the Join chat button seems to be the same as others, and I don’t get this issue. Very odd. Can you try from a different computer?

 https://raw.githubusercontent.com/graphile/graphile.github.io/develop/src/pages/postgraphile/index.mdx

**Comment by stevelizcano** [comment]
It works on a different computer, it must be a discord issue or something. Closing!

Thanks for an awesome product !

**Comment by benjie** [comment]
Thanks for checking @stevelizcano :+1:
