### ISSUE TITLE
FileUpload with Fastify/Postgraphile

### ISSUE THREAD

**Issue by mthota15** [graphile/postgraphile#1268]
I am looking for help on implementing fileupload service with Fastify/Postgraphile. I tried using the following plugin postgraphile-plugin-upload-field but i am not able to make it work with Fastify framework.

#https://github.com/graphile-contrib/postgraphile-plugin-upload-field/issues/10

**Comment by benjie** [comment]
Please use StackOverflow or Discord chat to ask for this help. You may want to check out the PRs on the Graphile Starter repo too.
