### ISSUE TITLE
CLI switch for graphileBuildOptions?

### ISSUE THREAD

**Issue by Zireael** [graphile/postgraphile#1275]
I'm submitting a ... 

* [ ] bug report
* [ ] feature request
* [x] question 

Hi, is there a CLI switch version of `graphileBuildOptions` option object? For example to provide plugin options when starting a docker image with docker.compose.yml
Well, I can imagine providing options through CLI string wouldn't be the most readable/convenient idea... Alternatively, is there a way to bake/merge the `graphileBuildOptions` into a Dockerfile so that they are picked up when the container later gets started through docker-compose or kubernetes CLI command?

The [CLI help page](https://www.graphile.org/postgraphile/usage-cli/) mentions that there are more CLI options than the ones listed there. It would be nice if we have a complete list of CLI options somewhere.
I tried looking through source code, but couldn't find a file where CLI switches are defined.

PostGraphile version: 4.7.0

**Comment by benjie** [comment]
I think that’s poorly written; it meant more than those mentioned above and then proceeds to give an exhaustive list. You can use a postgraphilerc to supply graphileBuildOptions 👍

**Comment by benjie** [comment]
I'm not going to add a CLI argument for graphileBuildOptions - the CLI requires fewer options, not more. Closing this since postgraphilerc solves the issue.
