### ISSUE TITLE
Column permissions interaction with mutations

### ISSUE THREAD

**Issue by anmolsahoo25** [graphile/postgraphile#1284]
I'm submitting a ... 

* [ ] bug report
* [x] feature request
* [ ] question 

PostGraphile version: 4.7.0

Minimal SQL file that can be loaded into a clean database:

```sql
create table test1(id serial primary key, username text, firstname text, lastname text);
insert into test1(username, firstname, lastname) VALUES('username1', 'firstname1', 'lastname1');
insert into test1(username, firstname, lastname) VALUES('username2', 'firstname2', 'lastname2');

grant select(id, firstname) on test1 to postgraphile;
grant update(firstname) on test1 to postgraphile;
```

Steps to reproduce:
```
postgraphile -c postgres://username:password@localhost/database
```

Query 
```
mutation {
  updateTest1ById(input: {id: 1, test1Patch: {firstname: "firstname3"}}) {
    test1 {
      firstname
    }
  }
}

```

Current behavior:
This currently errors out with a permission denied error, which is understandable as the SQL query is - 
```
update "public"."test1" set "firstname" = $1
  where (
    "id" = $2
  ) returning *
)
select (
  (
    case when __local_0__ is null then null else __local_0__ end
  )
)::text
```
The `returning *` will error out because it does not have the permission to return the entire row.

Expected behavior:
Would it be better if we only returned the required fields, as specified by the payload? I do not have an idea about the architecure of postgraphile, but would be willing to contribute if required. 

At the same time, an alternative is to use the exclude smart comment to get rid off the rows and grant select on all columns.

**Comment by benjie** [comment]
"Don't use column-based SELECT grants" is listed in the PostGraphile requirements:

https://www.graphile.org/postgraphile/requirements/

I recognise the desire for this, and will be keeping it in mind during the V5 work, but no guarantees as there's a [lot](https://github.com/graphile/postgraphile/projects/5) of [things](https://github.com/graphile/postgraphile/issues?q=label%3A%22%F0%9F%94%81+revisit-in-v5%22+) [requested](https://github.com/graphile/graphile-engine/issues?q=sort%3Aupdated-desc+label%3Aconsider-for-v5+) for v5.

**Comment by anmolsahoo25** [comment]
Ah, sorry for the spurious request. In my hurry to dive into the implementation, I forgot to read the docs properly. 

Really enjoy working with Postgraphile, you are truly doing amazing work!
