### ISSUE TITLE
add a warning that postgraphile creates a new schema

### ISSUE THREAD

**Issue by erkandem** [graphile/postgraphile#1286]
I'm submitting a ... 

[ x ] bug report
[ x ] feature request

Nothing should modify a database without at least a warning.  You won't change adding a schema. So at least put a warning next to the "try it out now" commands. It's not obvious that a schema is created. I only realized it when I noticed that a pipeline in my app which depends on postgres schemas broke.

PostGraphile version:
whatever npx currently installs

Steps to reproduce:
From https://www.graphile.org/postgraphile/
```
Try it now:
npx postgraphile -c my_db --watch
requires Node.js 8.6 or higher
```
Current behavior:
 - new schema `postgraphile_watch` created

Expected behavior:
 - at least(!) document that it modifies the database. 
 - issue warning in CLI or add confirmation step to the launch.

**Comment by benjie** [comment]
The [CLI docs](https://www.graphile.org/postgraphile/usage-cli/) do note this occurs:

```
-w, --watch
automatically updates your GraphQL schema when your database schema changes (NOTE: requires DB superuser to install postgraphile_watch schema)
```

You get the same from `postgraphile --help`. Nonetheless I've added a note to https://www.graphile.org/postgraphile/

**Comment by erkandem** [comment]
being accessible via `--help` is nice but useless if the project advertises a single command usage.

the note below the  command at `graphile.org/postgraphile/` **is** a better way. 
thank you =)  *puts down his pitchfork and extinguishes torch*
