### ISSUE TITLE
Make subscriptions work with tables that have names in singular (animal instead of animals)

### ISSUE THREAD

**Issue by RoeiRom** [graphile/postgraphile#1287]
* [x] bug report
* [ ] feature request
* [ ] question 

PostGraphile version: 4.6.0
Steps to reproduce: create table with the name as singular (animal instead of animals)

Current behavior: related node of subscription is null

Expected behavior: related node of subscription is not null

**Comment by benjie** [comment]
Hi @RoeiRom from the docs:

```
select pg_notify(
  'postgraphile:hello',
  json_build_object(
    '__node__', json_build_array(
      'foos', -- IMPORTANT: this is not always exactly the table name; base64
              -- decode an existing nodeId to see what it should be.
      32      -- The primary key (for multiple keys, list them all).
    )
  )::text
);
```

I think you're putting the table name into the json_build_array; however as the note there specifies it's not always exactly the table name. I can confirm that subscriptions definitely works with singular table names.

**Comment by RoeiRom** [comment]
My table name is results_change_log, what is the name to put in the pg_notify.

**Comment by benjie** [comment]
As the comment in the code block above says: fetch an existing record, look at it's nodeId, and apply base64 decoding to it. You'll see what it needs to be. My guess would be `results_change_logs`. Share your base64 decoded nodeId if you need more help.
