### ISSUE TITLE
[Documentation] Best-practice - Should schemas named singular or plural?

### ISSUE THREAD

**Issue by benbender** [graphile/postgraphile#1288]
* [x] bug report
* [ ] feature request
* [x] question

I'm starting to dig around with postgraphile and I'm a bit confused by reading the docs and examples. On some of them it's explicitly stated (f.e. [forum-example](https://github.com/graphile/postgraphile/blob/v4/examples/forum/TUTORIAL.md#the-person-table)) that one should use singular schema-names but in the [example-db](https://github.com/graphile/examples/blob/master/db/400_users.sql#L9) and the [starter](https://github.com/graphile/starter/blob/master/data/schema.sql#L106) plural names are used.

So I would like to ask which method is the actual "best practice" and would propose to clarify in docs/examples to avoid confusion for newcomers. 

BTW: Thanks for the awesome work and methodology!

**Comment by benjie** [comment]
It's roughly 50/50, from my experience. Both sides argue strongly, and no-one wins. It doesn't really matter so long as you're consistent.

Caleb wrote some of the guides, and he prefers singular naming for various reasons explained in the schema design guide. His reasons are reasonable.

I wrote a lot of the more recent examples (such as Graphile Starter, and the examples repo) and I prefer plural naming. My reasons are also reasonable.

My preference for plural naming is pragmatic: PostgreSQL uses singular naming for builtins, so if I use plural then the chances of conflict are massively reduced. I could justify it further by saying things like  "a table is a collection of entities, so it should be plural" and "I want to SELECT a record from the list of USERS (plural); it just makes gramatical sense!" but honestly it's the pragmatic avoidance of clashes which was the clincher for me. In particular `user` is a reserved word, but `users` is not, and for me the `users` table is one of the most commonly referenced tables, so having to wrap it in quotes Every. Single. Time. would be a chore. You'll notice that Caleb's examples often use `person` to bypass this issue.
