### ISSUE TITLE
Parse resolver result

### ISSUE THREAD

**Issue by renehauck** [graphile/postgraphile#1294]
Hi, I am currently trying to develop a nestjs module from postgraphilic. 
But unfortunately I'm stuck on a small part of it. For this module I need the plugin `makeWrapResolversPlugin`. 
But now I have the problem that the answer of the postgraphile resolver does not quite match the Graphql schema. 

for example:

```typescript
return makeWrapResolversPlugin(
      (context, build, field, options) => {
       ....
      },
      (all) => async (resolver, source, args, context, info) => {
        ...
          // result is {"data":{"@addressEntity":{"id":14}}}
          // but I need {"data":{"addressEntity":{"id":14}}}
          const result = await resolver(source, args, context, info);
        ...
      }
    );
```
In this example I have chosen a simple case where I could simply remove the "@" in the property, but it is also possible to generate much more complex queries.
Is it possible to parse this answer, or is it possible to catch the final result in one place?

thank you so much for your work :smiley:

**Comment by benjie** [comment]
Non-leaf resolvers do not need to return data that conforms to the shape of the GraphQL schema, non-leaf resolver results are automatically passed into the next layer of resolvers by the GraphQL execution process (here's a relevant part of the GraphQL spec: https://spec.graphql.org/draft/#sec-Value-Completion).

Removing the `@` is __not__ safe; the `@` signifies that a dynamic value is in use, in this case the `@` key may be changed by using a GraphQL field alias.

I'm not familiar with Nest, could you elaborate a little further on what you're trying to achieve?

**Comment by renehauck** [comment]
I would like to forward the answer from the resolver into some kind of afterware.
I now have a small implementation for this which is not so nice, but executable.
If a parse/resolve is not possible, it works like this:

```typescript
const res = req.res;

    const oldEnd = res.end;
    res.end = (data) => {
      res.end = oldEnd;
      const sub: Subscriber<unknown> = req.__Subscriber_sub;
      try {
        delete req.__Subscriber_sub;
        const obj = JSON.parse(data);
        sub.next(obj);
      } catch (error) {
        sub.next(null);
      }
      return sub.complete();
    };
```

**Comment by benjie** [comment]
We have a PostGraphile server plugin hook for augmenting the result:

https://github.com/graphile/postgraphile/blob/8a0c6a8a68797f94f58eda48dc20f03405ebe000/src/postgraphile/http/createPostGraphileHttpRequestHandler.ts#L808

https://www.graphile.org/postgraphile/plugins/

I would caution heavily against modifying the result of a GraphQL query after resolution time though.

If you simply want to dispatch GraphQL queries through a different means than HTTP, you should look into schema only usage: 

https://www.graphile.org/postgraphile/usage-schema/

**Comment by renehauck** [comment]
ok, thank you so much :smiley:
