### ISSUE TITLE
Dynamically switch schema using postgraphile

### ISSUE THREAD

**Issue by ImranBashir43** [graphile/postgraphile#1295]
Hi,

I want to switch postgraphile schema dynamically based on HTTP request headers.

using one schema per tenant approach,want to switch schema for every request based on headers.

Here is my code snippet for postgraphile.

app.use(function(req,res,next){
let schemaName = "+req.headers.businessid+";
postgraphile(db, schemaName, {
ignoreRBAC: true,
extendedErrors: ["errcode", "detail", "hint"],
enhanceGraphiql: true
graphiql: true,
appendPlugins: [
//plugins
],
})
next();
});

and when i hit the endpoint i've got following output.
![schema](https://user-images.githubusercontent.com/47963406/83969942-a32e6700-a887-11ea-8583-0eea398c7ad0.PNG)

Any considerations would be highly appriciated.

Thanks.

**Comment by benjie** [comment]
Please see https://github.com/graphile/postgraphile/issues/427#issuecomment-293032341
