### ISSUE TITLE
Facing issue while getting the type of a table using the __type method.

### ISSUE THREAD

**Issue by navichawla92** [graphile/postgraphile#1299]
Hello, I am facing an issue while using the __type in the query to get the related data / type of the column name for a particular table it showing the null for some of the type and this is random. Like sometime it show null for UUID type column, in some it show Null for date type column and for some it show null for boolean.

https://www.awesomescreenshot.com/image/4931887/bb118122b1fd13699c742fcc5cd07362
https://tinyurl.com/y9hsa9vo

Thanks

**Comment by benjie** [comment]
Hello, this is what happens with wrapped types in GraphQL. You need to use `ofType` to expand the tree. See https://github.com/graphql/graphql-js/blob/58aaa1df30b501b67d6986ea2fc1a8b95ac9fbca/src/utilities/getIntrospectionQuery.js#L106-L137

**Comment by navichawla92** [comment]
@benjie This issue is still there as ofType is not working on the fields.

I think there must be some mis understanding. I am trying to get the type of the fields of table.

  "message": "Cannot query field \"ofType\" on type \"__Field\". Did you mean \"type\"?",
      "locations": [

Thanks

**Comment by benjie** [comment]
ofType goes inside the type selection set; see the example I linked; in particular see where that fragment is used.

**Comment by navichawla92** [comment]
@benjie Its not about the fragment. as the schema is generated auto.but when i query it from the frontend "http://localhost:8080/graphiql" to get the  fields and its name and its type for a particular table it show the error.
__type(name: "TableName") {
      name
      fields {
        name
        type {
          name
        }
      }
    }

**Comment by benjie** [comment]
```graphql
__type(name: "TableName") {
      name
      fields {
        name
        type {
          ...TypeRef
        }
      }
    }
```
