### ISSUE TITLE
contributing docs

### ISSUE THREAD

**Issue by pyramation** [graphile/postgraphile#1301]
I wanted to try and get into the code for some potential PRs, and realized the docs are not working (at least for me on the `v4` branch), maybe I'm doing something wrong?

1. from this instruction [here](https://github.com/graphile/postgraphile/blame/master/README.md#L94) I ran `yarn` and `yarn watch`... nothing happened except an error message:

```sh
$ yarn watch
yarn run v1.15.2
$ /code/sandbox/postgraphile/node_modules/.bin/watch
Usage: watch <command> [...directory] [--wait=<seconds>] [--filter=<file>] [--interval=<seconds>] [--ignoreDotFiles] [--ignoreUnreadable] [--ignoreDirectoryPattern]
✨  Done in 0.19s.
```

2. 
this line [here](https://github.com/graphile/postgraphile/blame/master/README.md#L102)
says to create a database called `graphileengine_test`. But then I ran the test and got this message:

```
 error: database "postgraphile_test" does not exist
```

## good news / questions

1. I just ignored it and was able to run tests, not sure if this is an issue or required anymore?

2. I was able to add the database, and the tests all passed. Do we need to add both databases?

**Comment by benjie** [comment]
These commands were intended to run in the context of graphile-engine rather than postgraphile. PostGraphile is really just a thin layer over engine. V5 converts to a single monorepo which helps alleviate these complex setup instructions.

**Comment by benjie** [comment]
I think you’re trying to work on the v4 branch using the v5 instructions.

**Comment by pyramation** [comment]
makes sense that it was on `master` not on `v4`... thanks for clarifying :)

**Comment by benjie** [comment]
I think this is resolved?
