### ISSUE TITLE
Smart Tags Loaded Before Schema Generation

### ISSUE THREAD

**Issue by git-blame** [graphile/postgraphile#1303]
I've been experimenting with moving all the smart comments out of postgres and into the smart tags file **postgraphile.tags.json5**.

However, on first run as cli, if postgraphile hasn't generated the graphql schema yet, none of the tables/views/etc. are available and all I get are errors of the sort `there were no matches for makePgSmartTagsPlugin rule xx` for all my rules. Of course, on subsequent (re-)starts of postgraphile it will be ok.

Is there anyway to delay the parsing of smart tags until we have a graphql schema? Otherwise, I will have to:
* Revert back to using smart comments in the DB schema
* Put in some start-up logic so that postgraphile reboots if necessary. If so, is there a way to query on command-line if postgraphile has generated the schema or not?

**Comment by benjie** [comment]
I don't think what you've said is right. Are you sure you don't have something else going on, such as some Docker workflow where the database is seeded in parallel with PostGraphile starting? Otherwise please use the issue template to file a reproduction.

**Comment by git-blame** [comment]
Yes, you are probably right that there is some race condition in Docker. Thanks.
