### ISSUE TITLE
Adding computed column via sql fragment

### ISSUE THREAD

**Issue by apjoseph** [graphile/postgraphile#1308]
I'm submitting a ... 

* [ ] bug report
* [ ] feature request
* [x] question 

PostGraphile version: 4.7.0

I'm new to postgraphile and looking to add complementary read-only geometry statistics columns for each geometry column on every table/view in schema without manually storing computed column functions for each geometry column for every table in the database. 

Trying to figure out how/if I can add a sql fragment like `st_area(geom::geography) geomAreaSqm `.  I imagine this is pretty simple, but I'm not finding any straightforward examples in the documentation.

**Comment by benjie** [comment]
There's not a super concise syntax for that yet (it's on the list), but you could build a plugin that'd do it. You could also use the `@pgQuery(fragment:...)` directive in `makeExtendSchemaPlugin` to add it field-by-field manually. I'd do it with a plugin, something like:

```js
module.exports = builder => {
  builder.hook('GraphQLObjectType:fields', (fields, build, context) => {
    const { scope: { isPgRowType, pgIntrospection: table }, fieldWithHooks } = context;
    if (!isPgRowType || !table) { return fields; }
    return extend(fields, table.attributes.reduce((newFields, attr) => {
      const fieldName = attr.name + "_thingy";
      const scope = {};

      const fieldSpecGenerator = /* relevant parts of https://github.com/graphile/graphile-engine/blob/7f0225e7bb69bbf3c135cdf1c5c155d92e916a71/packages/graphile-utils/src/makeExtendSchemaPlugin.ts#L863-L1028 */

      return build.extend(memo, {
        [fieldName]: build.pgField(
          build,
          fieldWithHooks,
          fieldName,
          fieldSpecGenerator,
          scope,
          false
        ),
      });
    }, {});
  }
}
```
