### ISSUE TITLE
Changing master to main

### ISSUE THREAD

**Issue by konnectTeer** [graphile/postgraphile#1310]
I'm submitting a ... 

* [x] bug report
* [ ] feature request
* [ ] question 

[... snipped by Benjie ...]

https://github.com/graphile/postgraphile/blob/master/src/postgraphile/pluginHook.ts

Hi,
This permalink leads to a 404 and would kindly request changing master to main. 

Thank you.

**Comment by benjie** [comment]
Hi; where did you find this link? I can't change it if I don't know where it is.

**Comment by konnectTeer** [comment]
Hi @benjie Its @jay1994tee from discord here. I stumbled on this link when you suggested i trace a conversation in help and support for ideas on an issue I had. I then decided to follow the link which led to the 404 error.

**Comment by benjie** [comment]
So the link is from chat? Was it from one of the things Graphubot said?

**Comment by konnectTeer** [comment]
Yes @benjie Its one of the links Graphubot said

**Comment by benjie** [comment]
Got it; it was the auto-response for `!server-plugins`

**Comment by benjie** [comment]
Fixed: https://discord.com/channels/489127045289476126/498852330754801666/731886861693485057
