### ISSUE TITLE
Postgres geometric support

### ISSUE THREAD

**Issue by hoopes** [graphile/postgraphile#1318]
I'm submitting a ... 

* [ ] bug report
* [x] feature request
* [ ] question 

PostGraphile version: `4.4.4`

https://www.postgresql.org/docs/9.4/datatype-geometric.html

Hi, I was wondering if it would be possible to support postgres geometric types? They are currently exposed as strings, except for `point`, which exposes an `x` and `y`.

This is specifically _not_ `postgis` support.

For box/polygon/path, it would be nice to get a list of `point` objects, and for circle, maybe an object with `center` and `radius` as attributes? I'm not gonna prescribe anything though, whatever support is added would be greatly appreciated!

Thanks!

**Comment by benjie** [comment]
Fixed in https://github.com/graphile/graphile-engine/pull/637
