### ISSUE TITLE
When installing from npm I get version 4.7.0, even though 4.8.0 was released

### ISSUE THREAD

**Issue by asafyish** [graphile/postgraphile#1326]
Like the title say, when doing an npm install postgraphile we get version 4.7.0, also on https://www.npmjs.com/package/postgraphile you can see 4.7.0 is the active version and 4.8.0 is the @next version.

Is that on purpose ? I saw 4.8.0 was released a few days ago and even the package.json file shows version 4.8.0

**Comment by benjie** [comment]
4.8.0 has not been promoted to @latest due to a reported compatibility issue with pg-many-to-many which I’ve not been able to confirm or solve yet. Will be looking into it on Friday this coming week.
