### ISSUE TITLE
error: ���� ������ "rollme" �� ����������

### ISSUE THREAD

**Issue by MaxmaxmaximusAWS** [graphile/postgraphile#1334]
```javascript
const express = require('express')
const {postgraphile} = require('postgraphile')

const app = express()

const POSTGRES_URL = process.env.POSTGRES_URL ||
  `postgres://postgres:pass@localhost:5432/rollme`

const API_GRAPHQL_PORT = process.env.API_GRAPHQL_PORT ||
  3000

app.use(
  postgraphile(POSTGRES_URL, 'public', {
    watchPg: true,
    graphiql: true,
    enhanceGraphiql: true,
  })
);

app.listen(API_GRAPHQL_PORT, () => {
  console.log(`Server listening at ${API_GRAPHQL_PORT}`)
});

```

![image](https://user-images.githubusercontent.com/69426460/90932053-917c4a80-e406-11ea-892f-1539518976a9.png)

As I understand it, it says `database not exist` but what about the encoding?

**Comment by benjie** [comment]
I suspect those are colour escape sequences that your terminal doesn't support (is it Windows, perchance?). Try running with the `FORCE_COLOR=0` envvar set; see: https://github.com/chalk/chalk#chalksupportscolor

**Comment by benjie** [comment]
(If this fixes it, feel free to raise an issue with Chalk about colour support detection, it's out of scope for PostGraphile.)

**Comment by MaxmaxmaximusAWS** [comment]
I don’t think this is beyond support, the terminal is git bash and colors are supported. Here, judging by the number of characters, it is clear that these are not colors, but just ordinary words that I wrote. I just reported an anomaly)

**Comment by MaxmaxmaximusAWS** [comment]
is Docker linux =)
