### ISSUE TITLE
Feature request: support parsing options 

### ISSUE THREAD

**Issue by cudr** [graphile/postgraphile#1340]
I'm submitting a ...

* [x] feature request

PostGraphile version: 4.7.0

I want to enable [this functionality](https://github.com/graphql/graphql-js/pull/1141) but looks like we can't currently control parser [options](https://github.com/graphql/graphql-js/blob/master/src/language/parser.js#L64)

It would be nice if postgraphile could do this

**Comment by benjie** [comment]
This was discussed in Discord; there's little point enabling parser options since it only affects parsing and not execution.

Cudr:

> Hi, @Benjie ! Is there way to enable this parser option to postgraphile?
> https://github.com/graphql/graphql-js/pull/1141

Benjie:

> Probably; but it wouldn't give you any benefit. That's literally only parsing support, it doesn't affect execution. GraphQL doesn't even know how to map operation variables to fragment variables. From the PR:
>
> > Note that this PR only supports parsing fragment variable definitions into the AST. It does not allow for passing variable values into a fragment spread.

Cudr:

> @Benjie thank you! Missed that

-- https://discord.com/channels/489127045289476126/498852330754801666/749750921260564600
