### ISSUE TITLE
Datetime not outputting ISO 8601 in makeExtendSchemaPlugin

### ISSUE THREAD

**Issue by sampok** [graphile/postgraphile#1341]
I'm submitting a ... 

* [x] bug report
* [ ] feature request
* [ ] question 

PostGraphile version: 4.8.0

Any `timestamptz` fields auto-generated by Postgraphile are output nicely as `Datetime` field in ISO 8601 format. However, if I use Postgraphile's `Datetime` in my custom `makeExtendSchemaPlugin` schema with a date object, the date is output in ECMA-262 format. I can of course define my own type, but it'd be nice to use just one (the existing) `Datetime` from client pov.

Steps to reproduce:

```javascript
const express = require("express");
const { postgraphile } = require("postgraphile");
const { makeExtendSchemaPlugin, gql } = require("graphile-utils");

const app = express();

const DateTestSchemaPlugin = makeExtendSchemaPlugin(() => {
  return {
    typeDefs: gql`
      extend type Query {
        dateTest: Datetime
      }
    `,
    resolvers: {
      Query: {
        dateTest: () => new Date(),
      },
    },
  };
});

app.use(
  postgraphile(process.env.DATABASE_URL, "public", {
    watchPg: true,
    graphiql: true,
    appendPlugins: [DateTestSchemaPlugin],
  })
);

app.listen(process.env.PORT);
```

Current behavior:

```graphql
query MyQuery {
  dateTest
}

{
  "data": {
    "dateTest": "Tue Sep 01 2020 10:25:49 GMT+0300 (Eastern European Summer Time)"
  }
}
```

Expected behavior:

```graphql
query MyQuery {
  dateTest
}

{
  "data": {
    "dateTest": "2020-09-01T07:25:49.000Z"
  }
}
```

**Comment by benjie** [comment]
There's a bug in your resolver; instead you should do:

```
        dateTest: () => new Date().toISOString(),
```

**Comment by sampok** [comment]
Thank you Benjie and sorry, I’m new to Postgraphile.

Previously (with Apollo Server) I have defined a custom scalar for Datetime which lets me directly return database objects with Date fields (timestamptz in Postgres) from resolvers as ISO date strings. So I guess my options here are either to manually covert all Dates fields to ISO strings, or define a different custom scalar (for example name it DateTime)?

**Comment by benjie** [comment]
Yes, those are two options; another would be to add a `makeWrapResolversPlugin` that wraps all resolvers returning a DateTime and does something like

```ts
const MyPlugin = makeWrapResolversPlugin(
  (context, build, field, options) => build.graphql.getNamedType(field.type).name === "Datetime" ? field : null,
  (field) => async (resolver) => {
    const d = await resolver();
    // TODO: handle case where `field` is a list.
    return d instanceof Date ? d.toISOString() : d;
  }
);
```

**Comment by sampok** [comment]
Thank you Benjie! Using ```makeWrapResolversPlugin``` works like a charm: Now I can easily reuse the existing ```Datetime``` type for all datetimes no matter whether they come from automatic Postgraphile-generated queries, or manual ```makeExtendSchemaPlugin``` resolvers!

**Comment by sampok** [comment]
The next related thing is the input type: I guess `makeWrapResolversPlugin` works only for result fields. Is there a good way for turning any `Datetime` input files into Date objects?

**Comment by benjie** [comment]
You should assume that values coming into GraphQL are JSON compatible - strings, booleans, numbers, objects, arrays - so in general I'd recommend against doing that. (And no, there's currently no argument/input object field filters since GraphQL doesn't have resolvers for inputs; also it'd break the Postgres types if Datetimes were automatically converted to Dates rather than ISO strings.)

**Comment by sampok** [comment]
Thanks Benjie! Previously with my Apollo Server and custom Datetime scalar I found it convenient and simple that all dates in resolvers were Date objects. There were no problems as `pg` module by default converts to and from JS Dates correctly, and custom scalar did the ISO string 'serialization/deserialization' of Datetime scalars both ways. But obviously it's not a big deal to remember that input dates come in as plain strings.
