### ISSUE TITLE
Order by result of calculation (with input)

### ISSUE THREAD

**Issue by stamuser60** [graphile/postgraphile#1348]
*Some context:*

My table has two columns, longitude and latitude.
I want to be able to create a query that can receive an input of a longitude, latitude and a number that represents the maximum number of kilometers distance.

The query will return the rows that are within that distance ordered by the resulting distance.

I have seen few options for custom conditions, but that might be pretty hacky...
I thought maybe there is a way to do it and use the build in `order by` that `PostGraphile` generates, but the I'm if there is a way to pass variable to the order by.

*The question:*

What is the best to do it in `PostGraphile`?

Thanks in advance!

**Comment by benjie** [comment]
To do this, step 1 is to build your filter object with your x, y and radius:

```js
const { makePluginByCombiningPlugins, makeAddPgTableConditionPlugin } = require('graphile-utils');

const PositionFilterObjectPlugin = builder => {
  builder.hook('build', build => {
    const nonNullFloat = new build.graphql.GraphQLNonNull(build.graphql.GraphQLFloat);
    const PositionFilter = new build.graphql.GraphQLInputObjectType({
      name: 'PositionFilter',
      fields: {
        x: {
          type: nonNullFloat,
        },
        y: {
          type: nonNullFloat,
        },
        radius: {
          type: nonNullFloat,
        },
      },
    });
    build.addType(PositionFilter);

    return build;
  });
};

/*
   Due to a plugin ordering issue that cannot be addressed in V4, we can't
   just use makeExtendSchemaPlugin to add this type; we have to write it
   out by hand in the build hook.

   input PositionFilter {
     x: Float!
     y: Float!
     radius: Float!
   }
*/
```

(`build.graphql` is an instance of the `graphql` module, the reference GraphQL implementation, you can read more about it [here](https://graphql.org/graphql-js/type/) and [here](https://github.com/graphql/graphql-js).)

Step 2 is to add a condition that _also_ does ordering:

```js
const PositionConditionPlugin = makeAddPgTableConditionPlugin(
  'public',
  'entities',
  'closeTo',
  build => ({
    type: build.getTypeByName('PositionFilter'),
  }),
  (value, { queryBuilder, sql, sqlTableAlias }) => {
    if (value == null) {
      return;
    }

    const { x, y, radius } = value;
    const valX = sql.value(x);
    const valY = sql.value(x);
    const valR = sql.value(radius);

    const distance = sql.fragment`(((${sqlTableAlias}.x - ${valX}) ^ 2 + (${sqlTableAlias}.y - ${valY}) ^ 2) ^ 0.5)`;

    // Order the result set by the proximity of the entity to the given point
    queryBuilder.orderBy(
      distance,
      true, // Ascending
      false,
    );

    // Filter to only entities within the given radius
    return sql.fragment`${distance} < ${valR}`;
  },
);
```

Finally you either load both these plugins or if you prefer you can make a single plugin that encompasses both:

```js
module.exports = makePluginByCombiningPlugins(PositionFilterObjectPlugin, PositionConditionPlugin);
```

I've added an example with ordering to the docs:

https://www.graphile.org/postgraphile/make-add-pg-table-condition-plugin/#example-with-ordering

NOTE: before 4.9.1 is released you'll need to add this plugin via `--prepend-plugins` because otherwise there's a plugin ordering issue that means that orders added by `makeAddPgTableConditionPlugin` come after the default orders.

**Comment by benjie** [comment]
I've also added an answer to the StackOverflow post: https://stackoverflow.com/questions/63867606/postgraphile-order-by-result-of-calculation-with-input/63904529#63904529 (yay, internet points :wink: )

**Comment by stamuser60** [comment]
Thanks a lot for the detailed answer, appreciate it!
I didn't get the chance to try it myself yet, but I wanted to ask one more thing,
maybe it becomes something else entirely,
but what if I wanted to put the result of the calculation into another column? 
Its a computed column, and from what I have red, by default you don't have order by if the column receives parameters (which it does in this case).
Will I still be able to use something similar to what you have written here?

**Comment by benjie** [comment]
You’d add the column separately.
