### ISSUE TITLE
Hope plugin hook supports async function

### ISSUE THREAD

**Issue by mywin** [graphile/postgraphile#1350]
### Feature description

Hope plugin hook supports async function

### Motivating example

    async 'postgraphile:http:handler'(incomingReq, { options, res, next }) {
        const { pgPool } = options
         // make some query

        const result = await pgPool.query(
            "SELECT ...."
          )

          // do something with result
    }

Now it is wrong to use async like this，the reason is because pluginHook function does not support await

Check the source code, the pluginHook in the requestHandler function in createPostGraphileHttpRequestHandler.js does not support await

AND
  Is it possible to support graphql.execute before and after hook function

**Comment by benjie** [comment]
Hooks are deliberately synchronous for performance reasons; however you often have the ability to perform asynchronous actions by using a hook that lets you replace an asynchronous function; for example you might be better off using the `postgraphile:middleware` hook:

```js
'postgraphile:middleware'(originalMiddleware) {
  return async function (req, res, next) {
   try {
      const { pgPool } = options;
      // make some query

      const result = await pgPool.query(
        "SELECT ...."
      );
    } finally {
      return originalMiddleware(req, res, next);
    }
  }
}
```

**Comment by mywin** [comment]
// this is ok in the new version
    'postgraphile:middleware'(middleware, { options }) {
        return Object.assign((req, res, next) => {
            //const { pgPool } = options
            // const result = await pgPool.query("SELECT ....")
            return middleware(req, res, next)
        }, middleware)
    },
