### ISSUE TITLE
New plugin hook to define Postgres pool for incoming request

### ISSUE THREAD

**Issue by JeffJankowski** [graphile/postgraphile#1352]
### Feature description

I'm looking for the ability to dynamically set the target `pg.Pool` based on the headers of the incoming request. I'm not sure if this should be a new lifecycle hook, or if it would be better to augment a currently existing one, such as `postgraphile:http:handler`. 

Another option would be to have the `pgPool` parameter accept a callback function instead of a static pool definition.

I previously accomplished this by customizing the `makeSchemaAndPlugin` function (from [postgraphile-apollo-server](https://github.com/graphile/postgraphile-apollo-server)) to accept a map of Pools and inspecting the headers in the `didResolveOperation` Apollo hook.

### Motivating example

I have a multi-tenant environment where each tenant has the same schema, but customer data is separated into distinct postgres databases. For my use case, it's more manageable to proxy to the target database at the server application level as opposed to spinning up postgraphile instances for each tenant. 

### Supporting development

- [x] am interested in building this feature myself
- [x] am interested in collaborating on building this feature
- [x] am willing to help testing this feature before it's released
- [ ] am willing to write a test-driven test suite for this feature (before it exists)
- [ ] am a [Graphile sponsor](https://www.graphile.org/sponsor/) ❤️
- [ ] have an active [support or consultancy contract](https://www.graphile.org/support/) with Graphile

**Comment by benjie** [comment]
I *think* you can do this already using the [`withPostGraphileContext` hook](https://github.com/graphile/postgraphile/blob/8c4a26cc123bd8c573ce25a27043e1110013d029/src/postgraphile/withPostGraphileContext.ts#L272); you'd wrap the existing solution with something that switches out the pgPool. Off the top of my head, the code might look something like:

```js
module.exports = {
  withPostGraphileContext(withDefaultPostGraphileContext, { options }) {
    return async (contextOptions, callback) => {
      const newContextOptions = {
        ...contextOptions,
        // Overwrite the pgPool setting with our own
        pgPool: await getPgPoolForOptions(contextOptions); // You need to implement this.
      };
      return withDefaultPostGraphileContext(newContextOptions, callback);
    }
  }
}
```

Here's the type definition for `contextOptions`:

https://github.com/graphile/postgraphile/blob/8c4a26cc123bd8c573ce25a27043e1110013d029/src/interfaces.ts#L350-L367

Please report back and let me know how it goes. If it works we should add it as an example to the docs.

**Comment by JeffJankowski** [comment]
This seems like it will work, but I need a header value from the request to determine the correct pool. It looks like I can stuff the header into the `pgSettings` function so I can access it within the hook (and they maybe remove it? probably not a big deal if I leave it), but it seems a bit "hacky."

**Comment by benjie** [comment]
That’s the way to do it; this function also handles non-HTTP requests so whatever HTTP stuff you need to do, you need to do it beforehand.
