### ISSUE TITLE
Add support for Restify framework

### ISSUE THREAD

**Issue by PaulMcMillan** [graphile/postgraphile#1354]
### Feature description

Postgraphile supports connect, express, vanilla http, and has alpha support for koa. It would be awesome to add [restify](http://restify.com/) to that list.

If it makes things less complex, our particular use case is unlikely to use websocket functionality.

### Motivating example

Restify is not as popular as frameworks like express, but it is a high performance framework that has a significant number of users. Added support would make it easier to integrate graphile with existing ecosystems that are built on restify.

### Breaking changes

N/A

### Supporting development

I [tick all that apply]:

- [ ] am interested in building this feature myself
- [ ] am interested in collaborating on building this feature
- [x] am willing to help testing this feature before it's released
- [ ] am willing to write a test-driven test suite for this feature (before it exists)
- [ ] am a [Graphile sponsor](https://www.graphile.org/sponsor/) ❤️
- [x] have an active [support or consultancy contract](https://www.graphile.org/support/) with Graphile (soon!)

**Comment by benjie** [comment]
I have this working in a PR and passing the existing test suite, but I think I might do a few more heavy edits before I merge: https://github.com/graphile/postgraphile/pull/1361

**Comment by benjie** [comment]
(The other heavy edits are now complete; and #1361 is ready to merge once we've had some :+1:'s from testers.)
