### ISSUE TITLE
Persisten query

### ISSUE THREAD

**Issue by francescovenica** [graphile/postgraphile#1357]
### Feature description

Would be nice to have a way to persist queries using hash instead of id (https://github.com/apollographql/persistgraphql).

### Motivating example

Increasing security and using hash instead of id for better scalability

**Comment by benjie** [comment]
Copied from Discord:

> Today I've written a new PostGraphile server plugin (MIT license) to give PostGraphile official support for persisted operations (a.k.a. persisted queries). As you probably know, I already recommend that every PostGraphile server that only intends first-party clients (your website, your mobile apps, etc) to talk to the API should use persisted operations. Hopefully this new plugin helps make this easier to achieve! I've not had time today to write a test suite for it, but I'd love help testing v0.0.1! https://www.npmjs.com/package/@graphile/persisted-operations
>
> If you're not sure of the what/why of persisted operations; have a read of https://www.graphile.org/postgraphile/production/.
