### ISSUE TITLE
foreign key as both enum and graphql type

### ISSUE THREAD

**Issue by wesselvdv** [graphile/postgraphile#1360]
Is it possible to define a foreign key as an enum, but still have it act as a foreign key? I am currently seeing that defining a table as an enum prevents me from using that relation in graphql.

Seems that defining something as an enum has the effect of completely removing the graphql type.

**Comment by benjie** [comment]
Rather than defining the table as an enum (which does indeed remove it from the schema), you may define one of the non-primary-key unique constraints as enum, and then reference that constraint in your foreign key references.

Please use the issue template in future :+1:
