### ISSUE TITLE
Start postgraphile with all schemas

### ISSUE THREAD

**Issue by hajiuduman** [graphile/postgraphile#1362]
### Summary
Hi, I need to start with postgraphile server from command line including all schemas (like --schema *)
Also whenever new schema added in postgres DB, postgraphile should load the new schema details automatically.
is this possible?

**Comment by benjie** [comment]
No. I don't think this is something that we want to support explicitly; e.g. presumably you wouldn't want to expose schemas such as `pg_catalog` or `information_schema`.

I suggest you run PostGraphile passing in the list of schemas, and then use the watch-mode event trigger to restart your PostGraphile instance with more schemas passed in whenever the schema list changes.
