### ISSUE TITLE
Lifecycle hooks for websocket connections

### ISSUE THREAD

**Issue by pnfcre** [graphile/postgraphile#1363]
Hi there,

### Summary

I'm interested in [something like this](https://www.apollographql.com/docs/graphql-subscriptions/lifecycle-events), but for Postgraphile. The last issue comment in #1218 mentioned creating a derivative stream, but I'm not sure how to go from there.

### Additional context

I'd love to see an abstraction or an official example for hooking into the lifecyle of a websocket connection, or just some help on how to complete the solution from #1218 with the derivative stream described in the last comment.

Thanks for the great library!

Kind regards,
Hampus Kraft.

**Comment by benjie** [comment]
You can read about our server hooks support here:

https://www.graphile.org/postgraphile/plugins/#writing-your-own-plugins

We already expose the `onOperation` hook from the websocket server here:

https://github.com/graphile/postgraphile/blob/3b01d529e7fdc79e14a0bde0bf133e963ecdc088/src/postgraphile/pluginHook.ts#L57

And you can see an example of it in use here:

https://github.com/graphile/persisted-operations/blob/ee2e404ccc5e4f7f7ffe65215a97ac5e6e0fc08e/src/index.ts#L255-L263

---

However, for your derivative stream I think you're actually after something completely separate to that. I suspect you're just not familiar with wrapping an async iterator, which goes a little something like this:

```js
async function* doSomethingWith(asyncIterator, context) {
  console.log("Subscription started");
  try {
    for await (const val of asyncIterator) {
      yield val
    }
  } finally {
    console.log("Subscription ended");
  }
}
```

**Comment by pnfcre** [comment]
Thanks!
