### ISSUE TITLE
Two @unique smart comments result in non-nullable references

### ISSUE THREAD

**Issue by felixyz** [graphile/postgraphile#1366]
### Summary

I'm using the `@unique` smart comment to create 1-to-1 relations between views. It works for *two* views - they both get a direct reference to the other (`foo` has a `bar` instead of a `barList` and likewise in the other direction).  However, when I do the very same thing for another view that `foo` references, namely `baz`, additional unwanted changes to the schema occur: both `barId` and `bazId` become non-optional in `foo`, and the only root query for `foo` is by `bazId`.

### Steps to reproduce

See the commits in this repo for a minimal case illustrating the bug:

https://github.com/felixyz/postgraphile-unique-smart-comment-bug

### Expected results

Adding one more `@unique` column constraint to a view that already has one should result in one more 1-to-many relation changing into a 1-to-1 relation. Nothing else should change.

### Actual results

A 1-to-1 relation is created, but in addition to that

* `foo.barId` and `foo.bazId` become non-optional (`Int!`)
  * The root queries for `foo` disappear
    - `foo(id: Int!) : Foo`
    - `fooByBarId(barId: Int!): Foo`
  * The only root query for `foo` is now `foo(bazId: Int!): Foo`

### Additional context

Schemas generated using

`postgraphile --connection postgres://postgraphile:xyz@localhost:5431/my_db --schema gql --watch --export-schema-graphql schema.graphql --port 5123 --enhance-graphiql --append-plugins @graphile-contrib/pg-simplify-inflector --simple-collections only --disable-default-mutations`

postgraphile 4.9.1
postgres 12 (official docker image)
OS: Pop!_OS 20.04 LTS (Ubuntu-derived)

**Comment by felixyz** [comment]
Note: I observed the same bug when running Postgraphile through the official [4.9.1 Docker image](https://hub.docker.com/layers/graphile/postgraphile/v4.9.1/images/sha256-4428bb47f331f19c84bdddf2c9ff921a552a234398b765b843e305ff30dea298?context=explore).

**Comment by benjie** [comment]
Hah; such a simple copy/paste error. Fixed in https://github.com/graphile/graphile-engine/pull/681

**Comment by felixyz** [comment]
:tada: :heart:
