### ISSUE TITLE
Cannot use the keyword'xxx_conditions' to define the table name, when there is a table called'xxx'

### ISSUE THREAD

**Issue by mywin** [graphile/postgraphile#1370]
### Summary

First create a table named'xxx', then create another table called'xxx_conditions', start postgraphile, it will report an error,
Adding condition type for table "xxx". You can rename the table's GraphQL type via a'Smart Comment':

**Comment by benjie** [comment]
Indeed, this is a naming conflict and is working as designed.

You can rename the table's GraphQL type via a 'Smart Tag' to avoid the conflict.

https://www.graphile.org/postgraphile/smart-tags/#name
