### ISSUE TITLE
Broken GraphiQL CSS For "Explorer"

### ISSUE THREAD

**Issue by machineghost** [graphile/postgraphile#1375]
### Summary

The Explorer column of a Postgraphile GraphiQL page is off-center; the left-part of the column is off the page.

![Exlporer Cropped](https://user-images.githubusercontent.com/448908/97470658-05eed080-1905-11eb-913c-0efc07c2d2d0.png)

### Steps to reproduce

1. Start a Postgraphile server (one with a decent amount of tables so your Explorer content exceeds the width).
2. View GraphiQL
3. As of ... recently (I'm not sure what I did to get this, but it must have been a recent update) the explorer column is off-center, with the left part of its content off-screen

### Expected results

You can see the whole column, as you can on any normal GraphiQL (or the old Postgraphile GraphiQL).

### Actual results

It's cropped.

### Possible Solution

This looks like a styling bug that can be fixed by changing two styles on two elements.  If you remove the `overflow:scroll` from:

    <div style="overflow: scroll; width: 100%; display: flex; flex-direction: column; min-height: 100%;">

and instead add a "min-width: fit-content;":

    <div style="/* overflow: scroll; */width: 100%;display: flex;flex-direction: column;min-height: 100%;min-width: fit-content;">

Then you modify `.historyPaneWrap` to have a "max-width: 380px" instead of a "width", and give it an "overflow:auto" ...

    <div class="historyPaneWrap" style="height: 100%;/* width: 380px; */z-index: 7;display: block;overflow: auto;max-width: 380px;">

GraphiQL looks normal: there are horizontal/vertical scrollbars in the Explorer pane, as needed, depending on the contents of the pane, but the pane never goes off the page.

**Comment by benjie** [comment]
Thanks for the issue and analysis, hopefully I can look at this before the next PostGraphile release :+1:
