### ISSUE TITLE
SELECT DISTINCT

### ISSUE THREAD

**Issue by PedroD** [graphile/postgraphile#1380]
In the sequence of this issue https://github.com/graphile/postgraphile/issues/492 which I found the conclusion below satisfactory, I wanted to ask if the following is possible:

Sometimes you want to make a `SELECT DISTINCT columnA FROM table WHERE columnB = xxx AND columnC > yyy`.
Unlike many have suggested in similar questions: No, for this type of query no normalization can save you, you really need a DISTINCT select option that allows you to select which columns you want to distinct by.

Can this be done?

Thanks.

**Comment by benjie** [comment]
Hello, yes you can achieve this with a custom query function (https://www.graphile.org/postgraphile/custom-queries/) or by adding your own query via makeExtendSchemaPlugin (https://www.graphile.org/postgraphile/make-extend-schema-plugin/). For the latter, please note that `selectGraphQLResultFromTable` accepts an SQL fragment as it's first argument, so in your case the fragment might be something like:

```js
sql.fragment`select distinct on (x, y, z) * from my_table`
```
