### ISSUE TITLE
Version 4.10 with fastify does not support cookies in pgSettings

### ISSUE THREAD

**Issue by asafyish** [graphile/postgraphile#1382]
### Summary
When creating a project using postgraphile 4.10.0-317aa40db with fastify 3.70 and fastify-cookie, the cookies are not available on the request object (request.cookie) in pgSettings.

### Steps to reproduce
Not a full repo, but I think it will still help:
Use https://github.com/graphile/postgraphile/blob/v4/examples/servers/fastify3/vanilla.ts as a starting point, add fastify-cookie, and try reading it in pgSettings - it will be undefined.

### Expected results
I expect to have the cookies available in request.cookie, they are only available in request.headers.cookie, unparsed.
Non postgraphile routes have the cookie correctly.

### Actual results
request.cookie is undefined

### Possible Solution
I guess it's because most testing is done on header authorization, but there is a strong movement to use signed cookies instead of JWT (smaller payload / more secure).
Looks like the transformation in PostGraphileResponseFastify3 is missing something.

**Comment by benjie** [comment]
Hi @asafyish thanks for the report 🙌 Please could you share the code where this worked with previous versions of PostGraphile? I didn’t know previous versions worked at all with fastify v3, and I definitely don’t want this to be a breaking change so I need to understand how it worked previously.

**Comment by asafyish** [comment]
So, I don't know if it worked with previous versions. What I previously had was using the HTTP header authorization. Thinking about it, maybe it's not actually a bug, but more of a feature-request.

**Comment by benjie** [comment]
Awesome; that's what I was hoping you'd say :raised_hands:

**Comment by benjie** [comment]
I think the solution to this is going to be something like accessing `req._fastifyRequest.cookies`; are you okay with that? I think we do something similar with Koa; it's `req._koaCtx` to get the Koa context if memory serves.

**Comment by asafyish** [comment]
Since I only need to read the cookie in pgSettings, it's a good solution.
