### ISSUE TITLE
postgraphile:http:handler hook in route handlers

### ISSUE THREAD

**Issue by domvernon** [graphile/postgraphile#1383]
### Feature description

I'd like to be able to use postgraphile:http:handler hook when using the route handlers being introduced in v4.10.0

### Motivating example

I am making use of `4.10.0-317aa40db` for the better integration with Fastify (v3) and as such have needed to convert the default handlers to Fastify ones. I am trying to make a plugin similar to [postgraphile-log-consola](https://github.com/graphile/postgraphile-log-consola) that uses [pinojs](https://github.com/pinojs/pino/) to keep it consistent with Fastify. I am using the `pluginHook` way of defining inline plugins with postgraphile as library. I tried the following code:

```
import { IncomingMessage } from 'http';
import { makePluginHook, PostGraphilePlugin } from 'postgraphile';
import logger from './logger';

interface PluginMessage extends IncomingMessage {
  startTime: [number, number];
}

let graphql;

const graphileLoggerPlugin: PostGraphilePlugin = {
  init: (_, { graphql: _graphql }) => {
    graphql = _graphql;
    return _;
  },

  'postgraphile:options': (options) => {
    return {
      ...options,
      disableQueryLog: true,
    };
  },

  'postgraphile:http:handler': (req: PluginMessage) => {
    req.startTime = process.hrtime();
    return req;
  },

  'postgraphile:http:result': (result, { queryDocumentAst, req }: { queryDocumentAst: any; req: PluginMessage }) => {
    if (queryDocumentAst) {
      const timeDiff = process.hrtime(req.startTime);

      setImmediate(() => {
        // pino logging stuff here
      });
    }
    return result;
  },
};

export default graphileLoggerPlugin;
``` 

[Discussing](https://discord.com/channels/489127045289476126/489717118154309633/774945215882199041) the problem on discord made me realise that the `postgraphile:http:handler` hook is not being run and @benjie confirmed the hook is not present in the route handlers. The reason I would like to use this is to be able to time the processing of the requests. Possible fixes suggested:

1. move the hook into each of the route handlers (and as a fallback in the middleware if no route handler matches)
2. keep that hook where it is and add separate hooks for each of the route handlers.

I am also going to try to make use of the suggestion to wrap the route handler to give it the functionality needed in the mean time.

### Supporting development

I [tick all that apply]:

- [ ] am interested in building this feature myself
- [ ] am interested in collaborating on building this feature
- [x] am willing to help testing this feature before it's released
- [ ] am willing to write a test-driven test suite for this feature (before it exists)
- [x] am a [Graphile sponsor](https://www.graphile.org/sponsor/) ❤️
- [ ] have an active [support or consultancy contract](https://www.graphile.org/support/) with Graphile

**Comment by benjie** [comment]
Thanks @domvernon :raised_hands: 

For others, I've labelled this as bug but to be clear the bug is there's no similar hook for route handlers, it's not necessarily saying that route handlers should call this specific hook as I'm currently thinking this hook is a middleware-specific hook (that was my intention for it, at least). Will attempt to address this before the release of 4.10.0

**Comment by benjie** [comment]
@domvernon this is out in postgraphile@next; could you let me know how you get on? Note it's not the `:handler` hook you want; see #1389 and release notes: https://github.com/graphile/postgraphile/releases/tag/v4.10.0-alpha.0

**Comment by domvernon** [comment]
😄 I was just in the middle of testing this! I ended up using `postgraphile:http:graphqlRouteHandler` and this has given me the behaviour I was looking for. Thanks for this!

This release must have also included some extra typings as the code wouldn't compile, so caught a bug I would have run into if an error was thrown from the fastify server - thanks for that as well.
