### ISSUE TITLE
ERR_INVALID_ARG_TYPE — internal/crypo/keys.js:322

### ISSUE THREAD

**Issue by kirkbross** [graphile/postgraphile#1398]
### Summary

Getting an ERR_INVALID_ARG_TYPE error when trying run a simple
```
postgraphile -c postgres:///mydb -a -j
postgraphile -c myusername@postgres:///mydb -a -j
```

### Steps to reproduce

npm install -g postgraphile
Try to connect to any db
I do get `PostGraphile v4.9.2 server listening on port 5000` and the bullet list ending in "Join Chad Furman..." but then it crashes on `internal/crypto/keys.js:322`

### Expected results
For postgraphile to launch and listen with no errors.

### Actual results
TypeError [ERR_INVALID_ARG_TYPE]: The "key" argument must be of type string or an instance of Buffer, TypedArray, DataView, or KeyObject. Received null

### Possible Solution
Do it right? i.e. I'm going about it. I'm trying to connect to a local postgres db with 
`postgraphile -c postgres:///mydb -s public -a -j`

**Comment by benjie** [comment]
Hi @kirkbross did you work out what happened?

**Comment by LetTheComputerDecide** [comment]
I am also experiencing this behavior. Windows, node v14.11.0

**Comment by benjie** [comment]
@LetTheComputerDecide What's your connection string?

**Comment by LetTheComputerDecide** [comment]
@benjie I was following https://www.graphile.org/postgraphile/usage-cli/ and as such my connection string was in the form of "**postgres:///mydb**". It didn't work and I tried few variations on that form.

Meanwhile, I've noticed different form used on the postgraphile's landing page (**postgres://pg_user:pg_pass@pg_host:pg_port/pg_db**) and this worked for me.

**Comment by benjie** [comment]
`postgres:///mydb` means "connect to the database called `mydb` on the default host and port using the default username and password. It works with locally installed PostgreSQL using trust auth on Mac, but I think it has issues on other platforms that I wasn't aware of when I wrote it. Unfortunately there doesn't seem to be a universal solution to this.

**Comment by LetTheComputerDecide** [comment]
For the record, I was connecting to the database on my localhost running on default pg port, with default postgres user.

Maybe the documentation and/or error message could be improved for future users?

**Comment by benjie** [comment]
> Maybe the documentation and/or error message could be improved for future users?

Suggestions welcome :+1:
