### ISSUE TITLE
docker tag latest refer to a stable release?

### ISSUE THREAD

**Issue by haakondr** [graphile/postgraphile#1406]
We had our environment configured to use the latest tag by mistake. 

Suddenly our test environment broke down as we started using graphile/postgraphile:v4.11.0-alpha.0. The container crashed with the following error message:

```
graphql_1            | /postgraphile/build-turbo/postgraphile/http/subscriptions.js:45
graphql_1            |     if (!options.websockets?.length) {
graphql_1            |                             ^
graphql_1            | 
graphql_1            | SyntaxError: Unexpected token '.'
graphql_1            |     at wrapSafe (internal/modules/cjs/loader.js:915:16)
graphql_1            |     at Module._compile (internal/modules/cjs/loader.js:963:27)
graphql_1            |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
graphql_1            |     at Module.load (internal/modules/cjs/loader.js:863:32)
graphql_1            |     at Function.Module._load (internal/modules/cjs/loader.js:708:14)
graphql_1            |     at Module.require (internal/modules/cjs/loader.js:887:19)
graphql_1            |     at require (internal/modules/cjs/helpers.js:74:18)
graphql_1            |     at Object.<anonymous> (/postgraphile/build-turbo/postgraphile/http/createPostGraphileHttpRequestHandler.js:37:25)
graphql_1            |     at Module._compile (internal/modules/cjs/loader.js:999:30)
graphql_1            |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
```

 The container crashing on a alpha release is not a problem, but I think the latest tag should refer to a stable release.

**Comment by benjie** [comment]
a) yes it should be stable; I've currently misconfigured the Docker build sorry about that.
b) thanks for noting the optional chaining/GRAPHILE_TURBO issue, we'll have to turn off GRAPHILE_TURBO on Docker as I think upgrading to Node v14 might in itself be a breaking change.

**Comment by keithlayne** [comment]
This commit: https://github.com/graphile/postgraphile/commit/c04d6703c602bd0b023dc083f0741779b713fbd0#diff-8512ecc0fdf2e0d9e9c0c0229681a7838a420c3585866333c7bdb67bf372b48c

appears to have introduced some optional chaining. When compiled with a TS target of less than `es2020` (or maybe `esnext`, can't remember), these will not be transformed. 

The "turbo" build targets esnext: https://github.com/graphile/postgraphile/blame/8a0c6a8a68797f94f58eda48dc20f03405ebe000/scripts/build#L16

The dockerfile sets turbo mode: https://github.com/graphile/postgraphile/blame/v4/Dockerfile#L47 but uses node 12, and IIRC no versions of node 12 support optional chaining in v8.

My understanding was that turbo generally didn't require that much, so esnext is probably not the best target there.

**Comment by keithlayne** [comment]
Oops.  Too slow 😄

**Comment by benjie** [comment]
Ref #1407

**Comment by benjie** [comment]
Turbo always targets the latest LTS release of Node; it's a moving target.

**Comment by benjie** [comment]
I've changed our main branch to be `main` rather than `v4`; will only merge to `v4` on stable releases. Merges to `v4` go out on Docker Hub automatically.
