### ISSUE TITLE
Who to handle binary data (like images)?

### ISSUE THREAD

**Issue by guettli** [graphile/postgraphile#1410]
Who to handle binary data (like images)?

I am evaluating if I need Django+DRF for my next project, or if postgraphile would be enough.

I could not find any documentation about the support of binary data in your docs.

**Comment by benjie** [comment]
I don't believe that GraphQL is a good fit for binary data; I recommend you use a separate API for that and that you ignore the links below.

That said, if you really want to:

- Here's a plugin for BYTEA support which may or may not suit your needs depending on what size of binary we're talking about: https://github.com/graphile/postgraphile/issues/1035#issuecomment-479574071
- Discussion about file uploads: https://github.com/graphile/postgraphile/issues/523
- Example of file uploads with PostGraphile: https://github.com/graphile-contrib/postgraphile-upload-example
