### ISSUE TITLE
Postgraphile capability to intercept in development headers/request/responses

### ISSUE THREAD

**Issue by ruslanrusu** [graphile/postgraphile#1412]
Hi here,

I'm using postgraphile for while and I'm impressed how easy to use and productive i feel.

Though once in a while will have to deal with 3rd party clients for the service onboarding process.
In this situation it is mostly helping them with either bad queries or misconfigured clients.

I tried to see if posgraphile allows to enable debug mode where I can print all http headers,
request body, response body. Unfortunately could not find anything. 

Things I tried:
a) register a middleware in express before use(postgraphile) to intercept request/response.  
Did not help. Captures the request but no response body. Tried to register after and then 
does not get invoked at all. 
b) looked into plugins but none of them seemed obvious how to reach request, response
and intercept them

The only option i can think of is to use a proxy and front the traffic through. I suspect I'm 
missing something obvious. Is the proxy my only option ?

Happy to make a sample if that helps

Appreciate your help,
Ruslan

**Comment by benjie** [comment]
Using approach a) you could monkey-patch `res.end`; but a proxy would also work :+1:
