### ISSUE TITLE
Checking if body-parser was used before postgraphile library

### ISSUE THREAD

**Issue by WhoAteDaCake** [graphile/postgraphile#1413]
Hi, thank you for an amazing package. It's normally really straight forward to use, however, this time I've spent around 3 hours trying to integrate it with next.js, to only realise, that the reason requests would hang forever was due to next.js enabling `body-parser` by default.
I'm not sure if it's a bug with `body-parser` package, but it would just hang forever. Afterwards, I've added

```javascript
export const config = {
  api: {
    externalResolver: true,
    bodyParser: false,
  },
};
```

To my code and it worked fine. So I guess my question is: can we catch this sort of scenario? For example checking if body was already parsed, etc. Again, thank you so much for all the work you've put in

P.S: after checking the code, the culprit was `bodyParser.json({ limit: options.bodySizeLimit })` line within `createPostGraphileHttpRequestHandler.ts`

**Comment by benjie** [comment]
`body-parser` already handles this as it sets `req._body` when parsed:

https://github.com/expressjs/body-parser/blob/480b1cfe29af19c070f4ae96e0d598c099f42a12/lib/types/json.js#L99-L103

Perhaps `next` is using a different body parser and is not setting this? You should be able to set it in your middleware or whatever next uses; in express it'd be something like `(req, res, next) => {req._body = true; next()}`

**Comment by benjie** [comment]
I'd advise sending a PR to Next that sets `req._body = true` for compatibility with the `body-parser` module.

**Comment by WhoAteDaCake** [comment]
Thanks!
