### ISSUE TITLE
AllowExplain exiting postgraphile run as library

### ISSUE THREAD

**Issue by pszafer** [graphile/postgraphile#1420]
### Summary

if allowExplain is enabled and explain is enabled in graphiql website then postgraphile error with exit 1.

### Steps to reproduce

Create database as:
```
drop schema if exists app_public CASCADE;
drop role IF EXISTS app_role;
create role app_role;
create schema if not exists app_public;
CREATE EXTENSION IF NOT EXISTS citext WITH SCHEMA app_public;
GRANT usage ON SCHEMA app_public TO app_role;
ALTER DEFAULT privileges REVOKE EXECUTE ON functions FROM public;
REVOKE ALL ON DATABASE app_public FROM PUBLIC;
REVOKE ALL ON SCHEMA public FROM PUBLIC;

create table if not exists app_public.foo (
 id serial primary key,
 title text not null
);

GRANT SELECT ON TABLE app_public.foo TO app_role;

insert into app_public.foo (title) values ('one'), ('two'), ('three');
create or replace function app_public.foo_test_ha (o app_public.foo) RETURNS text AS $$ SELECT 'text' $$ LANGUAGE sql STABLE;
```

create postgraphile as library as:
```
import express from "express";
import { postgraphile } from "postgraphile";
const postgraphileOptions = {
  pgSettings: () => ({ role: "app_role" }),
  graphiql: true,
  enhanceGraphiql: true,
  allowExplain: true
}
const postgraphileMiddleware = postgraphile("postgres://postgres:postgres@localhost/app_public", "app_public", postgraphileOptions)
const app = express();
app.use(postgraphileMiddleware);
app.listen(port, () => {
  console.log(`Pricing service listening on http://localhost:${port}/graphiql`);
});
```

Run db.
Run `yarn server`

Run query with explain disabled:
```
query MyQuery {
  allFoos {
    nodes {
      title
      testHa
    }
  }
}
```

now turn on explain and postgraphile will crash.

### Expected results

Same as with explain disabled - message with permission denied.

### Additional context

Postgresql postgres:13-alpine
Postgraphile: "postgraphile": "^4.10.0"
Yarn: v1.22.10
node: v15.4.0

**Comment by benjie** [comment]
I attempted to reproduce this issue following your instructions here: https://github.com/benjie/issue1420-reproduction-attempt

I failed to reproduce it.

Please can you share the actual error messages you're getting, they may well give a clue as to what is going wrong.

**Comment by pszafer** [comment]
Change postgraphile options to
```
const postgraphileOptions = {
  pgSettings: (req) => {
    const settings = {};
    settings["role"] = "app_role"
    settings["user.sub"] = "123123123213123"
    settings["user.firstname"] = "123123123213123"
    settings["user.lastname"] = "123123123213123"
    return settings;
  },
  graphiql: true,
  enhanceGraphiql: true,
  allowExplain: true
}
```

I end up with error:

```
yarn run v1.22.10
$ node -r esm index.js
error: permission denied for function foo_test_ha
    at Parser.parseErrorMessage ($HOME/postgraphile_demoerror/server/node_modules/pg-protocol/dist/parser.js:278:15)
    at Parser.handlePacket ($HOME/postgraphile_demoerror/server/node_modules/pg-protocol/dist/parser.js:126:29)
    at Parser.parse ($HOME/postgraphile_demoerror/server/node_modules/pg-protocol/dist/parser.js:39:38)
    at Socket.<anonymous> ($HOME/postgraphile_demoerror/server/node_modules/pg-protocol/dist/index.js:10:42)
    at Socket.emit (node:events:379:20)
    at Socket.EventEmitter.emit (node:domain:470:12)
    at addChunk (node:internal/streams/readable:313:12)
    at readableAddChunk (node:internal/streams/readable:288:9)
    at Socket.Readable.push (node:internal/streams/readable:227:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
  length: 102,
  severity: 'ERROR',
  code: '42501',
  detail: undefined,
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'aclchk.c',
  line: '3461',
  routine: 'aclcheck_error'
}
```

if you want I can 
```

**Comment by benjie** [comment]
I get the error (as expected), but no crash with/without explain.

![Screenshot_20210120_153849](https://user-images.githubusercontent.com/129910/105198466-99672480-5b35-11eb-8a4a-73ab45be1a96.png)

![Screenshot_20210120_153908](https://user-images.githubusercontent.com/129910/105198536-a71caa00-5b35-11eb-8747-498fefe883bb.png)

**Comment by pszafer** [comment]
if you can't reproduce maybe there is something with Arch Node or npm or yarn or with esm. Don't know. I don't need it so I think we can close. maybe in the future something come up.

![image](https://user-images.githubusercontent.com/690510/105200546-3f1f9100-5b40-11eb-957c-cb6524573271.png)

![image](https://user-images.githubusercontent.com/690510/105200669-624a4080-5b40-11eb-97c8-7e4ab1963962.png)

![image](https://user-images.githubusercontent.com/690510/105200717-6e360280-5b40-11eb-92cf-41af64194255.png)

**Comment by benjie** [comment]
I’ve not tried with esm but not sure why that would make a runtime rather than require-time difference.
