### ISSUE TITLE
UUIDs and GRANT USAGE issue

### ISSUE THREAD

**Issue by gevera** [graphile/postgraphile#1421]
Hi there. I am following the official Postgraphile forum example, however, instead of regular integer serial primary key for ids, I am using UUID. 

Now when it comes to granting usage,
`grant usage on sequence forum_example.post_id_seq to forum_example_person;`
obviously, this won't work since UUID doesn't create a sequence. How then one should proceed with granting usage without switching back to regular incremental ids?

Thank you

Btw, loving Postgraphile, very powerful yet minimalist tool.
Merry Christmas and Happy New year, Benjie

**Comment by benjie** [comment]
You simply don’t need that statement at all with UUIDs. Thanks and happy holidays!
