### ISSUE TITLE
Get input type of table that uses psql schema which is not specified in a postgraphile instance

### ISSUE THREAD

**Issue by shavlakmax** [graphile/postgraphile#1426]
### Question

 Is it possible to get a table input type in a `makeExtendSchemaPlugin` of table that uses private psql schema?
 
The thing is that I have two instances of postgraphile. One is for `public` requests (public psql schema), and the second one handles `admin` requests (admin psql schema). The user table is in `admin` schema. However, I want to create some wrapper mutation that will handle the request from public side and give it to the admin one. And that mutation should take the input type of a user. 

For the admin instance, I have a basic mutation which looks something like this:
`createUser(input: CreateUserInput): CreateUserPayload`

I want to get that `CreateUserInput` type somehow. Since the table is not in public psql schema I won't have it outside of the box. It will be great if a query build object has some method for creating such input types specifying a table fragment. 

```
makeExtendSchemaPlugin({
    typeDefs: gql`
      extend type Mutation {
        createUser(
          input: CreateUserInput! # do magic here and get input type of a user table which was not created by default since uses another schema
        ): User
      }
    `,
    resolvers: {
       Mutation: {
         createUser: () => {
              // do stuff here
         }
       }
    },
  })
```

Of course I can just type the fields manually. however, it would be really great to have it done automatically.

**Comment by benjie** [comment]
You'd use `build.pgGetGqlInputTypeByTypeIdAndModifier` to force the type to be generated; something like

```js
const table = build.pgIntrospectionResultsByKind.class.find(kls => kls.namespaceName === "admin" && kls.name === "user");
const GraphQLTableInputType = pgGetGqlInputTypeByTypeIdAndModifier(table.id, null /* or "patch" or "base" */);
```

However [it's possible that makeExtendSchemaPlugin runs too early for this to work](https://discord.com/channels/489127045289476126/489717118154309633/545578229696823296).
