### ISSUE TITLE
setofFunctionsContainNulls: false does not apply to scalar types

### ISSUE THREAD

**Issue by eddiew** [graphile/postgraphile#1427]
### Summary

using `setofFunctionsContainNulls: false`:
a function defined with `returns setof text` yields the return type `[String]`

### Expected results

the return type should be `[String!]`

If this behavior is intentional, how would I change it with a plugin?

Edit: I thought this applied only to custom scalar types but turns out it's all scalar types

**Comment by benjie** [comment]
This is as designed/intended, but yes the name is misleading. `setofCompositeTypeReturningFunctionsMayContainNull` is a bit of a mouthful though :wink: 

A gist you wrote on how to make simple collections non-nullable: https://gist.github.com/eddiew/d96cfaa7724cc4aea7f167afd22f586b
