### ISSUE TITLE
Saving the GraphQL query results as view or materialized view in Postgres

### ISSUE THREAD

**Issue by KrishnaPG** [graphile/postgraphile#1436]
From the documentation it is clear that GraphQL query can read from an existing view from the postgres.

Can it also be made possible to create new views from the results of GraphQL queries? This helps in creating data subsets that can later be used in further GraphQL queries, which is specifically useful when the initial queries results in large subsets.

**Comment by benjie** [comment]
You could potentially do this with some kind of plugin but it’s way outside the scope of the project itself.
