### ISSUE TITLE
Treat raise warning as raise exception

### ISSUE THREAD

**Issue by Tam** [graphile/postgraphile#1457]
I'm currently using `raise exception` to bail out of a function early and show an error to the client. However, this means anything done up to that point in the function is rolled back. This is annoying in cases where I want to modify the database before throwing the exception (i.e. incrementing a failed login count).

Is it possible to treat `raise warning '...'; return null;` as an exception? This would allow me to bail out and notify without rolling back the transaction.

I've tried wrapping the logic I want to not be rolled back in `begin ... end;` but this doesn't seem to work in all cases.

**Comment by benjie** [comment]
You can probably achieve this with makeWrapResolversPlugin by adding an event listener to context.pgClient for the relevant event (see node-postgres docs); just be sure to wrap it in try/finally and in the finally block ensure you remove the event listener.

**Comment by Tam** [comment]
@benjie Thanks for getting back to me so quick!

After a bit of tinkering, I've managed to come up with this:

```js
const { makeWrapResolversPlugin } = require('graphile-utils')
    , { GraphQLError } = require('graphql');

module.exports = makeWrapResolversPlugin(
    context => context.scope.isRootMutation || null,
    () => async (resolve, source, args, context) => {
        const hasWarning = { warning: null };

        context.pgClient.on('notice', n => {
            if (n.severity === 'WARNING') {
                hasWarning.warning = n;
            }
        });

        const res = await resolve();

        if (hasWarning.warning)
            throw new GraphQLError(hasWarning.warning.message);

        return res;
    }
);
```

Seems to work fine, although I'm not sure how to remove the event listener, since there doesn't seem to be a way documented in their docs.

**Comment by benjie** [comment]
It’s an event listener so context.pgClient.removeListener(...) - see the Node.js “events” docs

**Comment by Tam** [comment]
Tweaked to remove the event listener (thanks for the tip!):

```js
const { makeWrapResolversPlugin } = require('graphile-utils')
    , { GraphQLError } = require('graphql');

module.exports = makeWrapResolversPlugin(
    context => context.scope.isRootMutation || null,
    () => async (resolve, source, args, context) => {
        const hasWarning = { warning: null };
        const onNotice = n => n.severity === 'WARNING' && (hasWarning.warning = n);

        try {
            context.pgClient.on('notice', onNotice);

            const res = await resolve();

            if (hasWarning.warning)
                throw new GraphQLError(hasWarning.warning.message);

            return res;
        } catch (e) {
            throw e;
        } finally {
            context.pgClient.off('notice', onNotice);
        }
});
```
