### ISSUE TITLE
Query Interceptors

### ISSUE THREAD

**Issue by ldadams** [graphile/postgraphile#1462]
### Summary

Looking for advice.  

I have a custom query that's implemented as a SQL function - works great!  What I need to do now is convert the output of that function to a CSV file.  I need to increase the pagesize or paginate through results to build the file via some sort of interceptor or...

I was looking for recommendations on if this is possible via a plugin / hook.  I figure I can create a new custom graphql or rest endpoint that calls the API (itself for this) but wanted to see if there was a creative way to intercept these calls or use the generated stubs directly in Node.  Thx!

**Comment by ldadams** [comment]
Or Maybe this should be done in Fastly adding a new content type handler.

**Comment by benjie** [comment]
That does sound like a concern outside of PostGraphile (though you could always return CSV from a GraphQL resolver, it may or may not make sense to do so).

Something like this should do the trick:

```js
const { Pool } = require('pg');
const { parse } = require('json2csv');

async function main() {
  const pool = new Pool({ connectionString: "postgres:///" });
  try {
    const { rows, fields } = await pool.query('select * from my_function($1, $2)', [
      42,
      "thanks for all the fish"
    ]);
    const csv = parse(rows, { fields: fields.map(f => f.name) });
    console.log(csv);
  } finally {
    pool.end();
  }
}

main();
```
