### ISSUE TITLE
makeProcessSchemaPlugin and @graphql-tools/merge

### ISSUE THREAD

**Issue by guillaumervls** [graphile/postgraphile#1463]
Hi and thanks for the good work on Postgraphile,

The following plugin (which should do nothing) seems to break connection fields (it looks like it works on single items). I'm not familiar enough with the low-level GraphQL implementations, so I ask here if that's something someone struggled with before ?

```js
import { mergeSchemas } from "@graphql-tools/merge";

const plugin = makeProcessSchemaPlugin((schema) =>
  mergeSchemas({
    schemas: [schema],
  })
);
```

Cheers

**Comment by benjie** [comment]
PostGraphile's schema is built as a cohesive whole. Tools that mutate the schema or take parts of it apart and put them into other schemas may fall foul of this assumption, causing issues. Generally it's best to treat PostGraphile's schema as a "remote schema" and not manipulate it directly, instead delegating to it via some other mutable schema.

**Comment by yevgenypats** [comment]
If this is not supported I would suggested then changing or also adding this note in the documentation (https://www.graphile.org/postgraphile/make-process-schema-plugin/) as in the documentation it's written that  `makeProcessSchemaPlugin` can be used for schema merging. specifically I tried the same snippet and it doesn't work as well.

**Comment by benjie** [comment]
Note added: https://github.com/graphile/graphile.github.io/commit/24c4588e0dc335fafe511718a2551bb77af02212#diff-6043010738267d094ed9251cd1a420c6784e29b6fae57e772b779a81a1684056
