### ISSUE TITLE
[Question] Integration with nestjs (@nestjs/graphql)

### ISSUE THREAD

**Issue by mubaidr** [graphile/postgraphile#1474]
### Summary

How to integrate `Graphile` server with the `NestJS` application for single `Grapghql` endpoint. 

### Additional context

So far I am able to integrate Postgraphile into the NestJS application, and I have a running Graphql endpoint and NestJS server endpoints. 

**Setup**
- Setup NestJS application
- Add Graphile server (using middle-ware option)
- Add `@nestjs/graphql` package
- Create custom endpoints in NestJS

**Question:** 
Is it possible that somehow I could merge `@nestjs/graphql` generated `schema.graphql` to graphile server to generate crud for these schema too? 

**Benefit**
This way I would have benefit of defining custom endpoints using awesome `NestJs` syntax and excellent performance/crud functionality of `Postgraphile`.

Please note that `NestJs` can generate schema of type `const schema: GraphQLSchema` for defined routes/resolvers. 

```ts
export class GraphQLSchema {
  description: Maybe<string>;
  extensions: Maybe<Readonly<GraphQLSchemaExtensions>>;
  astNode: Maybe<SchemaDefinitionNode>;
  extensionASTNodes: Maybe<ReadonlyArray<SchemaExtensionNode>>;

  constructor(config: Readonly<GraphQLSchemaConfig>);
  getQueryType(): Maybe<GraphQLObjectType>;
  getMutationType(): Maybe<GraphQLObjectType>;
  getSubscriptionType(): Maybe<GraphQLObjectType>;
  getTypeMap(): TypeMap;
  getType(name: string): Maybe<GraphQLNamedType>;

  getPossibleTypes(
    abstractType: GraphQLAbstractType,
  ): ReadonlyArray<GraphQLObjectType>;

  getImplementations(
    interfaceType: GraphQLInterfaceType,
  ): InterfaceImplementations;

  // @deprecated: use isSubType instead - will be removed in v16.
  isPossibleType(
    abstractType: GraphQLAbstractType,
    possibleType: GraphQLObjectType,
  ): boolean;

  isSubType(
    abstractType: GraphQLAbstractType,
    maybeSubType: GraphQLNamedType,
  ): boolean;

  getDirectives(): ReadonlyArray<GraphQLDirective>;
  getDirective(name: string): Maybe<GraphQLDirective>;

  toConfig(): GraphQLSchemaConfig & {
    types: Array<GraphQLNamedType>;
    directives: Array<GraphQLDirective>;
    extensions: Maybe<Readonly<GraphQLSchemaExtensions>>;
    extensionASTNodes: ReadonlyArray<SchemaExtensionNode>;
    assumeValid: boolean;
  };
}
```

I am using latest NestJS and Postgraphile.

**Comment by mubaidr** [comment]
I have also noticed another issue. It looks like `postgraphile` is totally controlling the endpoint route. This means if I define some other handler (`get` or `post`) to same endpoint `/graphql` it fails to hit and `postgraphile` returns not found error.

**Comment by benjie** [comment]
Other handlers need to come before PostGraphile

**Comment by mubaidr** [comment]
This is not possible with `nestjs` framework 😞 Having an option to be set `graphile` as pass through handler would be suitable. 

Options: 
- Create an instance of `fastify`, add `graphile`, then pass it to `nestjs`
But this over rides the later routes as you said. 
- Try to add `graphile` routes after `nestjs` boots, simply cannot. 
Because we cannot add routes to `fastify` after initialization.

**Comment by mubaidr** [comment]
Definig a new `nestjs` module and setting up graphile inside that partially solves the issue.

**Comment by Mingyang-Li** [comment]
Hey @mubaidr, did you manage to integrate postgraphile into your NestJS API? If so, I'd like to see how you structured your project - reply to this comment with project URL if you're happy to
