### ISSUE TITLE
"yarn run build" fails on Windows

### ISSUE THREAD

**Issue by Venryx** [graphile/postgraphile#1477]
### Summary

Running the `yarn run build` script fails on Windows.

### Steps to reproduce

1) Download the postgraphile repo, on Windows.
2) Open a terminal in the repo root.
3) Run `yarn`, to install the dependencies. (not actually necessary to demonstrate this issue, but might as well)
4) Run: `yarn run build`

### Expected results

I expect to see a success message in the terminal, and the outputted files in the `build-turbo` folder.

### Actual results

```
PS C:\Root\Apps\@V\@Modules\postgraphile\Fork> yarn run build
yarn run v1.22.10
$ ./scripts/build
'.\scripts\build' is not recognized as an internal or external command,
operable program or batch file.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Same thing for NPM:
```
PS C:\Root\Apps\@V\@Modules\postgraphile\Fork> npm run build

> postgraphile@4.12.0-alpha.0 build C:\Root\Apps\@V\@Modules\postgraphile\Fork
> ./scripts/build

'.' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE [...]
```

I also tried renaming the scripts to end with `.bat` and running them in cmd/powershell, but that (as expected) fails as well. (many errors, due to linux commands like `rm` not being present)

### Additional context

OS: Windows 10
Node: v14.5.0

### Possible Solution

Switch from using bash scripts to NodeJS scripts, or some other cross-platform scripting solution (eg. based on [shx](https://github.com/shelljs/shx) or [shelljs](https://github.com/shelljs/shelljs)).

**Comment by benjie** [comment]
I’m afraid we don’t have the resources (and I don’t have the knowledge) to support contributing to PostGraphile on native Windows; please use a Linux VM or Docker or WSL or similar.

(For anyone reading out of context: you can run PostGraphile on Windows just fine, it’s the development scripts if you want to contribute to PostGraphile that are unix-specific.)

**Comment by Venryx** [comment]
I figured that might be the case...

Anyway, this issue should help clarify that point at least, for others searching with the same question. 👍

**Comment by benjie** [comment]
Thanks so much ❤️

**Comment by Venryx** [comment]
I'll eventually look into using WSS for a "proper" build setup.

However, for people merely wanting a basic Typescript build command, I got it working on Windows.

Step 1: Create a `build.js` file in the `scripts` folder:
```
const {execSync} = require("child_process");
const fs = require("fs");

// create assets (some empty/fake) in the src/assets folder (to fix typescript errors)
fs.mkdirSync("./src/assets", {recursive: true});
//fs.copyFileSync("./assets/favicon.ico", "./src/assets/favicon.ico");
fs.writeFileSync("./src/assets/favicon.ico", "");
fs.writeFileSync("./src/assets/graphiql.html", "");

// this helper file tells Typescript to interpret the asset files as string-returning modules (else TS complains about their being imported)
//if (!fs.existsSync("./src/assets/assetsTSHelper.d.ts")) {
fs.writeFileSync("./src/assets/assetsTSHelper.d.ts", `
	declare module '*.ico' {
		const str: string;
		export default str;
	}
	declare module '*.html' {
		const str: string;
		export default str;
	}
`);

// the default is "build-turbo", but I use "build", to match with the npm-published postgraphile package (for npm-link)
//const buildFolder = "build-turbo";
const buildFolder = "build";

execSync(`.\\node_modules\\.bin\\tsc --target esnext --lib esnext --outDir ${buildFolder} --declarationDir ${buildFolder}`, {stdio: "inherit"});

// copy assets to build folder (else runtime-import error is hit)
fs.mkdirSync("./build/assets", {recursive: true});
const assetNames = ["favicon.ico", "graphiql.html"];
for (const assetName of assetNames) {
	fs.copyFileSync(`./src/assets/${assetName}`, `./build/assets/${assetName}`);
}
```

Step 2: For easier running from VSCode, you can create a `.vscode/launch.json` file:
```
{
	"version": "2.0.0",
	"tasks": [
		{
			"label": "node: build (windows)",
			"type": "shell",
			"command": "node",
			"args": [
				".\\scripts\\build.js"
			],
			"group": "build",
			"problemMatcher": []
		}
	]
}
```

Step 3: Run the build script, either with `node .\scripts\build.js`, or ctrl+shift+b in vscode.

Like I said, this solution is not ideal (eg. it uses empty placeholder files for the assets), but for simply testing changes to the code, it works fine.
