### ISSUE TITLE
Unable to access Datetime built-in

### ISSUE THREAD

**Issue by yogiduzit** [graphile/postgraphile#1478]
### Summary

Hi,

I am trying to implement a date range filter on an entity using `makeAddPgTableConditionPlugin`. 
The condition will take an object with non-nullable fields `startDate` and `endDate`. Using the `Datetime` built-in to define the type seems the best way, but I am not sure how to access the type.

This is what I am trying to do:
```
import { Datetime } from "postgraphile"
```
```
(build) => {
    const { GraphQLObjectType, GraphQLNonNull, GraphQLScalarType } = build.graphql;
    return {
      description: "Filters orders created within a time range",
      type: new GraphQLObjectType({
        startDate: new GraphQLNonNull(Datetime),
        endDate: new GraphQLNonNull(Datetime)
      })
    };
  }
```

### Additional context

None

Thanks a lot for building and maintaining this awesome and highly customizable GraphQL API. 🙌🏽

**Comment by benjie** [comment]
First thing to try is `const Datetime = build.getTypeByName('Datetime')`; if that doesn't work there's another way :+1:

**Comment by yogiduzit** [comment]
> First thing to try is `const Datetime = build.getTypeByName('Datetime')`; if that doesn't work there's another way 👍

It worked!
Thanks a lot for the prompt reply, Benjie. Closing this issue now.
