### ISSUE TITLE
`ShutdownActions` required in `WithPostGraphileContextOptions`

### ISSUE THREAD

**Issue by ben-pr-p** [graphile/postgraphile#1491]
### Summary

As of https://github.com/graphile/postgraphile/commit/818dad61a4d44d6a9aebdd8901ba58d104e1f562#diff-2ee8da4ec0f3c043c7e097851af07383ae3ce13022973c8727312e06bf2b89b3R391, `shutdownActions: ShutdownActions` is required in `WithPostGraphileContextOptions`, the type of the parameter passed to, for example:
```
await withPostGraphileContext(
    {
      ...options,
      pgPool,
      pgSettings,
      // BUG - shutdownActions should be not be required
      shutdownActions: new ShutdownActions(),
    },
    async (context) => {
      return await graphql(
        schema,
        query.loc.source,
        null,
        {
          ...context,
        },
        variables
      );
    }
```

ShutdownActions should *not* be required here since no continual loop is starting, and there's no way to call them via `middleware.release()`. 

### Steps to reproduce

Upgrade to Postgraphile 4.12.1, and use `withPostgraphileContext` without providing `shutdownActions`

### Expected results

Pre 4.12.1 behavior - the other options are enough to pass.

### Possible Solution

I'm not 100% where the place to put this would be, but likely this property should be optional (`shutdownActions?`) and some code should handle that and initialize it to a default.

## Temporary Fix

For anyone who comes across this issue, manually supplying a default `ShutdownActions` like in the example above is a temporary fix.

**Comment by benjie** [comment]
Fixed in 4.12.2 by removing that definition.
