### ISSUE TITLE
Use special domains to allow functions to return enums defined via enum tables

### ISSUE THREAD

**Issue by ben-pr-p** [graphile/postgraphile#1500]
### Feature description

Right now, you can [define enums with enum tables](https://www.graphile.org/postgraphile/enums/#with-enum-tables), which have a number of benefits versus native PostgreSQL enums. 

However, one drawback of enum tables vs native PostgreSQL enums is that you can't return them from functions.

```sql
create table stage_options (
  type text primary key
);

insert into stage_options (type) values ('pending', 'round 1', 'round 2', 'rejected', 'hired');

create table applicants (
  id uuid,
  first_name text,
  last_name text,
  stage text references stage_options (type)
);

create or replace next_stage_options(a applicants) returns text -- no way to make this return stage_options instead of text
as $$
  -- some function definition
$$ language sql;
```

In Discord, Benjie and I discussed using a domain to tell Postgraphile to re-use the enum type:
```sql
create domain stage_options_enum_domain as text;

create or replace next_stage_options(a applicants) returns stage_options_enum_domain
as $$
  -- some function definition
$$ language sql;
```

And linking the domain to the table either
- by naming convention `<enum table name>_enum_domain`
- or by smart comment:
```
comment on domain stage_options_enum_domain is E'@enum stage_options';
```

### Breaking changes

I suppose this could be a breaking change for anyone who:
- is using an enum table
- has a domain that matches the naming specification
- has a function that returns that domain

and is counting on Postgraphile treating that domain as an alias for text, accepting any options, instead of the specific enum options.

I think this is sufficiently unlikely that we shouldn't consider it a breaking change.

### Supporting development

I [tick all that apply]:

- [x] am interested in building this feature myself
- [x] am interested in collaborating on building this feature
- [x] am willing to help testing this feature before it's released
- [ ] am willing to write a test-driven test suite for this feature (before it exists)
- [x] am a [Graphile sponsor](https://www.graphile.org/sponsor/) ❤️
- [x] have an active [support or consultancy contract](https://www.graphile.org/support/) with Graphile

**Comment by ben-pr-p** [comment]
I'd love to get to work on this since we don't have a great alternative in our codebase right now.

I took a look at the enum / domain code, and I think what needs to be done is to a check inside [of this if statement](https://github.com/graphile/graphile-engine/blob/v4/packages/graphile-build-pg/src/plugins/PgTypesPlugin.js#L995) to see if the domain matches our conditions.

If it does, fetch the enum type and name and use it instead of fetching the base type, as is done now.

We should also assert and throw if the domain base type isn't (or is incompatible with) text.

I don't see anything else I'd need to do in the code to make it work, let me know if I'm missing something!

**Comment by ben-pr-p** [comment]
It looks like we're already fetching the comments on domains: https://github.com/graphile/graphile-engine/blob/v4/packages/graphile-build-pg/src/plugins/introspectionQuery.js#L241

**Comment by ben-pr-p** [comment]
After successfully completing this, I'm getting:
```
Error: Error occurred when processing database type 'public.stage_options_enum_domain' (type=d):
  graphile-build:warn   A type naming conflict has occurred - two entities have tried to define the same type 'StageOptions'.
  graphile-build:warn   
  graphile-build:warn     The first entity was:
  graphile-build:warn   
  graphile-build:warn       'newWithHooks' call during hook 'PgConnectionArgCondition/init/PgConnectionArgCondition'
  graphile-build:warn   
  graphile-build:warn     The second entity was:
  graphile-build:warn   
  graphile-build:warn       'addType' call during hook 'PgQueryProceduresPlugin/GraphQLObjectType:fields/PgQueryProcedures'
  ```

which makes sense, since I'm adding another type with the same functionality but a different id, so subsequent plugins are attempting to register it twice.

**Comment by benjie** [comment]
Closing this issue in favour of the PR graphile/graphile-engine#748 to keep conversation in one place 👍
