### ISSUE TITLE
Remove all generated queries except `all`

### ISSUE THREAD

**Issue by Tam** [graphile/postgraphile#1504]
Is it possible to remove the auto-generated queries, except for the `all` query, and keep relational reads?

For example, I want to remove `account` and `accountByEmail` while keeping the `user { account }` query (related by `user_id` on the account).

```diff
{
  allUsers { }
  user {
    account { }
  }
- account { }
- accountByEmail { }
}
```

(In the example above, I'm already ommiting the `allAccounts` query using smart tags)

**Comment by benjie** [comment]
Sure; you can use the ["Removing things from the schema"](https://www.graphile.org/postgraphile/extending-raw/#removing-things-from-the-schema) part of the docs. A custom plugin to do this for every field that doesn't start with `all` would be something like:

```js
function RemoveEverythingFromQueryExceptAll(builder) {
  builder.hook("GraphQLObjectType:fields", (fields, _, { Self }) => {
    if (Self.name !== 'Query') return fields;
	for (const key in fields) {
      if (!key.startsWith("all")) delete fields[key];
	}
    return fields;
  });
}
```

You probably want something a bit more nuanced; but this is a start ;)

**Comment by Tam** [comment]
Perfect, thanks!
