### ISSUE TITLE
use custom key to select by id, update by Id or delete by Id operations

### ISSUE THREAD

**Issue by imVinayPandya** [graphile/postgraphile#1531]
### Summary
I am new to Postgraphile and i am currently learning it. I have one question if you guys can help me.

I have two columns in database table
1. id (Auto increment)
2. public_id (uuid)

here id I am using for FKEY relation and uuid will be used by web app or mobile app to select, update, delete operations.

By default PostGraphile generate select, update and delete operation by using ID (auto increment) column, I want to use public_id to be used instead of ID. 

currently id writing custom psql function for doing above operation using public_id. 
can anyone suggest me a batter solution?

**Comment by benjie** [comment]
Welcome! Add a unique constraint to the `public_id` column.

Please ask further questions in #help-and-support on the Graphile Discord: https://discord.gg/graphile :+1:

**Comment by imVinayPandya** [comment]
Thank you @benjie it worked and will post questions in discord.
