### ISSUE TITLE
Add output of the errors to the console when reporting an error.

### ISSUE THREAD

**Issue by gjbadros** [graphile/postgraphile#1533]
Hi Benjie! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `postgraphile@4.12.4` for the project I'm working on.

I want server-side logs to show more details about the error reported, rather than having to use telemetry from the client (sentry, amplitude, whatever) to figure out what went wrong with a query. I'm not sure if there's an already-supported different approach to this, but I'm finding this tiny change to the "1 error(s) ..." output that shows the query very valuable.  It just also shows the errors to the console.

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/postgraphile/build/postgraphile/http/createPostGraphileHttpRequestHandler.js b/node_modules/postgraphile/build/postgraphile/http/createPostGraphileHttpRequestHandler.js
index ac3db5d..50d4d34 100644
--- a/node_modules/postgraphile/build/postgraphile/http/createPostGraphileHttpRequestHandler.js
+++ b/node_modules/postgraphile/build/postgraphile/http/createPostGraphileHttpRequestHandler.js
@@ -778,7 +778,7 @@ function createPostGraphileHttpRequestHandler(options) {
                                 message = chalk_1.default[errorCount === 0 ? 'green' : 'red'](`${errorCount} error(s)`);
                             }
                             // tslint:disable-next-line no-console
-                            console.log(`${message} ${pgRole != null ? `as ${chalk_1.default.magenta(pgRole)} ` : ''}in ${chalk_1.default.grey(`${ms.toFixed(2)}ms`)} :: ${prettyQuery}`);
+                            console.log(`${message} ${pgRole != null ? `as ${chalk_1.default.magenta(pgRole)} ` : ''}in ${chalk_1.default.grey(`${ms.toFixed(2)}ms`)} :: ${prettyQuery} :: ${JSON.stringify(result.errors)}`);
                         });
                     }
                     if (debugRequest.enabled)
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by benjie** [comment]
We deliberately do not do this as it could lead to leaking confidential information to the logs. Similarly we don’t log variable values for the same reason. I’m glad you can use patch-package to address this if you don’t agree with my reasoning 👍

**Comment by gjbadros** [comment]
Maybe just control it with an environment variable that is described with
the appropriate warnings?  Or allow a sanitize function?  It's super
helpful during development minimally and in general one should secure logs
the same as other data.
