### ISSUE TITLE
How are GraphQL operations stored in a file into a Flutter app managed by Postgraphile?

### ISSUE THREAD

**Issue by warcayac** [graphile/postgraphile#1536]
When a query is run on the interactive GraphQL interface, an entry is generated in its log, for example:
```
mygraphql | 2021-09-29T17:22:14.196819135Z 0 error(s) as anonymous in 38.28ms :: mutation PurchaserExists($p1: String!, $p2: String!, $p3: String!, $p4: Int!, $p5: String!, $p6: String!, $p7: Int!, $p8: Int!, $p9: String!) { registerPurchaser( input: {email: $p1, password: $p2, fullName: $p3, iddocType: $p4, iddocNo: $p5, phoneNo: $p6, customerType: $p7, district: $p8, address: $p9} ) { result { uid } } }
```
So I understand an entry is an operation executed in Postgraphile.

In my Flutter app I have 2 (*.graphql) files, one for queries and another for mutations, then making any request to server from my app (I'm using [ferry](https://pub.dev/packages/ferry) package), in the Postgraphile's log an entry is generated, but this entry contains all operations stored in the file where the request was originated. 

Example: In `fileA.graphql` contains 10 queries (query1,query2,...), then the entry generated by Postgraphile is some like this:

```
mygraphql | 2021-09-29T16:56:08.372551771Z 0 error(s) as anonymous in 4.79ms :: query1 {} query2 {} ... query10 {} 
```
How should I interpret it? Are all queries into that file run when calling a only query? Should I create a file per GraphQL operation?

**P.S.:** I asked this question in Ferry's site and they said `it sounds like this is a question about Postgraphile`.

**Comment by benjie** [comment]
We should probably add the operationName to the log so you know which operation you executed. In the mean time splitting your queries to one per file should solve it.

**Comment by benjie** [comment]
The errors are visible in the client; we do not log them to the server as they may contain confidential information.

**Comment by warcayac** [comment]
Thanks again.
