### ISSUE TITLE
sql.value does not support arrays

### ISSUE THREAD

**Issue by mgummelt** [graphile/postgraphile#1553]
### Summary

sql.value renders arrays as objects, not arrays

### Steps to reproduce

Pass an array to sql.value when constructing a SQL statement (e.g. through resolveInfo.graphile.selectGraphQLResultsFromTable).  Observe the SQL error that results.

### Expected results

A successful query against a `json` type in Postgres.

### Actual results

I don't know how to get postgraphile to show me the raw query it's generating, but the error indicates it's rendering an array using "{}" syntax instead of "[]" syntax.

```
postgres-plato_1  | 2021-11-01 18:28:47.580 UTC [191] ERROR:  invalid input syntax for type json
postgres-plato_1  | 2021-11-01 18:28:47.580 UTC [191] DETAIL:  Expected ":", but found "}".
postgres-plato_1  | 2021-11-01 18:28:47.580 UTC [191] CONTEXT:  JSON data, line 1: {"0"}
```

**Comment by mgummelt** [comment]
Hm, I see now that pg-sql2 is rendering the array not as an object, but as a Postgres array, which uses "{}" syntax.  I suppose that makes sense, but it remains difficult to pass in an array as a value to a `jsonb` predicate.  I'm currently just calling `JSON.stringify` on the array to perform the serialization myself.  Feel free to close this if nothing can be done.

**Comment by benjie** [comment]
The intended usage is that you do `sql.value(JSON.stringify(json))` :+1:

**Comment by mgummelt** [comment]
It would be great to have a higher level query client a la Prisma.  Then the client could be aware of how the value is being used, and serialize it appropriately.
