### ISSUE TITLE
Docker Hub doesn't list new releases

### ISSUE THREAD

**Issue by philon123** [graphile/postgraphile#1556]
Postgraphile is currently on version 4.15, but the newest version on Docker Hub is 4.13 and 6 months old. It looks like maybe there is an issue with the build pipeline..? 

Also, whats up with the naming convention for the tags on Docker Hub? Here is a list, newest to oldest, from the tags page (https://hub.docker.com/r/graphile/postgraphile/tags):

4-12
4-12-3
v4.12.3
4-12-2
v4.12.2
v4.12.1
v4.12.0
4
4-12-1

**Comment by benjie** [comment]
Indeed, I only just discovered the docker hub issue in #1557 

The naming conventions are detailed here: https://www.graphile.org/postgraphile/deploying-docker/

Closing as duplicate
