### ISSUE TITLE
Docker hub doesn't have the latest images

### ISSUE THREAD

**Issue by Bonemind** [graphile/postgraphile#1557]
### Summary

When using the latest docker image, the port set in the connection string seems to get lost somehow. The rest of the connection string is parsed fine.

### Steps to reproduce

This seems to be consistently reproducable with the `latest` docker image:
```
docker run --rm -it -p 5000:5000 graphile/postgraphile --connection 'postgres://some:user@172.17.0.1:9193/somedb'
```

### Expected results

Expected is either a connection, or at least an error connecting to port 9193. Expected:

```
PostGraphile v4.12.1 server listening on port 5000 🚀

  ‣ GraphQL API:         http://0.0.0.0:5000/graphql
  ‣ GraphiQL GUI/IDE:    http://0.0.0.0:5000/graphiql (RECOMMENDATION: add '--enhance-graphiql')
  ‣ Postgres connection: postgres://some:[SECRET]@172.17.0.1:9193/somedb
  ‣ Postgres schema(s):  public
  ‣ Documentation:       https://graphile.org/postgraphile/introduction/
  ‣ Node.js version:     v12.22.1 on linux x64
  ‣ Join Splitgraph in supporting PostGraphile development: https://graphile.org/sponsor/

* * *

```
This output was captured with the same command as above, but I added `-e "PGPORT=9193"`. After this addition postgraphile works as expected.

### Actual results

```
PostGraphile v4.12.1 server listening on port 5000 🚀

  ‣ GraphQL API:         http://0.0.0.0:5000/graphql
  ‣ GraphiQL GUI/IDE:    http://0.0.0.0:5000/graphiql (RECOMMENDATION: add '--enhance-graphiql')
  ‣ Postgres connection: postgres://some:[SECRET]@172.17.0.1/somedb
  ‣ Postgres schema(s):  public
  ‣ Documentation:       https://graphile.org/postgraphile/introduction/
  ‣ Node.js version:     v12.22.1 on linux x64
  ‣ Join Chris Watland in supporting PostGraphile development: https://graphile.org/sponsor/

* * *

A serious error occurred when building the initial schema. Exiting because `retryOnInitFail` is not set. Error details:

Error: connect ECONNREFUSED 172.17.0.1:5432
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1144:16)
```

### Additional context

About 7 months ago this used to work as expected. It seems like somehow the port is lost from the connection string, especially since setting the `PGPORT` env var connects on the right postgres port

**Comment by benjie** [comment]
This was fixed in 4.12.3: https://github.com/graphile/postgraphile/releases/tag/v4.12.3

It seems Docker Hub no longer build the images; looks like they require a paid subscription to get this working again (cc @jemgillam)

In the mean time, you can probably create your own Docker image relatively easily; there's a number of example Dockerfiles in the docs, e.g. https://www.graphile.org/postgraphile/running-postgraphile-as-a-library-in-docker/#create-postgraphile-dockerfile

**Comment by DanielFGray** [comment]
> It seems Docker Hub no longer build the images; looks like they require a paid subscription to get this working again

For whatever it's worth, I believe GitHub Actions should allow you to build a new container image and push to Docker Hub

**Comment by Bonemind** [comment]
Apologies, this one slipped my mind. Using a different version indeed fixed the issue. Thanks.

**Comment by benjie** [comment]
Reopening to remind me to publish the new images.

**Comment by endersonmaia** [comment]
at docker hub we have `:latest` but don't have tagged versions like `v4.12.6`

the last version on docker hub is `v4.12.3`

**Comment by benjie** [comment]
Yes, the next release should go out automatically when it gets tagged, but the process wasn’t retroactive alas. Maybe I can tag the existing release via docker hub? I don’t use Docker so not super familiar with its capabilities/etc.

**Comment by endersonmaia** [comment]
> Yes, the next release should go out automatically when it gets tagged, but the process wasn’t retroactive alas. Maybe I can tag the existing release via docker hub? I don’t use Docker so not super familiar with its capabilities/etc.

yes, you can

just build each image with the proper tags, locally, and then push it to docker hub

https://docs.docker.com/engine/reference/commandline/image/

**Comment by benjie** [comment]
I was trying to avoid doing a local build :wink: 

I've just tagged a new version which went out automatically :+1: 

https://github.com/graphile/postgraphile/runs/4581198874?check_suite_focus=true
https://hub.docker.com/r/graphile/postgraphile/tags
