### ISSUE TITLE
How to limit tables?

### ISSUE THREAD

**Issue by damaon** [graphile/postgraphile#1581]
### Summary

I have 20K lines of schema for real app. I don't need/want to modify all this stuff. 
I would like to limit inference/autogeneration for 3 tables for example. Is it possible? 

I think would like such UX:
```
$ Which tables you want to expose?
> TableA
> TableB
[enter]
$ Which operations for TableA?
> Update
>Which for TableB?
> Delete, Create
```

I hope this helps to explain what I want.

I don't mind inference for everything but I would like to limit what's available in graphql.

**Comment by benjie** [comment]
I would recommend that you use the option --no-ignore-rbac and then only grant the postgres user that you use with PostGraphile access to the tables and methods that you wish to expose. There are many other ways to achieve it, but this is the best in my opinion.

**Comment by damaon** [comment]
Thanks for answer Benjie
