### ISSUE TITLE
How to extend `node` resolver

### ISSUE THREAD

**Issue by husseinhere** [graphile/postgraphile#1582]
Let's say I want to create my own (non-database backed) type. It's pretty straight forward with `makeExtendSchemaPlugin` to do something like this: 

```
      type RemoteUser implements Node {
        nodeId: ID!
        uname: String!
      }
```

And let's say for a user `alice`, I create the nodeId `base64Encode('["RemoteUser","alice"]')`

How would I extend the `node` resolver such that:

```
query MyQuery {
  node(nodeId: "WyJSZW1vdGVVc2VyIiwiYWxpY2UiXQ==") {
    nodeId
    ... on RemoteUser {
      uname
    }
  }
}
```

would actually work?

**Comment by ab-pm** [comment]
The resolver can be found [here](https://github.com/graphile/graphile-engine/blob/1619878d964b222332c8d4092bd6a654c1ec6595/packages/graphile-build/src/resolveNode.js), and uses the `nodeFetcherByTypeName` dictionary that you can fill using [`build.addNodeFetcherForTypeName()`](https://github.com/graphile/graphile-engine/blob/a9fcbafc52244495420faac5da0e05cbceaf5e69/packages/graphile-build/src/plugins/NodePlugin.js#L79-L87).

**Comment by husseinhere** [comment]
Thanks for the help! I hate to ask for too much, but could you show me how you'd make a plugin that would intercept the `RemoteUser` typename. I'm a bit lost in the plugin / hook system and can't figure out exactly what I should be doing

**Comment by benjie** [comment]
Here's where it works for Postgres stuff:

https://github.com/graphile/graphile-engine/blob/a9fcbafc52244495420faac5da0e05cbceaf5e69/packages/graphile-build-pg/src/plugins/PgRowNode.js#L36


Here's the skeleton of a plugin:

```js
module.exports = builder => {
  builder.hook('init', (_, build, context) => {
    build.addNodeFetcherForTypeName(
      'RemoteUser',
      (_, identifiers) => getRemoteUser(identifiers[0])
    );
    return _;
  });
}
```

**Comment by husseinhere** [comment]
Thanks @benjie I feel like I'm so close, but just not quite there. I have the plugin:
```
export const nodeResolverPlugin: Plugin = (builder) => {
  builder.hook("init", (object, build, context) => {
    build.addNodeFetcherForTypeName(
      "RemoteUser",
      (x: any, identifiers: any[]) =>
        console.log("Got Remote User: ", x, identifiers)
    );
    return object;
  });
};
```
and I'm adding it to `appendPlugins`.  The fetcher gets registered (by the fact it gives an error if I try do it twice). Yet when I create a query:

```
query MyQuery {
  node(nodeId: "WyJSZW1vdGVVc2VyIiwiYWxpY2UiXQ==") {
    nodeId
  }
}
```

That debug line never gets executed

**Comment by husseinhere** [comment]
Thanks! That helps immensely.
