### ISSUE TITLE
Array of foreign keys in function

### ISSUE THREAD

**Issue by RyanDurk** [graphile/postgraphile#1586]
### Summary

A function returns people integer[], which is an array of foreign keys. Can a smart comment coerce the graphql endpoint to return people as a connection?

I tried setting the comment:

comment on function get_people() is E'@foreignKey (people) references public.user(id)';

**Comment by benjie** [comment]
Return a set of people directly, rather than a set of int

**Comment by RyanDurk** [comment]
> Return a set of people directly, rather than a set of int

Adding public.user in an inner join and returning a table with the people column as array_agg(public.user.*) worked. Thanks!

**Comment by RyanDurk** [comment]
It's actually returning a table with several joins and a public.user array in the table as a column of the returned table. I'm not sure having nested tables/sets is possible in Postgres? 14.1 is rejecting all my attempts as syntax errors.

**Comment by benjie** [comment]
Ah. Bold choice. :+1:
