### ISSUE TITLE
Looking for recommendation: Table View UI Component for React? 

### ISSUE THREAD

**Issue by markhalonen** [graphile/postgraphile#1590]
Feel free to close this, just checking for recommendations.

We have tables in our React UI that have >4000 rows. We need filter/sort/paginate functionality, implemented server-side via the awesome Postgraphile stack. We also generate Typescript types and would like that type safety in our tables.

It seems neither https://mui.com/components/data-grid/ nor https://github.com/TanStack/react-table are great solutions, so we're looking at rolling our own. 

I figured I'd check here if someone in the Postgraphile community already built something awesome for this!

**Comment by benjie** [comment]
Try asking in the #watercooler channel of discord https://discord.gg/graphile
