### ISSUE TITLE
curl not responding

### ISSUE THREAD

**Issue by pablocavalieri** [graphile/postgraphile#1600]
### Summary
Like the title says. I've been playing with postgraphile and suddenly, in one of my deploys, the curl command to the API just hangs. It's not a DB data problem because the curl request is not even valid (it hangs with valid requests too).   
`curl localhost:5000` just hangs.      
The logs shows that the application started correctly    
```
PostGraphile v4.12.9 server listening on port 5000 🚀

  ‣ GraphQL API:         http://localhost:5000/graphql
  ‣ GraphiQL GUI/IDE:    http://localhost:5000/graphiql
  ‣ Postgres connection: postgres://<my_db_server>/<my_db>
  ‣ Postgres schema(s):  <my_schema>
  ‣ Documentation:       https://graphile.org/postgraphile/introduction/
  ‣ Node.js version:     v8.10.0 on linux x64
  ‣ Join Nathanael Beisiegel in supporting PostGraphile development: https://graphile.org/sponsor/

* * *
```
If I run a `psql` query it returns results.   
`psql -h <my_db_server> -p 5432 -d <my_db> -c "select * from <my_schema>.<table_name>"`     

### How I am building the app
I'm using a `Dockerfile` and deploying it in kubernetes
```
FROM ubuntu:18.04
# install postgres and node
RUN apt-get update
RUN apt-get -y install postgresql postgresql-contrib nodejs npm
# install postgraphile 
RUN npm install -g postgraphile @graphile-contrib/pg-simplify-inflector postgraphile-plugin-connection-filter
#Run script
COPY startserver.sh /
RUN chmod u+x startserver.sh
CMD bash startserver.sh
EXPOSE 5000
```
`startserver.sh` script
```
#!/bin/bash
export PGUSER=<my_db_user>
export PGPASSWORD=<my_db_password>
postgraphile -c postgres://<my_db_server> -s <my_schema> \
  --no-ignore-rbac --dynamic-json --enable-query-batching \
  --append-plugins @graphile-contrib/pg-simplify-inflector,postgraphile-plugin-connection-filter \
  --enhance-graphiql
```

### Versions used
postgraphile version: 4.12.9
postgres version: 12.2

**Comment by benjie** [comment]
Node 8.x is ancient, it went end of life December 31, 2019! Strongly suggest you upgrade to something more modern: https://nodejs.org/en/about/releases/

Can you reproduce this issue without using Docker?

Can you reproduce this issue with the official Docker image?

**Comment by pablocavalieri** [comment]
About reproducing the issue, I can run the same docker image using the same kubernetes deploy manifest (k-native) on another environment with the same DB schema and it works.    
I need to get it working on the environment where it fails but I don't gen any debugging information that gives me a clue on what's going on.   
I set the debug envars (https://www.graphile.org/postgraphile/debugging/) and still when making a `curl` request I get no log

**Comment by benjie** [comment]
I can't help feeling that it's something Docker/K8s going wrong, rather than being PostGraphile specific...

**Comment by pablocavalieri** [comment]
You seem to be right. Feel free to close this question.
