### ISSUE TITLE
How to check for an unique session? 

### ISSUE THREAD

**Issue by warcayac** [graphile/postgraphile#1628]
### Summary

I don't know if this question belongs to Postgraphile topic, but I'm going with it:

I wish when an user logged in from my Android app (or from any platform), Postgraphile checks if there an existing session for that account, if there is then it closes that session and creates a new session, that is, I wish there to be an unique active session. How to get it? Any advice is welcome.

**Comment by benjie** [comment]
https://discord.gg/graphile
