### ISSUE TITLE
When using watchPg, the schema stop being updated automatically after a few minutes

### ISSUE THREAD

**Issue by niolap** [graphile/postgraphile#1638]
### Summary

I'm using option watchPg (set to true). When I start Graphile, the schema gets updated automatically at the beginning. But after a few minutes, it stops being updated and I see no error in Graphile logs.

- Have you seen this before?
- Have you an idea on how I can see some logs about what's happened to give me a clue?

### Additional context

The issue occurred when using Graphile and Postgres in two different containers.
I tried without containers (with Postgres and Graphile on the same server), and I don't have this issue.

**Comment by benjie** [comment]
1. Are you using a proxy/bouncer for your postgres?
2. Are the connections between PostGraphile and your database being interrupted? E.g. some kind of "idle timeout" or similar?


If you pass a custom pool to PostGraphile you could add event listeners to it to be notified when connects/etc occur: https://node-postgres.com/api/pool#events

**Comment by niolap** [comment]
@benjie reading your comment led me to the answer. I change two things:

- `net.ipv4.tcp_keepalive_time` to 60 second on both containers
- `tcp_keepalives_idle` to 60 in the Postgres parameters

It looks like something was breaking the TCP connection after a few minutes of inactivity.
Thank you @benjie

**Comment by benjie** [comment]
Suggests we don’t reconnect on watch connection breakage which seems non-ideal…

**Comment by niolap** [comment]
@benjie, I'm not sure about that because in a non-container environment, with PostGraphile and Postgres on the same Linux machine, there is no issue. So, the issue only happens in container environment + I also have pgAdmin in another container that suffers the same issue with idle connections. I think PostGraphile detects the connection is broken and gets a new one from the pool transparently. But when Postgres notify a change to PostGraphile, then the notification never arrives in graphile even though for Postgres the TCP connection looks still good.
Anyway, the keep-alive setting fixes/workarounds this issue so I'll keep it like that.
