### ISSUE TITLE
Max depth and spam limiting?

### ISSUE THREAD

**Issue by ldesgoui** [graphile/postgraphile#164]
Hello,

I was wondering if "query-bombing" was taken care of ?
By that I mean something like `query { object { item { object { item { ... }}}}}`

This tool has been great so far, thanks.

**Comment by calebmer** [comment]
Yep, this is something that's important to address. I'm going to need to do research on this first, do you have a specific proposal and/or like how another library does it?

**Comment by ldesgoui** [comment]
I haven't read anything from Facebook about "malicious" attacks, they definitely should address it.
It seems like other libraries are simply validating on the maximum depth of a query. It seems like a naive but good enough implementation for most.
I feel that PostGraphQL could achieve more, though. Full introspection on the SQL schema can probably allow for a better estimation of the complexity. I only know basics about SQL/Postgres, I wouldn't be able to offer such an algorithm.
Another way could be to treat this as standard rate limiting, e.g: allow for 2000 SQL row hits per minute.
Either way, those scores could probably be used before the execution (in AST traversal) or during it.

Thanks

**Comment by calebmer** [comment]
I’m thinking for now we could just add a depth check, it may be too confusing and frustrating for users to hit the wall on an invisible algorithm that may be technically correct. If someone wants to add this feature or bring in a library that does this I’ll merge :+1:

**Comment by hmaurer** [comment]
Depth limiting is now available as a paid plugin (c.f. https://www.graphile.org/postgraphile/pricing/), or can, I think, alternatively be implemented as a step before passing the query to Postgraphile (when using it as a library). Should this issue be kept open @benjie ? The topic of security when using graphql probably deserves more discussion, but perhaps this old issue is not the place for it.

**Comment by benjie** [comment]
This topic is now discussed in the docs here: https://www.graphile.org/postgraphile/production/#limiting-graphql-query-depth

The pro plugin also has some very early query cost estimation features, but they are subject to heavy iteration.
