### ISSUE TITLE
When running postgraphile via npx with --cors, it does not properly include Access-Control-Allow-Origin in Access-Control-Allow-Headers

### ISSUE THREAD

**Issue by redaikidoka** [graphile/postgraphile#1641]
### Summary

When running postgraphile via npx with the --cors option, it does not include Access-Control-Allow-Origin in Access-Control-Allow-Headers.

When using CORS, the Apollo client does an OPTIONS query, and looks at response's
`Access-Control-Allow-Headers` to see what other headers it can accept.

PostGraphile is returning:
`Access-Control-Allow-Headers: Origin, X-Requested-With, Accept, Authorization, X-Apollo-Tracing, Content-Type, Content-Length, X-PostGraphile-Explain`

which includes `Origin` but NOT `Access-Control-Allow-Origin` and therefore Apollo client is ignoring the Access-Control-Allow-Headers and throwing the error:

``` 
Access to fetch at 'http://lvh.me:5000/graphql' from origin 'http://lvh.me:3333' has been blocked by CORS policy: Request header field access-control-allow-origin is not allowed by Access-Control-Allow-Headers in preflight response.
```

and refusing to connect to postGraphile. 

### Steps to reproduce

1. run postgraphile:  `npx postgraphile -n lvh.me -c postgres://gemini:abc123@localhost/gemini --enhance-graphiql --simple-collections both --show-error-stack --cors`

2. create a nextjs app `npx create-next-app@latest --typescript`

3. `yarn add @apollo/client`
4. add apollo-client.js: 
```
// ./apollo-client.js

import {
  ApolloClient,
  InMemoryCache,
  ApolloLink,
  HttpLink
} from '@apollo/client';
import { getCookie } from 'cookies-next';

// use lvh.me for development and localhost for staging and production
const httpMonolithLink = new HttpLink({
  uri: process.env.NEXT_PUBLIC_GQL_SERVER
});
const httpPostGraphileLink = new HttpLink({
  uri: process.env.NEXT_PUBLIC_P_GQL_SERVER
});
const authLink = new ApolloLink((operation, forward) => {
  /*
    NOTE: You need to login to `GQL_URL` (lvh.me:3000) (the monolith) in your browser
    to have the needed auth token cookie accessible to this app
  */
  const userEmail = getCookie('apiTokenEmail');
  const userToken = getCookie('apiToken');

  // Use the setContext method to set the HTTP headers.
  operation.setContext({
    headers: {
      'X-User-Email': userEmail,
      'X-User-Token': userToken,
      'Access-Control-Allow-Origin': '*'
    }
  });

  // console.log('ApolloClient: httpMonolithLink', httpMonolithLink);
  // console.log('ApolloClient: httpPostGraphileLink', httpPostGraphileLink);

  // Call the next link in the middleware chain.
  return forward(operation);
});

// load from server
const client = new ApolloClient({
  link: ApolloLink.split(
    (operation) => operation.getContext().clientName === 'postGraphile',
    authLink.concat(httpPostGraphileLink),
    authLink.concat(httpMonolithLink)
  ), // Chain it with the HttpLink
  cache: new InMemoryCache()
});

export default client;
```

5. run a query with useQuery in a component:
```
const { data, loading, error } = useQuery(SIMPLE_MATERIALIZED_CASE, {
    context: { clientName: 'postGraphile' }
  });
```

### Expected results

We should get data back. Running any simple query as in graphiQL should return the same query, e.g.
```query MyQuery {
  allActionLogs(first: 20) {
    edges {
      node {
        id
        actionLog
        actionSeconds
        affectedRecords
        createdAt
      }
    }
  }
}
```

### Actual results

<img width="1464" alt="Screen Shot 2022-06-14 at 09 47 41" src="https://user-images.githubusercontent.com/4842817/173632298-281a5bab-a212-48f5-a41d-7f14770d2006.png">

the Apollo client refuses to send the actual query because the header that would allow it to do that is not in the header that specifies what headers Apollo can look at. 

### Additional context

Mac OS 12.4
postGreSQL 11
NextJS
React 18

Project dependencies:
```
"dependencies": {
    "@apollo/client": "^3.6.5",
    "@emotion/react": "^11.9.0",
    "@emotion/styled": "^11.8.1",
    "@fortawesome/fontawesome-pro": "^6.1.1",
    "@fortawesome/fontawesome-svg-core": "^6.1.1",
    "@fortawesome/free-solid-svg-icons": "^6.1.1",
    "@fortawesome/pro-light-svg-icons": "^6.1.1",
    "@fortawesome/pro-solid-svg-icons": "^6.1.1",
    "@fortawesome/react-fontawesome": "^0.1.18",
    "@mui/material": "^5.8.1",
    "@mui/x-data-grid": "^5.11.1",
    "cookies-next": "^2.0.4",
    "graphql": "^16.5.0",
    "jest-environment-jsdom": "^28.1.0",
    "next": "^12.1.6",
    "react": "18.1.0",
    "react-dom": "18.1.0",
    "react-hook-form": "^7.31.2",
    "rollbar": "^2.25.0",
    "sass": "^1.52.1",
    "yup": "^0.32.11"
  },
```

### Possible Solution

Is there any way that I can use a command-line switch to specifically add  `Access-Control-Allow-Origin` to response header `Access-Control-Allow-Headers` ?

**Comment by benjie** [comment]
Why would it make sense to have the client send `Access-Control-Allow-Origin` to the server? The header is intended for the server to tell the client the origins that are allowed:

https://fetch.spec.whatwg.org/#http-access-control-allow-origin

Here's the relevant code in PostGraphile:

https://github.com/graphile/postgraphile/blob/ed6ecb4596088120969795a9ec30cb625ef93eae/src/postgraphile/http/createPostGraphileHttpRequestHandler.ts#L1158-L1180

**Comment by redaikidoka** [comment]
Yes but that is what apolllo client expects apparently.

**Comment by benjie** [comment]
Seems like that may be a bug in Apollo Client if so; I don’t think it makes sense for us to add this to the headers.

**Comment by redaikidoka** [comment]
Is the `Access-Control-Allow-Headers` meant to explicitly name the headers allowed?

**Comment by benjie** [comment]
Yes, it names the headers that the client is permitted to send 👍
