### ISSUE TITLE
Hiding Fields from Introspection

### ISSUE THREAD

**Issue by shellscape** [graphile/postgraphile#1654]
### Summary

There have been quite a few issues opened regarding conditional hiding of fields, types, etc from introspection. But those all relate to some dynamic conditions. What I'm after is something similar to a method I've used successfully many times with Apollo: https://www.useanvil.com/blog/engineering/undocumented-directive/

That leverages directives, something we've also covered here in issues before. However, the methodology in the article linked is vastly different to anything discussed in issues for directives.

Before I go down the rabbit hole, I wanted to ask if anything comes to mind for (even crudely) accomplishing the same result as the method linked above describes.

**Comment by benjie** [comment]
A) doing this means your API is not a GraphQL API

B) a directive isn’t important; see what the directive _does_ (for example, what properties does it set on which objects?) and then do that same change via the Graphile-Build APIs (or even just to the schema after it’s built via makeProcessSchemaPlugin). It’s just a GraphQL.js schema at the end of the day.

Closing this because I don’t want PostGraphile’s schema to be non-spec-compliant.

**Comment by shellscape** [comment]
In light of that, is there any way to turn off or disable the introspection query?

**Comment by shellscape** [comment]
I found this https://github.com/graphile/postgraphile/wiki/Disable-GraphQL-introspection buried in the repo after doing some source diving around `postgraphile:validationRules:static` and how to disable introspection altogether, rather than piecemealing bits. I think it'd be very helpful to integrate this into Postgraphile core (Apollo provides this as a config option), but barring that, adding this to the documentation site would be extremely helpful to folks.

**Comment by benjie** [comment]
Disabling introspection is, at best, security through obscurity. It is something that I actively discourage, so there's no way I'd add it as a built in option to PostGraphile.

A far superior solution is persisted operations (and I'm not talking Apollo's "automatic persisted queries", which are... not appropriate for this use case); read more here:

- https://www.graphile.org/postgraphile/production/#simple-query-allowlist-persisted-queries--persisted-operations
- https://github.com/graphile/persisted-operations

**Comment by benjie** [comment]
I've updated the above linked wiki page with more details; thanks for bringing it to my attention

https://github.com/graphile/postgraphile/wiki/Disable-GraphQL-introspection
