### ISSUE TITLE
Docs for server-side requests that bypass the network?

### ISSUE THREAD

**Issue by spiffytech** [graphile/postgraphile#1660]
### Summary

The PostGraphile home page says:

> *Server-side rendering*
> Issue requests to your PostGraphile API without network roundtrips, fantastic for React SSR

I haven't been able to find the docs on how to make queries/mutations from my Node.js code without hitting the network. Where can I find info on that?

**Comment by benjie** [comment]
That's called "schema-only usage" - where you're consuming the schema directly without the need of a transport:

https://www.graphile.org/postgraphile/usage-schema/

**Comment by spiffytech** [comment]
Thanks!
