### ISSUE TITLE
GraphiQL v2 Released 

### ISSUE THREAD

**Issue by shellscape** [graphile/postgraphile#1666]
GraphiQL v2 has been released. This comes with a lot of UX upgrades and puts it on par visually and functionally with Apollo's Sandbox et al.

I would love to see documentation updates that reflect how, or if it's possible, to leverage this new version with the Postgraphile's enhancements.

Given the length of time that v5 has been in development, the slow pace of improvement for v4, and the huge leap forward that GrapiQL v2 provides, information around this in docs at the least is crucial for the user base of Postgraphile.

**Comment by benjie** [comment]
You can use GraphiQL v2 with any GraphQL API; please see the GraphiQL README:

https://github.com/graphql/graphiql/blob/main/packages/graphiql/README.md#getting-started

For integration of GraphiQL explorer (if that's even necessary any more?), please see that repository:

https://github.com/OneGraph/graphiql-explorer

The headers integration is now native in GraphiQL so PostGraphiQL's solution is no longer needed.

For the explain functionality include the header:

```
X-PostGraphile-Explain: on
```

with your GraphQL request. It's up to you how you choose to render the results of that.

Have fun!
