### ISSUE TITLE
Allow whitespace around database comments for smart tags

### ISSUE THREAD

**Issue by joelmukuthu** [graphile/postgraphile#1673]
### Feature description

Writing smart tags via database comments is often tricky and involves a lot of trial-and-error. For me, most of that involves trying out different styles of formatting. I'd like to be able to format the comment however I want and still achieve the desired outcome.

### Motivating example

A bit of time lost trying to get multiple smart tags on the same column to work. What ended up working was:

```sql
COMMENT
  ON COLUMN "foo"."bar"
  IS E'
@name "baz"
@notNull
@omit create,update';

-- OR:

COMMENT
  ON COLUMN "foo"."bar"
  IS E'@name "baz"\n@notNull\n@omit create,update';
``` 

How I'd have liked to format the comment:

```sql
COMMENT
  ON COLUMN "foo"."bar"
  IS E'
    @name "baz"
    @notNull
    @omit create, update'; -- including whitespace between commas here
``` 

### Breaking changes

N/A

### Supporting development

I [tick all that apply]:

- [x] am interested in building this feature myself - could someone please point me at where to start? :)
- [x] am interested in collaborating on building this feature
- [x] am willing to help testing this feature before it's released
- [x] am willing to write a test-driven test suite for this feature (before it exists)
- [ ] am a [Graphile sponsor](https://www.graphile.org/sponsor/) ❤️
- [ ] have an active [support or consultancy contract](https://www.graphile.org/support/) with Graphile

**Comment by benjie** [comment]
Allowing whitespace around commas in `@omit` is a separate concern, and straightforward to accomplish - take this line:

https://github.com/graphile/graphile-engine/blob/fb4b7f6c1680aa52105013b45b5f4a4639feb0ba/packages/graphile-build-pg/src/omit.js#L64

and change it to use `/\s*,\s*/` as the split instead. Add some tests (or mod the existing ones) and job's a good'un.

As for the leading whitespace in smart comments, we recognise that people already comment on their database entities in various ways and we do not want to interfere with that so we have very strict specification on what qualifies as smart tags: https://www.graphile.org/postgraphile/smart-comments/#smart-comment-spec

If you're uncomfortable with that formatting, I suggest that you consider using a smart tags file instead, here's an example from Graphile Starter:

https://github.com/graphile/starter/blob/main/%40app/server/postgraphile.tags.jsonc

This has many advantages, including:

- you can comment explaining _why_ you added the smart tag
- you don't need to manage them via migrations
- easier to version control
- can use independent tags for two different PostGraphile instances against the same database
- you can use database comments for documenting database features and tags file for documenting GraphQL features

**Comment by joelmukuthu** [comment]
Thanks for the response @benjie. We have a different setup where, even though there are multiple apps accessing the database (specifically the database types), all apps share the same types and expect them to have the same shape. And from a code maintenance point of view, it's easier for us to manage changes when the types are declared and configured in the same place.

The spec is indeed quite clear, so for my problem I see two possible solutions:

1. Redefine what "hence all smart comments start with an @ symbol" means in the spec i.e. `@` must be the first character on a line, disregarding whitespace.
2. Add a config option that enables the behaviour in 1 above.

What do you think?

**Comment by benjie** [comment]
I'm not keen to change the definition of smart comments, nor am I keen to add _yet another_ configuration option.
