### ISSUE TITLE
No conditions on views when using --no-ignore-indexes

### ISSUE THREAD

**Issue by MarkASwanson** [graphile/postgraphile#1675]
### Summary

I can't seem to figure out how to create a view with a condition query parameter.  It seems like such an obvious use case, but I also couldn't find anything about it in the github issues, so I feel maybe I'm just missing something?

### Database Setup

given the setup...

```sql
CREATE TABLE thing (
	thingId SERIAL PRIMARY KEY,
	indexedColumn TEXT NOT NULL
);
CREATE INDEX ON thing (indexedColumn);
GRANT SELECT ON thing TO anonymous;
-- the GRANTs to anonymous are because I am using the JWT authentication setup from the docs.

CREATE VIEW thingView AS
	SELECT * FROM thing;
GRANT SELECT ON thingView TO anonymous;
```

...there is a ```condition``` clause on the ```things``` query but not on the ```thingviews``` query.

### Postgraphile Command
```bash
npx --no-install \
	postgraphile \
		--subscriptions \
		--watch \
		--retry-on-init-fail \
		--dynamic-json \
		--no-setof-functions-contain-nulls \
		--no-ignore-rbac \
		--show-error-stack=json \
		--extended-errors hint,detail,errcode \
		--append-plugins @graphile-contrib/pg-simplify-inflector \
		--export-schema-graphql schema.graphql \
		--graphiql "/" \
		--enhance-graphiql \
		--allow-explain \
		--enable-query-batching \
		--legacy-relations omit \
		--connection $DATABASE_URL \
		--port $APP_PORT \
		--owner-connection $ROOT_DATABASE_URL \
		--schema app_public\
		--classic-ids \
		--no-ignore-indexes \
		--jwt-token-identifier app_public."JWT" \
		--jwt-secret $JWT_SECRET \
		--default-role anonymous \
		--cors
```

### Versions
- postgraphile: 4.12.11
- node: v18.10.0
- npm: 8.19.2
- postgres: 15rc2-alpine (docker)

**Comment by benjie** [comment]
Don’t use `—no-ignore-indexes` since there are no indexes on views. Instead, `@omit` the things you don’t want to sort by/etc. You can use plugins to apply tags based on rules.

(I don’t use views, I prefer functions, which is why it might seem this behaviour is overlooked.)

**Comment by MarkASwanson** [comment]
Ok, thanks for the quick response!

**Comment by MarkASwanson** [comment]
> You can use plugins to apply tags based on rules.

did you have a specific plugin in mind, or did you mean i could create my own?

**Comment by MarkASwanson** [comment]
> Don’t use `—no-ignore-indexes` since there are no indexes on views. Instead, `@omit` the things you don’t want to sort by/etc.

as another thought, it would be nice to have a smart comment that was the opposite of @omit, so that, for instance, one could add a filter on a view column without having to remove --no-ignore-indexes and add a bunch of comments to existing tables to hide all the filters.

**Comment by benjie** [comment]
Yeah, alas adding an opposite cements the current set of options which would prevent others adding their own (e.g. manyToMany). This is why we didn’t do that.

plugin example: https://www.graphile.org/postgraphile/plugin-gallery/#Customisation__OmitMutationsByDefaultPlugin
