### ISSUE TITLE
how can i connect to pg use password contain @/^ character

### ISSUE THREAD

**Issue by flywalker** [graphile/postgraphile#1694]
### Summary
my postgres password like ab@cd^ef

**Comment by benjie** [comment]
Please use percent encoding as indicated in the PostgreSQL docs:

https://www.postgresql.org/docs/current/libpq-connect.html#id-1.7.3.8.3.6:~:text=The%20connection%20URI%20needs%20to%20be%20encoded%20with%20percent%2Dencoding%20if%20it%20includes%20symbols%20with%20special%20meaning%20in%20any%20of%20its%20parts.%20Here%20is%20an%20example%20where%20the%20equal%20sign%20(%3D)%20is%20replaced%20with%20%253D%20and%20the%20space%20character%20with%20%2520%3A
