### ISSUE TITLE
Postgraphile Does not Surface Raised Notices

### ISSUE THREAD

**Issue by machineghost** [graphile/postgraphile#1703]
### Steps to reproduce

Create a function that raises a notice:

```
  -- Return the current logged in user's ID (and also raise it)
  CREATE OR REPLACE FUNCTION public.current_user_id (  )
  RETURNS integer AS $$
  DECLARE result INTEGER;
  BEGIN
  RAISE NOTICE 'Current User ID: %', (SELECT ((NULLIF(current_setting('jwt.claims.person_id'::text, true), ''::text))::integer));  
  RETURN (SELECT ((NULLIF(current_setting('jwt.claims.person_id'::text, true), ''::text))::integer));
  END;
  $$
  LANGUAGE PLPGSQL STRICT SECURITY DEFINER;
```

Run the function from the `psql` command line; note that the raise works, and is logged:

```
$ psql -d goblincrafted -U admin -c "SELECT current_user_id();"
NOTICE:  Current User ID: <NULL>
 current_user_id 
-----------------
                
(1 row)
```
Define a `handleErrors` and pass it to Postgraphile:

```
    handleErrors: err => {
      console.error(`Postgres/Postgraphile Error:`, err);
      return err;
    },

```

Run the function through Postgraphile (eg. make an INSERT policy on a table, have that policy call `current_user_id()`, then go make an INSERT into that table via Graphiql).

### Expected results

`handleErrors` says to log everything, so I expect to see my raised notice.

### Actual results

My notices are nowhere to be found.

### Additional context

Maybe Postgraphile needs another configuration option called `handleNonErrorRaisedStuffThatIsntLoggedOtherwise` (although I'm sure you can make a better name).

**Comment by benjie** [comment]
Notices aren’t errors; but you can see them by enabling the relevant DEBUG envvar:

https://www.graphile.org/postgraphile/debugging/#other-debug-envvars

**Comment by machineghost** [comment]
Heh, sorry I updated my original post, but not fast enough.  I tried doing:

    DEBUG="postgraphile:postgres:notice" next start

but still got no notices.

**Comment by benjie** [comment]
Please try with the PostGraphile CLI and see if you get the same issue. I suspect the issue may lie in what you are doing with PostGraphile.
