### ISSUE TITLE
Password is getting appended to the hostname

### ISSUE THREAD

**Issue by chrispytoes** [graphile/postgraphile#1709]
### Summary

When connecting to the database, I get an ENOTFOUND error. The URL it outputs as being incorrect is my password appended to the beginning of my hostname, literally like: "${password}${hostname}". This has been working for weeks and the issue just started this morning and I didn't change anything. I deleted `node_modules` and `yarn.lock` and reinstalled to no avail.

```
apiRouter.use(
  postgraphile(
    {
      database: process.env.PG_DB,
      port: +(process.env.PG_PORT || '25060'),
      host: process.env.PG_HOST,
      password: process.env.PG_PASSWORD,
      user: process.env.PG_USER,
      ssl: {
        rejectUnauthorized: false,
        ca: process.env.PG_CERT
      }
    },
    'public',
    {
      watchPg: true,
      graphiql: true,
      enhanceGraphiql: true,
      appendPlugins: [ConnectionFilterPlugin, PgMutationUpsertPlugin]
    }
  )
);
```

I've quadruple checked my environment variables that they are indeed correct. I even tried entering the exact fields without the variables and that still does the same thing. Somehow, Postgraphile is appending the password to the hostname before connecting.

**Comment by benjie** [comment]
Instead of passing a configuration object to PostGraphile, pass a `pg.Pool` instance. That way you'll have narrowed the problem down to the `pg` module rather than `postgraphile` itself (which just defers to `pg`).

```js
const pool = new pg.Pool(
    {
      database: process.env.PG_DB,
      port: +(process.env.PG_PORT || '25060'),
      host: process.env.PG_HOST,
      password: process.env.PG_PASSWORD,
      user: process.env.PG_USER,
      ssl: {
        rejectUnauthorized: false,
        ca: process.env.PG_CERT
      }
    }
);
pool.on('error', (e) => {
  console.error(e);
});
pool.on('connect', client => {
  client.on('error', e => {
    console.error(e);
  });
});
apiRouter.use(
  postgraphile(
    pool,
    'public',
    {
      watchPg: true,
      graphiql: true,
      enhanceGraphiql: true,
      appendPlugins: [ConnectionFilterPlugin, PgMutationUpsertPlugin]
    }
  )
);
```

**Comment by chrispytoes** [comment]
@benjie Huh, alrighty then that gives the exact same error. I will post an issue with them.

**Comment by benjie** [comment]
Closing as I don't think this is related to PostGraphile.

Incidentally I trust you've logged out that configuration object and validated that it's not a mistake in your envvars or similar?

**Comment by chrispytoes** [comment]
@benjie Yes I did... This is so weird. I feel like I'm crazy but I've checked and rechecked everything. The appending is definitely happening inside the connection.

**Comment by chrispytoes** [comment]
@benjie No response from them yet but I thought I'd tell you about my further investigation.

It seems that if I rename my password variable to `PG_PASS` instead of `PG_PASSWORD`, it now tries connecting to `undefined${hostname}`. So it seems like `pg` is ignoring my configured password and trying to insert the variable. That being said, it's still generating an invalid hostname regardless.

**Comment by benjie** [comment]
I wonder if there’s any conflict with the native Postgres envvars like PGHOST etc: https://www.postgresql.org/docs/current/libpq-envars.html

**Comment by chrispytoes** [comment]
@benjie Okay... Now this is interesting. It seems for the purposes of validation, `pg` understands all those variables and does not give any errors if I ONLY provide these environment vars, but NOT pass them into the `Pool`, like this: `const pool = new Pool({});`. It does not return any validation errors, but it's trying to use `undefinedundefined` as the hostname like this.

Is it just me or does this sound super weird to you? I tried doing a test without specifying any vars OR options, and it gives a validation error saying the props are missing. So it does consider the standard `PGUSER`, `PGHOST` etc. variables for validation, but not for actually connecting?

**Comment by benjie** [comment]
No idea. Appending to the hostname feels like a port-related thing.
