### ISSUE TITLE
Error: connect ECONNREFUSED 127.0.0.1:5432

### ISSUE THREAD

**Issue by heesukim628** [graphile/postgraphile#1711]
When I run this, I got the below error. Any possible action to resolve this?

docker run --init -p 4000:4000 graphile/postgraphile --connection postgres://***:@@@@@localhost:5432/#### --schema app_public --watch

PostGraphile v4.13.0 server listening on port 5000 🚀

  ‣ GraphQL API:         http://0.0.0.0:5000/graphql
  ‣ GraphiQL GUI/IDE:    http://0.0.0.0:5000/graphiql (RECOMMENDATION: add '--enhance-graphiql')
  ‣ Postgres connection: postgres://postgres:[SECRET]@localhost/postgres (watching)
  ‣ Postgres schema(s):  app_public
  ‣ Documentation:       https://graphile.org/postgraphile/introduction/
  ‣ Node.js version:     v16.19.0 on linux arm64
  ‣ Join Kadi Kraman in supporting PostGraphile development: https://graphile.org/sponsor/

* * *

A serious error occurred when building the initial schema. Exiting because `retryOnInitFail` is not set. Error details:

Error: connect ECONNREFUSED 127.0.0.1:5432
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1278:16)

**Comment by benjie** [comment]
Docker creates a virtual machine. `localhost` inside the virtual machine means exactly that - `localhost` inside the virtual machine. So you're asking PostGraphile to connect to a Postgres instance running inside your Docker virtual machine. I strongly suspect you don't run Postgres inside your virtual machine; I suspect that you are running it elsewhere (perhaps in another instance), so you need to give PostGraphile the connection string that it can use from inside the PostGraphile virtual machine to connect to the "remote" Postgres service.

I'm going to close this; if you need further support please ask in #help-docker on the Graphile Discord at https://discord.gg/graphile
