### ISSUE TITLE
Overriding a mutation field

### ISSUE THREAD

**Issue by Tam** [graphile/postgraphile#1721]
I have a column that has changed from `String` to `UUID`. Is there a way I can override the mutation updating the column to allow for `String | UUID` then convert the `String` to `UUID` as needed?

I'm looking for something like:
```js
makeExtendSchemaPlugin(() => ({
    typeDefs: gql`
        union StringOrUUID = String | UUID
        
        extend input CardPatch {
            placeId: StringOrUUID
        }
    `,
    resolvers: {
        CardPatch: {
            async placeId (value) {
                return /* Convert to UUID if needed */;
            },
        },
    },
}));
```

**Comment by benjie** [comment]
GraphQL does not support a union of scalars.
