### ISSUE TITLE
More Specific Permission Error Messages

### ISSUE THREAD

**Issue by ScottPierce** [graphile/postgraphile#1727]
### Feature description

Better permission error messages, especially when a single field is causing the error.

### Motivating example

```
2023-06-24 16:29:20.678 UTC [34869] ERROR:  permission denied for table example_table
2023-06-24 16:29:20.678 UTC [34869] STATEMENT:  with __local_0__ as (insert into "example"."example_table" ("id", "title", "subtitle", "description", "image_path", "content", "is_root", "slug_id", "preview_title") values($1, $2, NULL, NULL, $3, $4, $5, NULL, $6) returning *) select ((case when __local_0__ is null then null else __local_0__ end))::text from __local_0__
```

The above error is just not clear to people on my team why there is a failure. The reality is simply because there was no insert permission for the `preview_title` field. This is challenging to actually drill down and understand. It almost always causes people on my team hours of wasted effort thinking that it has to do with the role hierarchy not working properly.

**Comment by benjie** [comment]
This error is originating from PostgreSQL, you should raise the issue there (assuming the error doesn’t have enough detail via all the other properties you can expose on it: https://www.graphile.org/postgraphile/debugging/#step-3-increase-postgraphiles-logging )

**Comment by ScottPierce** [comment]
@benjie Is there any downside to just enabling all the extended errors?
```
extendedErrors: ['severity', 'code', 'detail', 'hint', 'position', 'internalPosition', 'internalQuery', 'where', 'schema', 'table', 'column', 'dataType', 'constraint', 'file', 'line', 'routine']
```

**Comment by benjie** [comment]
The main downside is that then people using your API can see all the details from the errors (i.e. its a security concern).

**Comment by ScottPierce** [comment]
Oh, can we just log all the errors to the server and not return them in the
api?

**Comment by benjie** [comment]
Yes, you can do that using `handleErrors`. You have to return _something_ to the API though! Use `error.originalError` to get from the GraphQL error to the underlying (postgres) error in that callback.
