### ISSUE TITLE
postgraphile does not work with bun package manager

### ISSUE THREAD

**Issue by Malvolio** [graphile/postgraphile#1739]
### Summary

Installing postgraphile with the bun package manager cause the __schema query to fail

### Steps to reproduce

With the following `package.json`
```
{
  "scripts": {
    "db": "postgraphile -c 'postgres:///postgres'"
  },
  "dependencies": {
    "postgraphile": "^4.13.0"
  }
}
```

run the following

```
bun install
bun run db
```

Then click on the graphiql link

### Expected results

Expected the graphiql page to load normally in the browser, including the Docs and Explorer

### Actual results

The Docs and Explorer do not load and there is an error trace in the terminal:

```

Error: Must provide document.
    at devAssert (/Users/john.doe/persrepo/node-phile/node_modules/graphql/jsutils/devAssert.js:12:11)
    at assertValidExecutionArguments (/Users/john.doe/persrepo/node-phile/node_modules/graphql/execution/execute.js:208:40)
    at Object.execute (/Users/john.doe/persrepo/node-phile/node_modules/graphql/execution/execute.js:112:3)
    at /Users/john.doe/persrepo/node-phile/node_modules/postgraphile/build/postgraphile/http/createPostGraphileHttpRequestHandler.js:720:61
    at /Users/john.doe/persrepo/node-phile/node_modules/postgraphile/build/postgraphile/http/createPostGraphileHttpRequestHandler.js:106:20
    at /Users/john.doe/persrepo/node-phile/node_modules/postgraphile/build/postgraphile/withPostGraphileContext.js:172:30
    at func (/Users/john.doe/persrepo/node-phile/node_modules/postgraphile/build/postgraphile/withPostGraphileContext.js:35:26)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /Users/john.doe/persrepo/node-phile/node_modules/postgraphile/build/postgraphile/http/createPostGraphileHttpRequestHandler.js:711:34
    at async Promise.all (index 0)
An unexpected error occurred whilst processing 'graphqlRouteHandler'; this indicates a bug. The connection will be terminated.
TypeError: Cannot set properties of undefined (setting 'statusCode')
    at graphqlRouteHandler (/Users/john.doe/persrepo/node-phile/node_modules/postgraphile/build/postgraphile/http/createPostGraphileHttpRequestHandler.js:812:39)
```

Any query will fail, resulting in the same error.

### Additional context

It’s fine to use bun to *run* postgraphile, but if the package manager function from bun is used at all, postgraphile will no longer work in that directory.  Bizarre.

**Comment by shellscape** [comment]
@Malvolio you'd be better off letting Jared know by filing an issue with Bun. the npm registry is a minefield and there's very little standardization. Bun is going to have to handle the nuances, rather than Postgraphile.

**Comment by jsaunders92** [comment]
I'm having no issues with v5, except for having to change a couple of types to `bun:http`

**Comment by benjie** [comment]
Jarred Sumner says bugs like these should be filed against Bun rather than the project that Bun lacks compatibility with; so I'm going to close this.

> All of these are bugs in Bun. I’m sorry that people are filing issues in your repository instead of Bun’s. Please do send them to file an issue in our repository
> -- https://twitter.com/jarredsumner/status/1700497869160268155

**Comment by jbergstroem** [comment]
Refs: https://github.com/oven-sh/bun/issues/3999
