### ISSUE TITLE
Add Node `id` to interface

### ISSUE THREAD

**Issue by sgrove** [graphile/postgraphile#1740]
In v5 beta, with a schema with something like:

```
CREATE TABLE block (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    chain_id UUID REFERENCES chain(id) ON DELETE CASCADE,
    kind TEXT NOT NULL REFERENCES block_kind(kind),
    camel_case_name TEXT NOT NULL,
    title TEXT NOT NULL,
    description TEXT,
    local_schema TEXT NOT NULL,
    last_output JSON,
    source_code TEXT
);

create index on block (chain_id);
...

COMMENT ON TABLE block IS E'@interface mode:relational type:kind
@type PROMPT references:prompt_block
@type COMPUTE references:compute_block
@type HUGGINGFACE references:hugging_face_block
@type REPLICATE references:replicate_block
@type CALLOUT references:callout_block';
```

I'd expect to be able to just select the node `id` field off the top of the Block interface, but right now it seems like I need an inline fragment (which makes the id field nullable which is a bit of a pain in most places):

```
fragment Test on Block {
  __typename
  description
  ... on Node {
    id
  }
}
```

it'd be nice to be able to do:

```
fragment Test on Block {
  __typename
  description
   id
}
```

Here's a link to the [original discussion](https://discord.com/channels/489127045289476126/498852330754801666/1137829325836669089)

**Comment by benjie** [comment]
Thanks for the report! Fixed in https://github.com/benjie/crystal/pull/454; will go out with next V5 release.
