### ISSUE TITLE
Hooking into every GraphQL Request to collect metrics

### ISSUE THREAD

**Issue by markhalonen** [graphile/postgraphile#1743]
Greetings Benjie,

currently we measure our graphql queries with an express middleware

```js
export function logResponseTime(req: express.Request, res: express.Response, next: express.NextFunction) {
  const startHrTime = process.hrtime()

  res.on('finish', () => {
```

Which works great, except it doesn't capture queries that are executed using `graphql.execute` inside an `makeExtendSchemaPlugin` plugin. Any ideas on how we can hook into every Graphql Execution? Or should we stop hand-rolling a metrics/logging system (which we've liked so far) and use datadog or something?

**Comment by benjie** [comment]
Maybe you can just have your plugins which execute queries inside resolvers call a helper method to do so which hooks up to your system?

**Comment by benjie** [comment]
(Presumably they share the GraphQL context so you can use that.) i can’t think of an alternative that’ll catch the entire execution without monkey patching

**Comment by markhalonen** [comment]
Ok, great thanks, that was my default solution but was just curious if there was some fancy hooks or something, thanks!
