### ISSUE TITLE
PostGraphile rhymes with Pedophile

### ISSUE THREAD

**Issue by majesticApricot** [graphile/postgraphile#1744]
Hi there,

No offence, but the naming is just horrible.

I am even scared to tell my friends that I am using `PostGraphile`. They will ask me: "are you pedophile?".

As much as I love the product I would recommend renaming it to something like "PostGraph"

**Comment by benjie** [comment]
“-phile” is a standard suffix in the English language that applies to a myriad of words, some common examples:

- anglophile - a person who is fond of or greatly admires England or Britain
- audiophile - a person who loves high-fidelity audio
- cinephile - a person who loves films
- technophile - a person who loves technology

I’m sorry that you think so little of your friends that they will confuse “postgra” with “pedo”… As a workaround to this issue, I recommend that you get better friends. No offence 😉

**Comment by supersnager** [comment]
This is the funniest issue I have ever seen :)
