### ISSUE TITLE
can we try to change the User Interface hyper links of the postgraphile while  using it as a library

### ISSUE THREAD

**Issue by prabhanjali11** [graphile/postgraphile#1745]
### Summary

I want to add my documenattaion and the examples for the below part links when they are clicked. Is it possible to change the hyper links in postgraphile

### Additional context

![image](https://github.com/graphile/postgraphile/assets/143176104/863239a3-74c4-4610-966a-19c2f0a0ad8d)

**Comment by benjie** [comment]
Maybe? If so, it'd be with a server hook; e.g. https://www.graphile.org/postgraphile/plugins/#inline-tweaks-via-pluginhook

**Comment by prabhanjali11** [comment]
sure Thank you @benjie
