### ISSUE TITLE
Cleanup PostGIS support

### ISSUE THREAD

**Issue by calebmer** [graphile/postgraphile#277]
There are some errors that occur whenever a user starts PostGraphQL in a schema that has PostGIS artifacts. Most noticeably the `stForce2d` (or whatever it’s called) function. We should probably hide PostGIS functions, or print a warning if we detect them.

This should be a pretty easy fix and would help a lot of people who are trying out the project 👍

**Comment by benjie** [comment]
(Ref #260)

**Comment by benjie** [comment]
PostGIS functions aren't added in v4; and there's the beginnings of work on a postgis plugin here:

https://github.com/singingwolfboy/graphile-build-postgis/tree/wip
