### ISSUE TITLE
Ability to specify CORS endpoints in CLI?

### ISSUE THREAD

**Issue by n1kt0** [graphile/postgraphile#279]
Hi,
is there a possibility to specify CORS endpoints instead of standard "*"?

**Comment by calebmer** [comment]
Not currently, but this would be a fairly simple thing to fix/add :blush:

**Comment by hmaurer** [comment]
What is the status on this with Postgraphile v4 @benjie ?

**Comment by benjie** [comment]
Still an issue; would be happy to receive a PR for it 👍

**Comment by benjie** [comment]
If you want to do this, your best bet currently is to add your own CORS middleware and use the library version in your Express app.
