### ISSUE TITLE
Skipping some default mutations

### ISSUE THREAD

**Issue by shauns** [graphile/postgraphile#289]
In relation to #182 -- is there any way to do this in a more granular fashion? I have a use case where the default behaviour is great, but at other times a manual migration is preferable, and I wouldn't want the default behaviour to leak out.

Happy to contribute if this isn't available and is in scope; could see why this sort of thing is a wontfix -- love the simplicity of the project.

**Comment by calebmer** [comment]
Could you describe more of your use case and which mutations you'd like to enable/disable? You should be able to achieve granular control with the `GRANT` command. For example `GRANT`ing updates to your database role but not deletes.

`GRANT` documentation: https://www.postgresql.org/docs/9.6/static/sql-grant.html

**Comment by shauns** [comment]
Ah -- so leaning on the database a bit more then? I'm still pretty early on with GraphQL, but my use case is that I have a table where I'd like to keep certain columns immutable after creation -- or at least until I have a procedure in place to deal with things changing. I think the pattern I'd like to avoid is exposing a really rich GraphQL schema and ending up with lots of granularity in the app layer. Maybe the answer is white-listing queries.

**Comment by calebmer** [comment]
Yeah, try not granting the update permission for those tables then. PostGraphQL will then be unable to generate a rich update mutation. You can then use the [`CREATE FUNCTION`](https://www.postgresql.org/docs/current/static/sql-createfunction.html) command to create a function with `SECURITY DEFINER` configured to define a mutation that only updates the fields you explicitly allow :blush:

Check out our [forum example tutorial](https://github.com/calebmer/postgraphql/blob/master/examples/forum/TUTORIAL.md), specifically the section on [authentication](https://github.com/calebmer/postgraphql/blob/master/examples/forum/TUTORIAL.md#authentication-and-authorization), to see how we hid passwords in a `forum_example_private.person_account` table and defined functions to be exposed in the GraphQL schema for our clients to use.

**Comment by benjie** [comment]
There's at least two ways of selectively disabling mutations in v4:

1. Smart comments: https://www.graphile.org/postgraphile/smart-comments/#omitting

2. `--no-ignore-rbac` / `ignoreRBAC: false` - and then revoking the relevant method on the table.
