### ISSUE TITLE
Output executed Postgres queries?

### ISSUE THREAD

**Issue by mgallagher** [graphile/postgraphile#310]
Forgive me if there's an answer for this somewhere, but it might be nice to have an option to show the SQL that gets sent to Postgres from PostGraphQL. Any idea how this might be done?

**Comment by benjie** [comment]
We use the `debug` module, so you can run `export DEBUG="postgraphql:*"` (assuming bash shell) before running postgraphql to see various output. For postgres queries specifically you want `DEBUG=postgraphql:postgres`; but `DEBUG=postgraphql:postgres:explain` is also handy.

**Comment by mgallagher** [comment]
Excellent. Thank you @benjie! This works perfectly :)

**Comment by lcjnil** [comment]
@benjie this should be mentioned in document

**Comment by benjie** [comment]
@lcjnil I totally agree. Pull requests are welcome 👍

**Comment by deslee** [comment]
FYI: It should now be `export DEBUG="postgraphile:*"` in case anyone is looking at this issue in 2018.

**Comment by benjie** [comment]
This is now documented here: https://www.graphile.org/postgraphile/debugging/#step-4-viewing-the-generated-sql
