### ISSUE TITLE
Add support for `hstore` extension

### ISSUE THREAD

**Issue by kasbah** [graphile/postgraphile#311]
Just started playing around with postgraphql. It's really neat!

I noticed that [the hstore extension](https://www.postgresql.org/docs/current/static/hstore.html) isn't supported yet and any hstore values are returned as "[object Object]" strings. It's not biggie for me personally but thought I would propose it as an enhancement anyway.

**Comment by benjie** [comment]
v4.0.0-rc4 will contain hstore support
