### ISSUE TITLE
Trigger functions should not be added to GraphQL schema

### ISSUE THREAD

**Issue by benjie** [graphile/postgraphile#355]

**Comment by EyMaddis** [comment]
As a workaround, it should be possible to great a second database schema that PostGraphQL does not have access to and put the trigger functions there.

**Comment by calebmer** [comment]
That’s what I generally like to do as well @EyMaddis. I generally call it `private` or something similar. However, it shouldn’t be hard to stop trigger functions from showing up. Out of curiosity what is the return type of trigger functions when they show up in GraphQL? 😊

**Comment by benjie** [comment]
Pass, I just noticed one trigger accidentally slipped through to the wrong schema so thought I'd make a note it oughtn't appear :)

**Comment by benjie** [comment]
Here's the v4 fix for this, if anyone feels like applying this to v3 please do: https://github.com/postgraphql/graphql-build/commit/1d0760781e21594a465d01b3fb801918b50e83d1

**Comment by stlbucket** [comment]
so if i want to try this out, should i be using:

https://www.npmjs.com/package/postgraphql-build

**Comment by benjie** [comment]
If you only need the schema then you can use that package; but I'd wait for the v4 alpha to be released soon - see #506

**Comment by benjie** [comment]
Triggers are not added to GraphQL in v4 👍
