### ISSUE TITLE
Add note to the README explaining `?ssl=1` connection string requirement

### ISSUE THREAD

**Issue by pyros2097** [graphile/postgraphile#357]
I'm trying to connect to my database hosted by https://aiven.io/ but getting some configuration error do you know what it could be
```
web_1       | > Using "webpack" config function defined in next.config.js.
web_1       | error: no pg_hba.conf entry for host "14.142.150.34", user "avnadmin", database "defaultdb", SSL off
web_1       |     at Connection.parseE (/usr/src/app/node_modules/pg/lib/connection.js:554:1
```
Its connecting fine using psql cli. So why isn't postgraphql connecting? Don't you set ssl to true? That seems to be the problem.

**Comment by benjie** [comment]
@pyros2097 The error states "SSL off" but it looks like your connection URL wants SSL; it seems that the postgres query string library doesn't support `sslmode=require` instead requiring `ssl=1`; my connection string looks like:

`postgresql://username:password@example.com/dbname?sslmode=require&ssl=1`

**Comment by pyros2097** [comment]
Yes it worked thanks @benjie :) :+1:

**Comment by benjie** [comment]
Reopening as a task.

**Comment by pencilcheck** [comment]
Starting to getting this error, with the latest version of postgraphql weird. I'm using heroku and I can't change DATABASE_URL as it is audo-generated and it is locked. I wonder if there is an easier way to do this via more command line approach. Does postgraphql provide any flag like ssl=true?

**Comment by benjie** [comment]
Something like this in your Procfile should work:

web: DATABASE_URL=“$DATABASE_URL?ssl=1” postgraphile ...

Failing that a bash script that does the same.

**Comment by pencilcheck** [comment]
I ended up doing similar things, by doing something like "${DATABASE_URL-default}?ssl=1" in the parameter
