### ISSUE TITLE
Postgres `numeric` overflowing pgql js `number`

### ISSUE THREAD

**Issue by aabluedragon** [graphile/postgraphile#358]
Currently postgraphql "treats" `numeric` as javascript's `number`.

[PG Docs](https://www.postgresql.org/docs/9.6/static/datatype-numeric.html) mention the following storage size for numeric:
Storage size: variable (User specified precision exact)
Range: up to 131072 digits before the decimal point; up to 16383 digits after the decimal point

JS number type seems to have a more fixed length (53 bits?).

Consider having a string based solution when serializing to JSON.

Similar to #302

**Comment by calebmer** [comment]
Yeah. This is really unfortunate given we just made a breaking change for big integers 😣

For now, it’s probably a good idea to specify which number type you specifically want 👍

**Comment by benjie** [comment]
v4 treats numeric as a string (specifically a `BigFloat`); documented here:

https://www.graphile.org/postgraphile/v3-migration/#very-large-numbers

This was a breaking change.
