### ISSUE TITLE
💅 Logo wanted 🙏

### ISSUE THREAD

**Issue by benjie** [graphile/postgraphile#394]
Hey lovely community, we need a logo! Can anyone help us out? I propose that requirements at this stage are:

- Free (as in beer and speech)
- Licensed in a way compatible with the [PostGraphQL license](https://github.com/calebmer/postgraphql/blob/master/LICENSE) that also allows us to modify it, scale it, redistribute it, print it on T-Shirts to sell, etc (I'm not sure how this would work best - Creative Commons maybe?)
- Works well as an avatar (e.g. on GitHub, Twitter, etc)

I'd like to keep this issue open for a few weeks to let people make alternative submissions and maybe iterate upon existing ones; at the end I think @calebmer will pick the winning logo, but he will likely be influenced by your 👍  votes.

Please use the reactions in this way:

- 👍  I vote for this logo (you can vote for as many logos as you want)
- ❤️  Thanks for the submission, we really appreciate the effort you've put in
- 👎  I do NOT want to see this, let's **keep it positive**!
- 😕  If you think the logo is inappropriate in some way (e.g. violates a trademark, is rude, etc) - if you use this please add a (very polite!) explanation in the comments

Thanks so much everyone!

**Comment by 5argon** [comment]
Hi, I tried create one based on GraphQL's logo. Let me know if you are interested in it.
<img width="337" alt="screenshot 2017-03-17 13 12 27" src="https://cloud.githubusercontent.com/assets/5653276/24031121/66a08c24-0b13-11e7-995b-ebebd7863913.png">

**Comment by benjie** [comment]
@5argon Thanks!

I'd love to have more community participation so I've added details to the initial post on voting/etc.

@calebmer When do you think the logo "competition" should close?

**Comment by theodorosploumis** [comment]
I could create a logo if you like or at least make this one more elegant. It seems to have some color combination issues.

Thanks.

**Comment by benjie** [comment]
@theodorosploumis More choice is always good, another submission would be welcome 👍  There was a logo from @valorize submitted on gitter also:

https://gitter.im/calebmer/postgraphql?at=58d027475917e26076b67fec

**Comment by valorize** [comment]
I could also image something like  the first half of a database symbol (http://iact.iact.netdna-cdn.com/wp-content/uploads/2014/06/relational-database-460x200.jpg), than postgraphql and then the second half of the graphql symbol

**Comment by theodorosploumis** [comment]
Here are my proposals. I will add them on separate issues to allow voting/hands etc.

I like much No 1a! All of theme are based (except from the PostgreSQL and GraphQL official logos) on "reflection", connection and are of square shape.

Notice that using the official GraphQL logo color (`#e535ab`) cannot play together with the PostgreSQL color (`#336791`) due to color conflicts. Thus I did not propose any logo with the combination of the 2.

**Comment by theodorosploumis** [comment]
![logo_tplcom_1](https://cloud.githubusercontent.com/assets/1315321/24223000/e51e9904-0f5c-11e7-9725-c77632335039.png)

**Comment by theodorosploumis** [comment]
![logo_tplcom_2](https://cloud.githubusercontent.com/assets/1315321/24223001/e520bcd4-0f5c-11e7-9340-5eb1e4d92b75.png)

**Comment by benjie** [comment]
I'm a little concerned about using PostgreSQL's trademark in our logo (same for GraphQL).

**Comment by theodorosploumis** [comment]
This is a good point to consider.

The PosgreSQL logo can be reused under CC BY-SA 2.5 (see https://www.postgresql.org/community/propaganda/) and GraphQL under BSD (see https://commons.wikimedia.org/wiki/File:GraphQL_Logo.svg).

My designs only affect the PostgreSQL logo the rest do not match the GraphQL in any way. We could have a custom "elephant" for the PostgreSQL part but this would not promote PostgreSQL and it would be like "overriding" the other logo.

In any case we could ask the Postgres maintainers if they have a problem.

**Comment by EyMaddis** [comment]
Maybe a graph structure could be colored such that the letters PG are formed. (just an idea)

**Comment by theodorosploumis** [comment]
Here is a proposal without any logo conflicts. Just the initial letters and the structure concept.

![proposal_no3](https://cloud.githubusercontent.com/assets/1315321/24266786/bd063292-1010-11e7-81f9-1a8babad17f9.png)

**Comment by benjie** [comment]
I really like these! What would it look like if 3c was a regular hexagon?

**Comment by theodorosploumis** [comment]
![hexagon_logo](https://cloud.githubusercontent.com/assets/1315321/24268323/12935e7e-1016-11e7-9f2d-9f1085bc0444.png)
Somehow like this.

**Comment by theodorosploumis** [comment]
And here are some new logos, based on the same concept. I prefer No 4b mostly.

![proposals_v4](https://cloud.githubusercontent.com/assets/1315321/24322108/e2ecb552-1165-11e7-9f21-1b6d9d27f73f.png)

**Comment by calebmer** [comment]
Thank you so much everyone for your proposals and collaboration!

@theodorosploumis I’m liking the look of 3a. What if we did the top half blue and the bottom half pink instead of a checker box? Also, what if we explore some other fonts? Finally, what if the four corners were not squares, but resembled puzzle pieces? Hammering in the metaphor that everything just fits together 😉

@5argon I like your proposal as another possible direction. What does everyone think about trying to take the GraphQL hexagon shape and rearranging it in a way that it looks like the Postgres ears 😊. Not sure how far that idea can go.

**Comment by calebmer** [comment]
I just moved PostGraphQL to its own GitHub organization (this is why I wanted a logo 😊). In order to have some kind of image I set the avatar to an elephant emoji from http://emojione.com/. I _do not_ like this as a long term solution. I just wanted some image to represent the organization while we work on a more formal logo here 😊

**Comment by theodorosploumis** [comment]
Here are some new combinations. Puzzle doesn't seem to work well at least for small size logo. And that because of the letters included. Some other fonts work better but the major issue is the color combination (that causes color issues).

![proposal_v5](https://cloud.githubusercontent.com/assets/1315321/24427917/5636656a-1415-11e7-9943-4d83c5293417.png)

**Comment by theodorosploumis** [comment]
![proposal_v6](https://cloud.githubusercontent.com/assets/1315321/24427957/7c7913b2-1415-11e7-8923-8cae7aabc0b7.png)

**Comment by theodorosploumis** [comment]
![proposal_v7](https://cloud.githubusercontent.com/assets/1315321/24427964/85211d52-1415-11e7-8c86-34320354c00e.png)

**Comment by theodorosploumis** [comment]
![proposal_v8](https://cloud.githubusercontent.com/assets/1315321/24427970/8c6a6b18-1415-11e7-8a40-0d4993c16bd3.png)

**Comment by valorize** [comment]
My favorites so far are: 3a/5a, 4c, 7b.

**Comment by valorize** [comment]
I've taken the liberty of taking @theodorosploumis glyphs and combined them to: 
![postgraphql](https://cloud.githubusercontent.com/assets/22564188/24447941/e7c900b6-1472-11e7-90c4-4a4073d703f6.jpg)

**Comment by benjie** [comment]
I think my favourite at the moment is 5a, but I also really like @5argon's updated image.

**Comment by niksubramanian** [comment]
My humble attempt.
![postgraphql-ex1](https://cloud.githubusercontent.com/assets/17026660/24526352/24e4a73a-159e-11e7-82ec-eaa9b05b2d3e.png)

**Comment by EyMaddis** [comment]
@niksubramanian The pattern is too small on the elephant head, IMHO. But overall I really like it, especially the typography is nice.

**Comment by niksubramanian** [comment]
And a final one, inspired by origami:
![postgraphql-ex2](https://cloud.githubusercontent.com/assets/17026660/24527497/abbc3cf6-15a2-11e7-849c-a9dddd9934ff.png)

**Comment by niksubramanian** [comment]
thanks for the comment @EyMaddis - agreed! Not sure I still have the courage to redo it completely though ;)

**Comment by kimballmortensen** [comment]
I'm new to GitHub but am a designer who's trying to get more into UI / tech brand identity projects.

Here's my attempt... Would love any feedback!

![postgraphql-logosend8](https://cloud.githubusercontent.com/assets/12931577/24572728/97265420-1638-11e7-8ab9-c083c343073a.jpg)

**Comment by valorize** [comment]
@kimballmortensen could you make the elephant blue? Maybe with something around #0067b9?

**Comment by calebmer** [comment]
I really love the colors in the second one from @niksubramanian. That purple looks great 😊

Let’s leave this open for another week and then we can choose which logo we want to use.

**Comment by angelosarto** [comment]
@niksubramanian This looks really good.  I also tried it on a black background and it looks really nice on a dark background IMO.

The only suggestion I would have here would be to see if you could reduce the number of colors in the elephant head, the head may need less colors for simplification.  What got me thinking of this is what would you suggest for use in something like the Favicon.ico - Maybe just the elephant head alone, and how would this scale down to a browser tab sized icon?

I think the concept is great, but if you haven't tried it yet - check it in a few different contexts:
what does it look like in grayscale?  On a black background?  on top of a lightly textured background, etc.   

Strong logos generally look at least ok in all of these contexts: e.g. FedEx, GE (meatball), UPS, etc.

  (Maybe the ear on the left {which would be the elephant's right ear...} could be the same color as the other one?)

**Comment by kimballmortensen** [comment]
Hey gents,

I implemented the blue as requested. I also tried to make the elephant look a little "tuskier" like the original postgres ele. Here's one: 
![postgraphql-newsend2](https://cloud.githubusercontent.com/assets/12931577/24719364/b404eab8-19f6-11e7-86ea-ba47a0e441cf.jpg)

**Comment by kimballmortensen** [comment]
I got some feedback that perhaps for a logo a more minimal approach might be more effective. The last version does seem a little busy.. This lead to the following concepts: (I'll put them in separate posts so I can better gauge which concept more people prefer via Likes)

![postgraphql-newsend3](https://cloud.githubusercontent.com/assets/12931577/24719444/04f7dfa2-19f7-11e7-883b-4c51dbd08fe1.jpg)

**Comment by kimballmortensen** [comment]
This was an early version, but I feel like it's worth posting to gauge response...

![postgraphql-logosend](https://cloud.githubusercontent.com/assets/12931577/24719485/31233b12-19f7-11e7-998f-e98ae305e9e9.jpg)

**Comment by kimballmortensen** [comment]
This last one seems like more of an illustration, but I'll post it anyway incase ppl happen to love it. ;)
![postgraphql-logosend3](https://cloud.githubusercontent.com/assets/12931577/24719596/807a4548-19f7-11e7-8c36-ea8e78859980.jpg)

**Comment by theodorosploumis** [comment]
Just a notice here that we are supposed not to use the original logos of PostgreSQL and GraphQL, see  https://github.com/postgraphql/postgraphql/issues/394#issuecomment-288671867 and after that.

**Comment by valorize** [comment]
Why shouldn't we? At least the BSD license allows to reuse and modify the logo as long as the initial copyright notice is left intact, right?

**Comment by 5argon** [comment]
I like the one that an elephant that looks like a pokeball. If you combined it with typography like the one that POST is in bold it might looks really good.

**Comment by kimballmortensen** [comment]
Typically copyright laws allow reuse as long as the original is modified at least 20%. I think this argument could be made for either logo. That said, I'm happy to make more changes if needed.

Thanks for the feedback!

**Comment by benjie** [comment]
I really like this one: https://github.com/postgraphql/postgraphql/issues/394#issuecomment-291944152

An issue you may not have considered with https://github.com/postgraphql/postgraphql/issues/394#issuecomment-291944526 and similar designs is they may pose an issue for the visually impaired, e.g. sticking it through http://www.color-blindness.com/coblis-color-blindness-simulator/ gives:
  
<img width="799" alt="screenshot 2017-04-08 09 47 29" src="https://cloud.githubusercontent.com/assets/129910/24827410/dd6112d2-1c40-11e7-9cff-1553a2542464.png">

I think this may be okay since there's still some decent contrast, but I'm no expert on this subject. A way to improve this may be to surround the overlay logo with a little whitespace or black borders? Either way, I still prefer the first one I mentioned 👍 

(And yes, diverging from the official GraphQL and PostgreSQL logos would be preferable, but we can totally use their essence.)

**Comment by benjie** [comment]
Hello everyone, I'm so sorry for the lack of comms on this - it's been a hectic couple of months!

Caleb and I have narrowed it down to the following two logos (which are also similar in popularity ratings); please can you vote with a 👍  for the logo you prefer? If you like both and can't decide, feel free to vote for both of them!

Without further ado, in order that they were posted:

**Comment by benjie** [comment]
![](https://cloud.githubusercontent.com/assets/17026660/24527497/abbc3cf6-15a2-11e7-849c-a9dddd9934ff.png)

by @niksubramanian [original comment](https://github.com/postgraphql/postgraphql/issues/394#issuecomment-290553957)

**Comment by benjie** [comment]
![](https://cloud.githubusercontent.com/assets/12931577/24719444/04f7dfa2-19f7-11e7-883b-4c51dbd08fe1.jpg)

by @kimballmortensen [original comment](https://github.com/postgraphql/postgraphql/issues/394#issuecomment-291944152)

**Comment by benjie** [comment]
I'd just like to take this opportunity to thank each and every person who has posted a logo idea and participated in this thread - it warms my heart to see so much enthusiasm from the community and such an outpouring of talent!

# 🤘  You are all awesome! 🙏

**Comment by benjie** [comment]
Congratulations @niksubramanian - yours was the favoured logo! Please could you get in touch with me so we can organise its adoption? You can contact me via my GH username at jemjie.com

Thanks!
