### ISSUE TITLE
It's impossible to use the same name for functions as generated names from PostGraphQL

### ISSUE THREAD

**Issue by EyMaddis** [graphile/postgraphile#402]
This might not at first sound like a bug, but the following error occurs if I have a `create-user` function defined in Postgres while **not granting any CREATE permission**.
The PostgraphQL user only has `SELECT` permission (and should have `UPDATE` later on).

```
21/03/2017 19:38:09Error: Naming conflict when building object. Cannot have two definitions for property 'createUser'.
21/03/2017 19:38:09    at /srv/webservice/node_modules/postgraphql/build/graphql/utils/buildObject.js:53:19
21/03/2017 19:38:09    at Array.forEach (native)
21/03/2017 19:38:09    at /srv/webservice/node_modules/postgraphql/build/graphql/utils/buildObject.js:39:58
21/03/2017 19:38:09    at Array.forEach (native)
21/03/2017 19:38:09    at Object.buildObject (/srv/webservice/node_modules/postgraphql/build/graphql/utils/buildObject.js:39:14)
21/03/2017 19:38:09    at fields (/srv/webservice/node_modules/postgraphql/build/graphql/schema/getMutationGqlType.js:37:46)
21/03/2017 19:38:09    at resolveThunk (/srv/webservice/node_modules/graphql/type/definition.js:162:40)
21/03/2017 19:38:09    at defineFieldMap (/srv/webservice/node_modules/graphql/type/definition.js:320:18)
21/03/2017 19:38:09    at GraphQLObjectType.getFields (/srv/webservice/node_modules/graphql/type/definition.js:285:44)
21/03/2017 19:38:09    at /srv/webservice/node_modules/graphql/type/schema.js:207:27
```

**Comment by calebmer** [comment]
Could you make a quick reproduction for this error? Also, does it happen with `disableDefaultMutations`? This definitely should not happen!

**Comment by EyMaddis** [comment]
@calebmer 
It does not happen with `disableDefaultMutations`. 

Right now I seem to have a way larger issue. PostGraphQL seems to generate the mutation anyway, even tough it shouldn't have any permissions.

I did the following:
1. create new database
2.
```
CREATE ROLE pgql WITH login nosuperuser;
CREATE SCHEMA private;

--- A first table
create table private.foo (
    id serial not null primary key,
    something text
);

GRANT SELECT ON TABLE private.foo TO pgql;
```
Please note that I created these as another user, so the owner of the table is *not* `pgql`.

3. changed the login user for PostGraphQL to `pgql`, but it still generates all functions for `foo`.

I then see the mutations for `foo`, e.g. `createFoo()`, even after running `REVOKE ALL ON SCHEMA private FROM pgql;` and verifying the grants via `SELECT * FROM view_all_grants WHERE subject = 'pgql' and public = false;`, using this [view](https://www.postgresql.org/message-id/20120701192005.05b83a62@james.intern).

The error occurs above occurs when running
```
create or replace function private.create_foo() returns private.foo as $$
select *
    from private.foo
$$ language sql volatile;
--- in theory this would also need GRANT EXECUTE ON FUNCTION private.create_foo() TO pgql;
```

I am really perplexed why this occurs, everything is set up from scratch and running 3.1.0 (latest on master) using the `dev` script. I don't know what I could do differently...?

**Comment by calebmer** [comment]
This is our current method of detecting whether or not something is insertable/updatable/deletable: https://github.com/postgraphql/postgraphql/blob/722eb0d01c8dff87daeaeec844be67211a7290dd/resources/introspection-query.sql#L93-L95

What are the values of these columns in your introspection? I’m trying to find out where the error lies. If it’s in PostGraphQL, our detection query, or in Postgres.

**Comment by EyMaddis** [comment]
@calebmer the value is 00011100

**Comment by benjie** [comment]
In v4 you can use smart comments to omit the built in mutation (e.g. `comment on users is '@omit create';`) then you can use the name that would have been used by the built in mutation 👍 

As for doing this automatically, that's a fair undertaking. Maybe start here: https://stackoverflow.com/a/23461690/141284
