### ISSUE TITLE
Blacklist/wishlist

### ISSUE THREAD

**Issue by langpavel** [graphile/postgraphile#411]
I know, you should care about permissions in postgres directly. But introducing blacklists can prevent some issues with conflicts. It should be good to report this in log as notice level in development but definitely this can workaround some human talks.

It can open next level-mapping of generated name to customized one. This can be used as transition thing too.

**Comment by benjie** [comment]
Hi @langpavel, what is it you wish to blacklist - is it the `role`?

**Comment by langpavel** [comment]
Hi @benjie
I want blacklist (or whitelist) every object which can be reflected by postgraphql.
There are some hardly resolvable issues with name clashing which can be resolved only by changing database.

**Comment by benjie** [comment]
I'd recommend using schemas to avoid that issue, however you could do it by hacking the introspection query:

https://github.com/postgraphql/postgraphql/blob/1145689054f7f7a6a5542ec34aa3827af3bc572a/resources/introspection-query.sql

Alternatively you could doctor the PgCatalog and feed it back in, based on the work in this PR:

https://github.com/postgraphql/postgraphql/pull/306

**Comment by calebmer** [comment]
I didn’t think about manually mutating `PgCatalog`, or creating your own with a custom introspection query. That’s an interesting and powerful idea.

@langpavel if you try that please let us know how it turns out 👍

**Comment by langpavel** [comment]
Actually I tried something similar some weeks ago but it is easier to filter out introspection query because of too tight internal logic.

**Comment by calebmer** [comment]
Does modifying the introspection query and/or its results work for you?

**Comment by benjie** [comment]
In PostGraphQL v4 you'll be able to replace the introspection plugin with your own:

https://github.com/postgraphql/graphql-build/blob/master/packages/graphql-build-pg/src/plugins/PgIntrospectionPlugin.js

**Comment by benjie** [comment]
You can now use the `@omit` smart comment to blacklist tables / columns / functions / etc: https://www.graphile.org/postgraphile/smart-comments/
