### ISSUE TITLE
Feature Discussion: Advanced Query Predicates in `condition` input.

### ISSUE THREAD

**Issue by danscan** [graphile/postgraphile#422]
I thought it might be nice to have support for "advanced" predicates in the `condition` query arg.  For example, `ilike`, `>`, `<`, `not`, etc.

In a pet project a while back I did something like this (_though not with Postgres, and not as nice as this project_ 😄 ), which [can be seen here](https://github.com/danscan/datomic-graphql/blob/master/src/graphQLSchema/utils/getQueryInputArgsForSchemaType.js#L79-L90).  This also supported chaining conditions with advanced predicates via `and` or `or`.

I like the simplicity of the current schema reflection in postgraphql, so perhaps there could be a way to opt in to "advanced predicates" on a per-type basis via the Postgres schema?

Maybe there's a more sensical and generic way to specify query predicates via Postgres functions?

Any thoughts?

**Comment by danscan** [comment]
Hmmm, after more playing, I think that adding the `condition` argument to query fields for set-returning functions could go a long way, and would be much simpler.

**Comment by benjie** [comment]
See also #47, #324 and #337

**Comment by calebmer** [comment]
This is definitely something we want! We are just waiting for a really good proposal at the moment 😊

In the meantime we do allow you to define whatever query you want using Postgres procedures: https://github.com/postgraphql/postgraphql/blob/master/docs/advanced-queries.md

**Comment by benjie** [comment]
This is possible via a plugin to PostGraphQL v4 👍

**Comment by sam123evers** [comment]
Hey guys, 
is is possible to pass a variable to the conditions input in order to construct dynamic queries?  Or am I just trying to create dynamic queries the wrong way?

**Comment by benjie** [comment]
Yes, you can pass variables anywhere you can pass a value, see the Variables section of the GraphQL manual: http://graphql.org/learn/queries/

**Comment by benjie** [comment]
Closing this since it's possible via @mattbretl's plugin; see:

https://github.com/graphile/postgraphile/issues/47#issuecomment-413245026
