### ISSUE TITLE
Surface omitted functions

### ISSUE THREAD

**Issue by brysgo** [graphile/postgraphile#465]
Found out the hard way that overloaded functions are ignored. Would love to have some way to see the objects and functions omitted along with the reason.

Forgive me if there is a way I overlooked.

**Comment by brysgo** [comment]
On my phone, on subway, referenced the wrong issue, will fix later.

**Comment by ikari-pl** [comment]
I also have a function that gets ignored that returns a inline-defined `TABLE(id int, data text...)` rather than an existing table model or a simple field. Is this supported? 
If a function is deliberately ignored by the library, it should be logged as a warning...

**Comment by benjie** [comment]
Yes, currently dynamic types are not supported. We recently added a small amount of documentation around this:

https://www.graphile.org/postgraphile/custom-queries/

https://github.com/postgraphql/postgraphql/blob/master/TROUBLESHOOTING.md#stored-procedure--function-not-appearing

---

A PR that adds a warning when a function isn't used would be considered.

Here's the code for computed columns:

https://github.com/graphile/graphile-build/blob/062239f3746bc23bb77879b388e8942ce2fe82b6/packages/graphile-build-pg/src/plugins/PgComputedColumnsPlugin.js#L46-L80

For custom queries:

https://github.com/graphile/graphile-build/blob/062239f3746bc23bb77879b388e8942ce2fe82b6/packages/graphile-build-pg/src/plugins/PgQueryProceduresPlugin.js#L22-L61

And for custom mutations:

https://github.com/graphile/graphile-build/blob/062239f3746bc23bb77879b388e8942ce2fe82b6/packages/graphile-build-pg/src/plugins/PgMutationProceduresPlugin.js#L20-L47

The `return memo;` clauses are similar to the `filter` clauses in that they do not add the function to the schema.

**Comment by benjie** [comment]
We now have `Failed to add function` warnings; hopefully that will help 👍 

https://github.com/graphile/graphile-build/blob/0fce134cac219d196ec97ead668ddbef7140b66c/packages/graphile-build-pg/src/plugins/PgQueryProceduresPlugin.js#L85-L95
