### ISSUE TITLE
Custom Data Type issue

### ISSUE THREAD

**Issue by SeenaLibin** [graphile/postgraphile#490]
Hi,
I am currently using a data with a view name "telenetstar". Also i have a custom data type with same name. When I am trying to up postgraphql on my db its showing the following issue

Error: Schema must contain unique named types but contains multiple types named "Telenetstar".

Is it due to the above problem. If yes can you give me a solution.  Here i am not able to modify vie name or dtat type name. Is there any technique in postgraphql to accept it as such?

**Comment by benjie** [comment]
@SeenaLibin If you need both types in your schema there's not much that can be done right now; but if you don't then you could move one of the types to a different schema?

**Comment by SeenaLibin** [comment]
Hi benjie,
Actually here we are using composite type concept. For a table row we are using the composite type as its data type. And we are in situation that  we cannot change its datatype.

**Comment by benjie** [comment]
@SeenaLibin PostGraphQL v4 will allow you to provide your own inflection engine which might solve this issue. There's still quite a bit to be done before it can be released, just letting you know. (Though you can probably use the GraphQL schema parts of it now...)

If you could provide a minimal schema to replicate your issue that would be excellent to help ensure issues like this are solvable in the new system.

**Comment by benjie** [comment]
v4 inflectors are now exposed, I've not documented them properly yet, but you can use them: 

https://github.com/postgraphql/postgraphql/pull/506#issuecomment-328831456

**Comment by benjie** [comment]
Here's an example of overriding inflectors:

https://github.com/graphile-contrib/pg-simplify-inflector
