### ISSUE TITLE
set pg client application_name parameter for pg_stat_activity and CSV log entries

### ISSUE THREAD

**Issue by rngadam** [graphile/postgraphile#499]
When using postgresql logging, application_name is useful to differentiate where the query originates from (interactive clients (pgadmin) or applications).

For Postgraphql, at the moment, application_name is set to an empty string ''

As per https://github.com/brianc/node-postgres/wiki/Client

```
string application_name:
default value: process.env.PGAPPNAME
name displayed in the pg_stat_activity view and included in CSV log entries
```

This seems to require a single change in postgraphql/cli.js:

```
var pgConfig = Object.assign({application_name: 'postgraphql'},
```

better yet would be to add additional information (graphql vs graphiql)

**Comment by jmealo** [comment]
:+1: I typically use the `application_name` GUC to identify the "web app user" executing a query and/or the request id/correlation id if "end-to-end" logging is present.

**Comment by benjie** [comment]
This is possible (and easy to achieve) via `pgSettings`; I'm going to close this for now.

https://www.graphile.org/postgraphile/usage-library/#pgsettings-function
