### ISSUE TITLE
PostgraphQL graphiql does not pick up drop table actions

### ISSUE THREAD

**Issue by johnbendi** [graphile/postgraphile#502]
I expected that postgraphql should automatically restart and remove the relevant queries and mutations when a `drop table` command is issued but that does not happen. Is this normal behavior?

**Comment by benjie** [comment]
@johnbendi Are you using the `--watch` option? If not then it will only perform introspection when the system is first ran and that schema will be permanent until you restart the process.

If you  are using `--watch` then yes, this is a bug.

**Comment by johnbendi** [comment]
@benjie Yes I'm using the -w option.

**Comment by benjie** [comment]
I'll look into the schema watching functions; it's not something I use but we need it for PostGraphQL 4 so I need to familiarise myself with it.

**Comment by benjie** [comment]
Hi @johnbendi, I've had a quick look through the relevant code - the following SQL is executed to add watching to the database:

https://github.com/postgraphql/postgraphql/blob/396bca42a927f598b5cbab176fd53a012600f60f/resources/watch-fixtures.sql

Please can you check the `postgraphql_watch` schema exists in your database? If not it might be that we don't have permissions to install it, though if that is the case then we should be outputting a warning:

https://github.com/postgraphql/postgraphql/blob/6b3374baa974d8efd110970e4bd9431b8b3771f3/src/postgraphql/watch/watchPgSchemas.ts#L43-L47

Do other DDL commands work (such as adding a column) - is dropping a table the only thing that doesn't work?

**Comment by benjie** [comment]
Can confirm there's an issue with the watch fixtures that does not pick up certain drop actions. I've fixed this in V4 but cannot do so in the same way in V3 because it's a breaking change:

https://github.com/postgraphql/graphql-build/commit/3656b1990bc9707ad5cdb122c09759f4dac03a87

**Comment by johnbendi** [comment]
Sorry for the long silence. I have been away for a while. Will test the changes and revert asap. Thanks for checking this issue out.

**Comment by hmaurer** [comment]
What is the status on this? It seems to me that it could be closed. @benjie ?

**Comment by benjie** [comment]
This is fixed in v4; v3 will not be receiving the fix as it may cause issues (it’s a significant change)
