### ISSUE TITLE
Contributing to the TROUBLESHOOTING

### ISSUE THREAD

**Issue by ppKrauss** [graphile/postgraphile#505]
This issue is a guide and a place to discuss the contents of the [TROUBLESHOOTING.md](https://github.com/postgraphql/postgraphql/blob/master/TROUBLESHOOTING.md). 

There are only three rules (best practices) to add new items:

1. Edit it **formating** as described below, with "subject group section" and "problem subsection".

2. **Cite the "motivation"** from popular or frequent problem-report, at [postgraphql/issues](https://github.com/postgraphql/postgraphql/issues) or [stackoverflow](https://stackoverflow.com/search?q=postgraphql). If there are no documented motivation, perhaps not need to add a TROUBLESHOOTING new item. 

3. To be concise: describe the problem with precision, and solution details when it it is short and oportune (the  solution must be a **link** when is to long).

Format:
```
----

## subject group X
...

### problem Y1 at subject X
...

Details at ...

### problem Y2 at subject X
...

Details at ...
```

**Comment by benjie** [comment]
4. Use neutral and respectful language, e.g. "You may sometimes meet an issue with ..." rather than "You may sometimes meet a really annoying issue with ..."

**Comment by benjie** [comment]
Thanks for this @ppKrauss; since there's not been any more comments here I've moved the instructions to the TROUBLESHOOTING file itself, as a comment.
