### ISSUE TITLE
unable to save UUID[]

### ISSUE THREAD

**Issue by graphqlgirl** [graphile/postgraphile#516]
I'm not sure if this is postgraphql related or graphql related but I'm having trouble with the auto generated mutations when saving arrays of UUIDs

for example 

mutation {
  createPost(
    input: {
      user_ids: ["9b6453br-e235-4edb-bbf9-97495d9a42a1"]
   }
 )
}

will give the error 

"message": "column \"user_ids\" is of type uuid[] but expression is of type text[]"

**Comment by benjie** [comment]
I think this is fixed in the V4 alpha, can you confirm?

npm install postgraphql@next

**Comment by bruceblay** [comment]
Ran into this issue today.  Tested the alpha and it did the trick.
