### ISSUE TITLE
[Question] Custom business logic and M:N relations

### ISSUE THREAD

**Issue by mcongy** [graphile/postgraphile#521]
Hello,

Sorry if this has already been answered, I tried to look into other issues/docs but I wasn't sure if I understand it right.

**1. How do I implement custom business logic?** 
I want to use postgraphQL as express middleware. How would I (for example) send an email when new user is added to the 'user' table? How would I implement custom validation logic?

**2. What is the preferred way to implement M:N relations (many-to-many)?**
I've seen https://github.com/postgraphql/postgraphql/issues/91 
But does this solve the problem entirely? What if I want to make this kind of queries:

```
{
  student {
    subject {
      id,
      content
    }
  }
}
```

and

```
{
  subject {
    student {
      id,
      content
    }
  }
}
```

I guess this won't be possible using the method you showed in that issue.

I think that answers to both of the questions should be added to the docs or project README.

I really like this project, and I definitely want to use it (even try v4 alpha), but if I wouldn't be able to solve these common use-cases reasonably well, I would have to stick with other solution.

Anyway, thanks for the awesome help on this project, and I'm looking forward to the more customizable v4!

PS. I've checked out the `graphql-build` project, but considering the fact I'm new to the postgraphQL, I didn't understand the docs/readme very well. Would be nice if you could be more clear on some of the subjects. I can't even ask concrete questions, since I didn't even get the basics of it :)

**Comment by benjie** [comment]
Yeah, graphql-build was only thought up about 4 weeks ago - the documentation is severely lacking and one of the things I want to get sorted before I can release PostGraphQL v4, but writing good documentation takes significant time!

Regarding your question, based off my comment in #91 you can just add the reciprocal function, e.g.

```sql
create function "post_authorsByPostId"(p post)
returns setof author as $$
  select author.*
  from author
  inner join post_author
  on (post_author.author_id = author.id)
  where post_author.post_id = p.id;
$$ language sql stable;

create function "authors_postsByAuthorId"(a author)
returns setof post as $$
  select post.*
  from post
  inner join post_author
  on (post_author.post_id = post.id)
  where post_author.author_id = a.id;
$$ language sql stable;
```

Pseudocode, untested.

**Comment by Chuckatron** [comment]
Hi @benjie Thanks for your work on this library, it is very much appreciated. I'm just getting started with Node/Express/GraphQL and this library is easing the path greatly!

I wondered if you had any thoughts on the first question in OP's post? I'm in a similar position, except I want to send a websocket message to all clients when receiving certain requests, such as the creation  of a user. I've got as far as identifying I need to use Postgraphile as Express middleware, which I have got working. However, despite much search of docs and issues, I am lost when it comes to somehow calling custom functions upon the receipt or processing of a particular request.

Are you able to point me in the right direction please?

**Comment by benjie** [comment]
I somehow missed your comment @Chuckatron, I'm sorry about that. I would achieve your request with database triggers, probably something that triggers a `NOTIFY` which one of my node-postgres clients can `LISTEN` for. I'd achieve @mcongy's emails task with a work queue; like this:

https://github.com/graphile/examples/blob/7b9a0aa8e7fc300561014b0e61898c429b5df2d8/db/400_users.sql#L128-L131
