### ISSUE TITLE
Have poolOrConfig throw if invalid

### ISSUE THREAD

**Issue by benjie** [graphile/postgraphile#552]
In the final fallback `poolOrConfig || {}`:

https://github.com/postgraphql/postgraphql/blob/233f55c53f8c982cb566b48b63e0fa5bcc7ed1fd/src/postgraphql/postgraphql.ts#L83-L92

we should check that poolOrConfig is a simple object (and not, for example, a pool returned from a different version of the `pg` module 😡 ) and throw with a helpful error if not.

**Comment by explicitcall** [comment]
Just stumbled upon this myself, [a documentation page](https://github.com/postgraphql/postgraphql/blob/master/docs/library.md) has `pg-pool` as an example, which isn't an instance of `Pool` from `pg` module, which causes errors. That documentation page should be fixed as well.

**Comment by benjie** [comment]
We have `quacksLikePgPool` now; so due to this duck-typing this shouldn't be an issue any more.
