### ISSUE TITLE
Unhelpful server-side error message when JWT has expired

### ISSUE THREAD

**Issue by zathras777** [graphile/postgraphile#560]
After working for several days, graphiql now fails to introspect the database. Error reported by postgraphsql is

1 error(s) in 127.12ms :: query IntrospectionQuery { __schema { queryType { name } mutationType { name } types { ...FullType } directives { name description locations args { ...InputValue } } } } fragment FullType on __Type { kind name description fields(includeDeprecated: true) { name description args { ...InputValue } type { ...TypeRef } isDeprecated deprecationReason } inputFields { ...InputValue } interfaces { ...TypeRef } enumValues(includeDeprecated: true) { name description isDeprecated deprecationReason } possibleTypes { ...TypeRef } } fragment InputValue on __InputValue { name description type { ...TypeRef } defaultValue } fragment TypeRef on __Type { kind name ofType { kind name ofType { kind name ofType { kind name ofType { kind name ofType { kind name ofType { kind name ofType { kind name } } } } } } } }

**Comment by benjie** [comment]
Please send the error returned from the network request (by looking in the Chrome Dev Tools' Network tab) and detail the PostGraphQL version you are using via "postgraphql --version"

**Comment by zathras777** [comment]
$ postgraphql --version
3.3.0

No network request is visible for the introspection. Documentation Explorer window simply says "NO SCHEMA AVAILABLE". There is an error visible in the console
TypeError: Cannot read property '__schema' of undefined
    at i (http://127.0.0.1:5000/_postgraphql/graphiql/static/js/main.32f19901.js:19:20833)
    at t.<anonymous> (http://127.0.0.1:5000/_postgraphql/graphiql/static/js/main.32f19901.js:15:15218)
    at r (http://127.0.0.1:5000/_postgraphql/graphiql/static/js/main.32f19901.js:23:784)
    at Generator._invoke (http://127.0.0.1:5000/_postgraphql/graphiql/static/js/main.32f19901.js:23:1904)
    at Generator.e.(anonymous function) [as next] (http://127.0.0.1:5000/_postgraphql/graphiql/static/js/main.32f19901.js:23:963)
    at r (http://127.0.0.1:5000/_postgraphql/graphiql/static/js/main.32f19901.js:15:12190)
    at http://127.0.0.1:5000/_postgraphql/graphiql/static/js/main.32f19901.js:15:12290
    at <anonymous>

Does that help?

**Comment by benjie** [comment]
Nope. I wonder if you have any browser extensions blocking the network request or blocking the loading of some JavaScript? You can try v4 via "npm install postgraphql@next -g". I've not come across this issue before.

**Comment by benjie** [comment]
Maybe you have multiple versions of graphql clashing? Are you using this via the command line or as an express middleware?

**Comment by zathras777** [comment]
Did some more digging and it turns out the error was being generated due to an expired jwt token not permitting the query to be submitted. Some queries worked, but some did not - the introspection query being one of those that didn't.

**Comment by rogerrohrbach** [comment]
I ran into this today.  I respectfully submit that an expired token should always be reported, and that this should be detected before attempting introspection.

**Comment by benjie** [comment]
Could you explain what the issue you're getting is, @rogerrohrbach? I can't seem to reproduce the issue.

---

When I run `postgraphile -c dbname -e 'secret'`; and then run a query with the following JWT:

```json
{
  "sub": "1234567890",
  "aud": "postgraphile",
  "name": "John Doe",
  "iat": 1516239022
}
```

I get:

```
echo '{nodeId}' | curl -i -d @- -XPOST -H 'Content-Type: application/graphql' -H 'Accept: application/json' http://localhost:5000/graphql -H 'Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwiYXVkIjoicG9zdGdyYXBoaWxlIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.EHjW9Pfb0J3S64pd2XU8-iDRG_Vv-0HN4li2ctyvwQw'
HTTP/1.1 200 OK
Access-Control-Allow-Origin: *
Access-Control-Allow-Methods: HEAD, GET, POST
Access-Control-Allow-Headers: Origin, X-Requested-With, Accept, Authorization, X-Apollo-Tracing, Content-Type, Content-Length
Content-Type: application/json; charset=utf-8
Date: Sat, 22 Sep 2018 14:24:33 GMT
Connection: keep-alive
Content-Length: 57

{"data":{"nodeId":"query"},"meta":{"graphqlQueryCost":1}}
```

i.e. a successfully completed authenticated request

---

When I run the same query with an expired JWT:

```json
{
  "sub": "1234567890",
  "aud": "postgraphile",
  "name": "John Doe",
  "iat": 1516239022,
  "exp": 1516239023
}
```

I get a 401 error, as expected:

```
echo '{nodeId}' | curl -i -d @- -XPOST -H 'Content-Type: application/graphql' -H 'Accept: application/json' http://localhost:5000/graphql -H 'Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwiYXVkIjoicG9zdGdyYXBoaWxlIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyLCJleHAiOjE1MTYyMzkwMjN9.VykffdNkyqaKa7z89Eg7iuDfMm8JW5k3t9cDNAeEXX8'
HTTP/1.1 401 Unauthorized
Access-Control-Allow-Origin: *
Access-Control-Allow-Methods: HEAD, GET, POST
Access-Control-Allow-Headers: Origin, X-Requested-With, Accept, Authorization, X-Apollo-Tracing, Content-Type, Content-Length
Content-Type: application/json; charset=utf-8
Date: Sat, 22 Sep 2018 14:24:47 GMT
Connection: keep-alive
Content-Length: 68

{"errors":[{"message":"jwt expired"}],"meta":{"graphqlQueryCost":1}}
```

---

So the expired token is reported (both in the JSON body and in the HTTP status code) and the detection does occur before the GraphQL query (whether introspection or otherwise) would take place.

**Comment by rogerrohrbach** [comment]
@benjie The error occurs when I attempt to refresh the Docs in an interactive client (I'm using [Altair](https://altair.sirmuel.design)) with an expired JWT.  The result is exactly that first reported here, [above](https://github.com/graphile/postgraphile/issues/560#issue-251283375).

**Comment by benjie** [comment]
Oh I *seeeeee*. The issue that you have is the console log on the *server* side rather than the lack of error reporting on the *client* side!

I don't think it's appropriate to let the expired JWT go through and perform introspection, btw. But I can change how the error is exposed 👍

**Comment by benjie** [comment]
(For one thing, that's not the only introspection query in existence, and writing code to detect whether a particular query is purely introspection or not would unnecessarily reduce performance.)

**Comment by rogerrohrbach** [comment]
Yes—we're all in agreement.  And the new title for this issue more accurately captures the problem.

**Comment by pixelpax** [comment]
Hm... I just ran into this again running postgraphile locally with version 4.5.0. Possible regression? 

Blank explorer pane w/ no UI error messages. In the log, introspection query prints  

`401 authentication error in 50.74ms :: query IntrospectionQuery { __schema { queryType { name } mutationType { name } subscriptionType { name } types { ...FullType } directives { name description locations args { ...InputValue } } } } fragment FullType on __Type { kind name description fields(includeDeprecated: true) { name description args { ...InputValue } type { ...TypeRef } isDeprecated deprecationReason } inputFields { ...InputValue } interfaces { ...TypeRef } enumValues(includeDeprecated: true) { name description isDeprecated deprecationReason } possibleTypes { ...TypeRef } } fragment InputValue on __InputValue { name description type { ...TypeRef } defaultValue } fragment TypeRef on __Type { kind name ofType { kind name ofType { kind name ofType { kind name ofType { kind name ofType { kind name ofType { kind name ofType { kind name } } } } } } } }
`

The problem resolved by removing the stale jwt in the UI.

**Comment by benjie** [comment]
Are you using a custom JWT middleware? Our JWT logic doesn’t block introspection.
