### ISSUE TITLE
Bug: pgSettings turn value types into strings

### ISSUE THREAD

**Issue by lifeiscontent** [graphile/postgraphile#566]
given the following pgSettings:

``` js
pgSettings: req => ({
            'user.user_id': req.ctx.session.user_id || ''
          })
```

I expect the following:

when `req.ctx.session.user_id === null` to set `user.user_id` to
  expected: `""` or `null`
  actual: `"null"`

when `req.ctx.session.user_id === undefined` to set `user.user_id` to
  expected: `""` or `null`
  actual: `"undefined"`

**Comment by benjie** [comment]
Suggestion: strings and numbers should be passed through, null/undefined should be dropped, and everything else should throw an error.

**Comment by lifeiscontent** [comment]
@benjie if I was to make a PR for this, which branch or repo should I work in?

**Comment by benjie** [comment]
Master; I'll then merge into v3 and v4

**Comment by benjie** [comment]
Specifically you want to extract this line and add slightly more logic:

https://github.com/postgraphql/postgraphql/blob/master/src/postgraphql/http/createPostGraphQLHttpRequestHandler.js#L404
