### ISSUE TITLE
Filter by computed columns?

### ISSUE THREAD

**Issue by pencilcheck** [graphile/postgraphile#593]
I can't see the filter for the computed columns I wrote, I wonder if this is even designed to be possible?

**Comment by chadfurman** [comment]
Could you give an example with SQL / code?

**Comment by benjie** [comment]
Currently we do not support filtering by computed columns in core, but it would Not be a complex plugin to add support I think.

**Comment by pencilcheck** [comment]
@chadfurman add any computed columns (e.g. stored procedure), and try to open graphiql and look into any function that provides $condition parameter and see if you can find the computed column you created. If you can find it that would be awesome. I currently can't.

**Comment by pencilcheck** [comment]
@benjie What would you recommend I can look into to get started on writing this plugin?

**Comment by benjie** [comment]
@pencilcheck I'm afraid the documentation is still emerging; but I'd start here:

https://www.graphile.org/postgraphile/extending/

And also with the plugin that adds `condition:` to connection args:

https://github.com/graphile/graphile-build/blob/master/packages/graphile-build-pg/src/plugins/PgConnectionArgCondition.js

And also with @mattbretl's plugin that adds more advanced filtering:

https://github.com/mattbretl/postgraphile-filter-plugins

**Comment by chadfurman** [comment]
@pencilcheck thank you, I wasn't sure exactly what you were saying and I appreciate the clarification

**Comment by benjie** [comment]
Matt's plugin above now supports filtering by computed columns 👍
