### ISSUE TITLE
Log levels

### ISSUE THREAD

**Issue by JacobAMason** [graphile/postgraphile#599]
Postgraphql seems to print out stuff to the terminal on every request it responds to. Is there a way to set the log level such that only errors are printed out?
I'm also fine with stdout/err manipulation to do this, if it's possible.

**Comment by benjie** [comment]
The `disableQueryLog` option will disable the query log entirely:

https://www.graphile.org/postgraphile/usage-library/#api-postgraphilepgconfig-schemaname-options

https://github.com/postgraphql/postgraphql/blob/779a643898418bc732473025182710f2d5b843ef/src/postgraphql/http/createPostGraphQLHttpRequestHandler.js#L439-L449

We don't currently have an option to just output this when errors occur; I'd consider a PR that enabled this via some backwards-compatible method (e.g. making the debug levels numeric constants and auto-converting true/false to the relevant constant in the new system).

**Comment by chadfurman** [comment]
Where do errors actually log to?  Is it possible to not include errors in the server response, but still log them?

**Comment by benjie** [comment]
We don't actually log the errors AFAIK; a PR for that would be welcome also (or maybe a hook so we can post them into [Rollbar](https://app.codesponsor.io/link/GvWU8mAin34aDjbdv9ze278R/postgraphql/postgraphql)/etc)

The whole logging thing could do with a complete overhaul really.

**Comment by benjie** [comment]
Errors are available using `DEBUG=postgraphile:postgres:error`:

https://www.graphile.org/postgraphile/debugging/

We still need to improve the error situation; help with that would be welcome 👍
