### ISSUE TITLE
Proposal: deprecate Koa support in v4

### ISSUE THREAD

**Issue by benjie** [graphile/postgraphile#602]
I've heard that our Koa support is a bit iffy, and we currently have no-one maintaining it, so I'm proposing that we remove Koa support and instead recommend people use `koa-connect` or similar. Native Koa support would be better, but with no-one to maintain it, it's a burden.

If anyone wants to step up to maintain the native Koa support in PostGraphQL please do so soon! Otherwise v4 is the perfect time for us to deprecate Koa support such that we can remove it in v5.

Please weigh in below.

**Comment by wenzowski** [comment]
> I've heard that our Koa support is a bit iffy
Are there open issues we can link here? I haven't come across problems yet

**Comment by benjie** [comment]
@alexFaunt perhaps you can chime in here?

**Comment by alexFaunt** [comment]
When i tried it with Koa I had a few issues, but wrapping with koa-connect everything worked fine. 

To be honest, I can't remember what went wrong, so it may have been me miss-using it, if I get a chance I can start from scratch again to see if I hit issues - time permitting though!

Either way the koa support that is currently in the lib doesn't interfere with koa-connect so no urgent reason to remove it

**Comment by benjie** [comment]
Can confirm that postgraphql does not work great with Koa (e.g. on error you get

```
Error:  Can't set headers after they are sent.
```
); koa-connect seems to solve this.

**Comment by wenzowski** [comment]
Guess I hadn't managed to hit an unhandled error. Moved over to koa-connect

**Comment by parris** [comment]
Note - we are using this with koa without issue -
https://github.com/fervorous/fervor/blob/master/src/server/server.js#L35

**Comment by benjie** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Deprecate koa support (or fix it!)](https://trello.com/c/yhycOyHc/12-deprecate-koa-support-or-fix-it)

**Comment by wenzowski** [comment]
ref: https://github.com/postgraphql/postgraphql/issues/522

**Comment by thewillhuang** [comment]
im using koa withoout issue as well /shrug

**Comment by benjie** [comment]
I think I'll just denote koa support as experimental rather than remove it 👍

**Comment by benjie** [comment]
Koa marked as experimental - it won't be removed, but issues with it will not be treated with the same severity as issues in express/etc.

**Comment by sjmcdowall** [comment]
As a corp. sponsor and user of Koa V2 .. I'd say .. No. :)  Although it doesn't have to have level 1 support I guess as long as there is someway to get it done .. maybe "we" could look at a koa-postgraphile module that does the wrapping .. seems like there are quite a few of those out there..

**Comment by benjie** [comment]
I’ll take a look at this tomorrow; I was under the impression that it mostly worked but that error handling was the issue.

**Comment by benjie** [comment]
I did start looking into this; more to come hopefully Friday.

**Comment by benjie** [comment]
So I think the reason is that the express body parser and the koa body parser don't work well together - the koa one consumes the body but the express one doesn't check for that and tries to decode it again, resulting in a hang.

**Comment by benjie** [comment]
So basically, it works for people who don't add bodyParser middleware before PostGraphile, and doesn't (always) work for those that do.

**Comment by benjie** [comment]
This should fix it: https://github.com/graphile/postgraphile/pull/780

**Comment by sjmcdowall** [comment]
Awesome1  Do I still need to use the koi-connect middleware to get this to work (I am assuming yes since the call sig for a Express & Koa middleware are quite different) ??

**Comment by benjie** [comment]
Theoretically no. I definitely want it to work without that. It works for me without it, but I've barely tested it - I'll be releasing a demo project soon showing usage.

**Comment by sjmcdowall** [comment]
I'll give it a try probably this afternoon (EDT) as well but the above is awesome -- 1st class Koa citizen! :) 
Oh and yes, I was for sure using the Koa body parser ahead of postgraphile since we have other routes we need to handle too .. So very interesting!

**Comment by benjie** [comment]
Have added a few more fixes; now no more headers warnings (that's what I was getting when I used PostGraphile with Koa) and also the server-sent events now work so schema watching in GraphiQL is live in the Koa version too 👍 

https://github.com/graphile/postgraphile/pull/780
https://github.com/graphile/postgraphile/pull/781
https://github.com/graphile/postgraphile/pull/782

I'm still deeming Koa support experimental; but it's suddenly a lot lot better 🎉

**Comment by sjmcdowall** [comment]
Woohoo!  As soon as I can pull a version with this in it (rc2?) I will give it a whirl.  And yes, I think a set of Koa tests would be a fine idea.  I'll pop it on my to do list for myself or my team ..

**Comment by benjie** [comment]
It'll be in RC2, yeah. There's lots more stuff required in RC2 though, so it'll probably not be until next week or maybe the week after 😞

**Comment by maxdesiatov** [comment]
I'm finding GraphiQL static assets hanging with koa, but very intermittently. When I use [`koa-graphiql`](https://github.com/expo/koa-graphiql) as a replacement all is good, but it doesn't load schema docs generated by PostGraphile. Everything else (main `/graphql` endpoint) is working well. Maybe the fixes that were applied didn't touch GraphiQL parts at all?

**Comment by benjie** [comment]
Are you able to figure out how to reproduce it? I think it’s an issue with `send` interacting with Koa. GraphiQL assets serving is changing soon anyway, so this might go away...

**Comment by maxdesiatov** [comment]
it's stably reproducible for me, I just set PostGraphile middleware on `/graphiql` path and open it in Safari. Most of the time it hangs (just blank page and loading progress never ends), although when I hit "refresh" when it's hanging it loads ok.

**Comment by benjie** [comment]
Any idea what resource is hanging? Is it the graphiql endpoint itself or the css/js? If you can reliably reproduce it then digging further in devtools would be great.

Are you using any koa middlewares before postgraphile? Does removing them solve/reduce the issue?

**Comment by maxdesiatov** [comment]
Basically every second load of `/graphiql` in any browser stalls for me. Literally I'm going to `/graphiql` and it loads, I reload it and it stalls, I reload it again and it loads again.
Removing all other middleware doesn't make any difference. I'm on `"koa": "^2.5.3"` and `"postgraphile": "^4.0.1"`. Devtools screenshots attached.

Stalled one:
<img width="580" alt="screen shot 2018-10-11 at 11 11 44" src="https://user-images.githubusercontent.com/112310/46797440-16947400-cd47-11e8-9fcb-fb01d4ca1c4b.png">

Every second one is loading well:
<img width="726" alt="screen shot 2018-10-11 at 11 12 00" src="https://user-images.githubusercontent.com/112310/46797476-2d3acb00-cd47-11e8-8c2c-564fee59fb62.png">

**Comment by benjie** [comment]
Cool; so it's definitely the resources. I think it's an interaction with `send`. I've already got a branch locally that removes `send` so I think this'll be fixed in 4.1.0 👍
