### ISSUE TITLE
Write a custom function like a postgraphql introspected CRUD function

### ISSUE THREAD

**Issue by ortonomy** [graphile/postgraphile#605]
What I've done so far: 
1. Followed the tutorial to create a split user record: one in a ``..._private`` schema and one in a ``anonuser`` and ``appuser`` accessible schema.
2. Followed the tutorial to create a ``register_user`` function. 

What I want to do:
I want to create the remaining CRUD functions for ``updateUser`` and ``deleteUser`` BUT I want them to have the same signatures / functionality as the automatically generated mutations that postgraphql creates when introspecting tables.

For example, on posts: ``updatePost`` and ``updatedPostByID``, both of which take an ``input`` object, and the ``input`` object is the global ``id`` and a ``patch`` object. I'd like to be able to replicate the this function signature in my custom functions.

Is it possible? What function signature do I need to create for _postgraphql_ to look at my function generate this same ``graphql`` mutation?

Stretch goal:
I'm very bad with SQL / pgplsql and I've tried searching for solutions to '_variadic postgresql functions to update tables_' and no dice so far. A complete function skeleton (signature, SQL UPDATE statement for this would be very helpful. -- or a link to a stackoverflow answer if you know one!)

**Comment by benjie** [comment]
This is not currently possible in SQL; in fact it’s not currently possible to use the Patch type in custom SQL mutations at all, let alone matching the payload. Also the nodeId is implemented in JS so again it’s not currently possible to use it in a custom mutation.

Hopefully one day this will be possible; it will probably be achieved using smart comments on the function to change its interpretted behaviour.

You can, however, achieve all of this using the plugin interface on v4, but it’s a fair amount of work. Check the extending docs on graphile.org

Good luck!

**Comment by ortonomy** [comment]
@benjie -- well thanks for the clarification, at least. 

So the approach would be to just a custom mutation that takes (id + all fields) with STRICT setting, so front-end supplies all values, either unchanged / updated, and update the entire row?

**Comment by benjie** [comment]
Here's a few ways you could do it:

1. Create a new patch type with only the fields you care about: `create type user_patch2 as (name text, dob date); create function update_user(id int, user_patch user_patch 2) ...`
2. Accept the fields explicitly `create function update_user(id int, name text, dob date)`
3. Use the default mutations combined with triggers and/or RLS policies (this'll require more mastery of SQL though)
4. Use `replaceAllPlugins` to "remove" the mutations plugins and replace them with your own forks that do what you need

**Comment by chris-guidry** [comment]
@benjie is there any way to decode the nodeId in Postgres to identify a unique row?

I have a scenario where I'm rewriting a component, which will use new tables, but I need it to be backwards compatible with existing versions of our app so I created a view that mimics the old schema and I have been recreating the mutations, which works for create and update because the patch has enough data, but not for deletes because the only input parameter is nodeId.
