### ISSUE TITLE
Error with custom composite type as parameter in function

### ISSUE THREAD

**Issue by Trupal00p** [graphile/postgraphile#618]
I'm getting this error when I use a custom composite type as a parameter in an sql function.

```malformed record literal: "somefilter"```

Here is the custom type and the function in my database schema:

```sql
CREATE TYPE search_recipes_condition as (
    title_like text
);

create or replace function ivtracker.search_recipes(condition search_recipes_condition) returns setof ivtracker.recipe as $$
    select recipe.*
    from ivtracker.recipe as recipe
    where (
      (condition.title_like) is null OR
      recipe.title ilike ('%' || (condition.title_like) || '%')
    )
$$ language sql stable;
```

Here is the graphql query I'm sending that causes the error:

```graphql
query {
  searchRecipes(condition: {titleLike: "somefilter"}) {
    nodes {
      nodeId
      title
    }
  }
}
```

The really weird thing is if I modify the query to add parenthesis to the filter, the error goes away and the query works as expected:

```graphql
query {
  searchRecipes(condition: {titleLike: "(somefilter)"}) { # <--- note the change here
    nodes {
      nodeId
      title
    }
  }
}
```

I'm trying to set up the function like this to mirror the autogenerated functions that postgraphql provides for each table.  This will allow me to share some code between my components.

I could change my components to send the query with the parenthesis but it seems like it might be a signal of another issue.  Any ideas?

**Comment by benjie** [comment]
Please confirm “postgraphql --version” and whether this still happens with the latest version.

**Comment by Trupal00p** [comment]
Original error occurred with 3.5.0.  

I just upgraded to 3.5.1 and got the same error.

**Comment by benjie** [comment]
I think this is fixed in postgraphql@next; would you mind confirming? See #506

**Comment by Trupal00p** [comment]
Upgraded to 4.0.0-alpha2.22, issue still present.

**Comment by benjie** [comment]
Please provide a minimal test case that reproduces this (an SQL file I can import into a clean database and a `postgraphql` command line) and I'll look into it.

**Comment by Trupal00p** [comment]
Here's a minimal schema to recreate the issue:
```plpgsql
DROP TABLE if exists recipe cascade;
create table recipe
(
    recipe_id                    serial primary key,
    title                        varchar(100)
);
drop type if exists search_recipes_condition;
CREATE TYPE search_recipes_condition as (
    title_like text
);
create or replace function search_recipes(condition search_recipes_condition) returns setof recipe as $$
    select recipe.*
    from recipe as recipe
    where (
      (condition.title_like) is null OR
      recipe.title ilike ('%' || (condition.title_like) || '%')
    )
$$ language sql stable;

insert into recipe (title) values
('firsttitle'),
('secondtitle'),
('thirdtitle'),
('fourthtitle');
```

Here's a graphql query that throws the error:
```graphql
query {
  searchRecipes(condition: {titleLike: "title"}) {
    nodes {
      nodeId
      title
    }
  }
}
```

Thank you for your work and stewardship on this awesome tool!

**Comment by benjie** [comment]
v3.5.1 definitely does:

![screenshot 2017-11-06 17 38 18](https://user-images.githubusercontent.com/129910/32455152-504c93e6-c319-11e7-87a5-38c0f848e0fe.png)

**Comment by benjie** [comment]
I'm afraid I'm unlikely to solve this issue in v3 as my work is focussed on getting v4 ready for release. If you want to raise a PR to fix this in v3 that'd be welcome, but failing that I recommend you use v4 for now 👍

**Comment by Trupal00p** [comment]
Ah yes, you are right.  Looks like I had it installed globally and locally (woops!) so the upgrade didn't take when I tested.  

Don't worry about fixing v3, definitely not worth it.

**Comment by benjie** [comment]
This is not an issue in v4
