### ISSUE TITLE
Time out for post graphql server

### ISSUE THREAD

**Issue by mamtalakhani** [graphile/postgraphile#623]
Can you plz let me know where to set the timeout for postgraphql server.

**Comment by benjie** [comment]
What timeout are you looking for?

**Comment by mamtalakhani** [comment]
We have a query which runs for a few minutes in Postgres. When the same query is written in GraphiQL,the server responds with 504 Gateway timeout exactly after 1.5 min. We would like to change the 1.5 min timeout variable.

**Comment by benjie** [comment]
I'm not aware of this limit (that isn't to say it doesn't exist). The error "Gateway Timeout" implies that you have something between the PostGraphQL server and the client (aka a "Gateway") and that that is causing the connection to time out. On Heroku this period is 30 seconds.

**Comment by benjie** [comment]
This was added by the above commit 🙏
