### ISSUE TITLE
Forum tutorial does not use missing_ok parameter in current_setting

### ISSUE THREAD

**Issue by johnchristopherjones** [graphile/postgraphile#629]
The forum tutorial explains how to set up row-level security using `current_setting`.  However, `current_setting` throws an exception unless the `missing_ok` option (psql >= 9.6) is provided.  People who follow the tutorial will no longer be able to perform queries on the affect tables without first manually setting the `jwt` locals, even as superusers.

Instead, the `create policy` steps that include `current_setting('jwt.claims.person_id')` should instead read `current_setting('jwt.claims.person_id', true)`.

**Comment by benjie** [comment]
It might be better to add the following to the schema, as otherwise people using Postgres 9.5 or lower will not be able to run the example:

```sql
do $$
begin
execute 'alter database ' || current_database() || ' set jwt.claims.person_id to ''''';
end;
$$ language plpgsql;
```

**Comment by johnchristopherjones** [comment]
1.  I didn’t know you could make it permanent that way.  That would also work, though a similar statement would be needed if any additional JWT claims that are checked via RLS.  Maybe that’s okay.  It also seems trickier if person_id is a uuid and nullable.
2.  Should Postgres <= 9.5 really be a concern, given that [graphile only officially supports Postgres 9.6+](https://www.graphile.org/postgraphile/requirements/ <https://www.graphile.org/postgraphile/requirements/>)?
3.  I can’t tell: Is the schema change still better, either technically or pedagogically, if only 9.6+ is considered?

**Comment by benjie** [comment]
PostGraphile currently supports PG 9.4+. I'd be open (if not keen!) to bump that to 9.5 now that PG10 is out, but I think 9.6 is too recent for many people. 

With the example schemas we want people to be able to run them on what they already have so they can get an immediate taste of PostGraphile, so using ugly workarounds like the `do $$` above is better than requiring something that will not work on older versions. 

Once they come to actually use PostGraphile they should update their database (in fact PG10 has massively improved performance in some RLS-related queries, so it's worth updating to that!) but for trying it out I would like to support as far back as reasonably possible.

If you wanted to open a PR to add the `do $$` to the schema (maybe with some comments around it explaining that if they're using PG9.6+ they don't need it and they should instead use `missing_ok`) that would be fantastic 👍 

(I'm just as frustrated as you that we can't simply use `missing_ok` in the schema, by the way.)

**Comment by benjie** [comment]
Almost a year has gone by, we should definitely switch over to using `missing_ok` now. This would be a very simple PR for someone if they want it 👍
