### ISSUE TITLE
Relay Modern support ✅

### ISSUE THREAD

**Issue by charring** [graphile/postgraphile#663]
I'm submitting a ... 
- [ ] bug report
- [ ] feature request
- [x] question 

I read that Relay Modern imposes some requirements on the server. But article did not elaborate. Anyway, I'm curious if postgraphql is compatible with Relay Modern.

**Comment by benjie** [comment]
I believe @chadfurman is using PostGraphile + Relay Modern with great success?

**Comment by wenzowski** [comment]
Works beautifully. You'll probably want `classicIds: true` unless you use globally unique primary keys for your tables (eg. uuids).

**Comment by chadfurman** [comment]
Yes I use relay modern all the time it is lovely.

Relay standard is supported in Postgraphile since before version 4.

For a (not yet working or complete but somewhat functional) example, please look to https://github.com/chadfurman/rpg-boilerplate

**Comment by benjie** [comment]
I'd welcome someone to add a page on graphile.org detailing what you should think about when using Relay Modern with PostGraphile. (You only need to write a markdown file.)

**Comment by chadfurman** [comment]
@benjie expect a blog post series by the end of the month and a presentation at NERD Summit 2018 on this.

**Comment by benjie** [comment]
😍

**Comment by charring** [comment]
Thanks. I'm looking forward to digging into this new (for me) tech stack!

**Comment by chadfurman** [comment]
Working on this heavily this week.  I have a talk this weekend at a local conference, and I am using that to fire me up on this task.

**Comment by benjie** [comment]
Of interest:

- https://github.com/chadfurman/rpg-boilerplate
- https://chads.website/development/2018/08/03/How-GraphQL-Saved-My-Project.html
- https://www.youtube.com/watch?v=4in5QbFyodA
