### ISSUE TITLE
Where can I report vulnerability details?

### ISSUE THREAD

**Issue by orangetw** [graphile/postgraphile#673]
I'm submitting a ... 
- [x] bug report
- [ ] feature request
- [ ] question 

PostGraphQL version:
3.5.4

Hi, I found some vulns, Is there any security related mail I can send my report?
P.S. I checked the website and GitHub, but I couldn't find where I can send the report :(

**Comment by benjie** [comment]
You can send them to me: code@benjiegillam.com

**Comment by orangetw** [comment]
Hi, I sent the report! Please check it :)

**Comment by benjie** [comment]
This issue was solved in 3.5.5 👍 

https://github.com/graphile/postgraphile/releases/tag/v3.5.5
