### ISSUE TITLE
Restrict a specific verb on a specific table

### ISSUE THREAD

**Issue by benbonnet** [graphile/postgraphile#687]
I'm submitting a ...
[ ] bug report
[x] feature request
[ ] question

PostGraphQL version: futures

Would that be possible to restrict a specific verb on a specific table (given a `users table`, for example disabling `deleteUser`, but still having the defaults `allUsers`, `createUser`, `updateUser`) ?

**Comment by benjie** [comment]
Ref https://github.com/postgraphql/postgraphql/issues/596#issuecomment-365863457

We could perhaps support this by tweaking `--enable-default-mutation-tables` to contain a permissions suffix, not unlike `\dp+` in `psql`; e.g. `--enable-default-mutation-tables users=rw,posts,comments=ra` to imply users gets SELECT (r) / UPDATE (w) methods exposed, posts gets all current methods, and comments only gets SELECT (r) and INSERT (a).

```
            r -- SELECT ("read")
            w -- UPDATE ("write")
            a -- INSERT ("append")
            d -- DELETE
            D -- TRUNCATE
            x -- REFERENCES
            t -- TRIGGER
            X -- EXECUTE
            U -- USAGE
            C -- CREATE
            c -- CONNECT
            T -- TEMPORARY
      arwdDxt -- ALL PRIVILEGES (for tables, varies for other objects)
```
> -- https://www.postgresql.org/docs/9.6/static/sql-grant.html

**Comment by benjie** [comment]
This functionality is now possible via [smart comments](https://www.graphile.org/postgraphile/smart-comments/#omitting), e.g.

```sql
comment on table table_name is E'@omit create,update,delete';
```
