### ISSUE TITLE
Dynamic JSON makes schema inaccurate; should come with a warning

### ISSUE THREAD

**Issue by slikts** [graphile/postgraphile#688]
I'm submitting a ... 
- [ ] bug report
- [x] feature request
- [ ] question 

Enabling the dynamic JSON option breaks any tool that relies on the schema to parse the results, and since GraphQL doesn't seem to have a way of expressing a 'dynamic' field type, PostGraphQL should at least display a warning that the schema is inaccurate for JSON results.

**Comment by benjie** [comment]
Please could you expand on this with concrete examples of dynamic JSON breaking any tools?

I've had success using PostGraphile with both Apollo and Relay with the dynamic JSON option, so I'm not sure what tool it is breaking for you? I wonder if you're just expressing that the JSON does not have a schema associated with it (which is not unexpected - we cannot determine the schema for an arbitrary JSON field!), though I'm not sure how turning dynamic JSON off and handling the field as a string (which would still result in a schema-less data structure after parsing) would solve this?

This documentation from Apollo GraphQL might be relevant:

https://www.apollographql.com/docs/graphql-tools/scalars.html#Using-a-package

**Comment by slikts** [comment]
I'm using [Graphqelm](https://github.com/dillonkearns/graphqelm) to make GraphQL queries; it ensures the field payload matching the field type, so a 'dynamic' payload breaks it. The other tools you mentioned don't have type safety so the schema being inaccurate won't break them.

**Comment by benjie** [comment]
I think that's a limitation of the elm-graphql client - it doesn't fully support custom scalars - see [this issue](https://github.com/jahewson/elm-graphql/issues/32).

From the GraphQL specification:

> All GraphQL scalars are representable as strings, though depending on the response format being used, **there may be a more appropriate primitive for the given scalar type, and server should use those types when appropriate**.
> -- http://facebook.github.io/graphql/October2016/#sec-Scalars (emphasis mine)

We allow you to opt in to `--dynamic-json` which tells the server to use the more appropriate primitive of a JSON object for the JSON data type given it is being sent in a JSON payload from the server. If your client does not support this then I recommend you leave this option disabled; or send a PR to your client of choice adding support 👍

**Comment by benjie** [comment]
I'm still happy with our use of JSON, I'm going to close this for now but if anyone finds any other GraphQL tools that suffer due to `--dynamic-json` please let me know below.
