### ISSUE TITLE
Error: Run CLI with option '--no-server'

### ISSUE THREAD

**Issue by sofyanhadia** [graphile/postgraphile#700]
I'm submitting a ... 

* [x] bug report
* [ ] feature request
* [ ] question 

PostGraphile version:
`4.0.0-alpha2.33`

I'm trying to execute postgraphile using cli with `--no-server` option, 
I got an error message like this

`error: unknown option '--no-server'`

Steps to reproduce:

My full CLI command:
```
postgraphile --no-server  -c postgres://user:db_pass@localhost:5432/dbname --export-schema-graphql src/graphql/test.graphql
```

Current behavior:
`error: unknown option '--no-server'`

Expected behavior:
Should generating schema without postgraphile's server running

**Comment by benjie** [comment]
Yeah; you've managed to see the new docs before I've released the software 😁 Happy to see you desire this feature.

Add your email to the newsletter and you'll be notified when it goes out, hopefully within the next week.

https://www.graphile.org/

Sorry!
