### ISSUE TITLE
Customize the GraphQL schema to hide selected tables

### ISSUE THREAD

**Issue by Tritpi** [graphile/postgraphile#701]
Please confirm if we can customize the GraphQL schema to show/hide only selected tables using postgraphql. For example if there are five tables in a schema out of which only three tables need to be shown and the other two to be hidden , please confirm if there is an option available in postgraphql for the same.

**Comment by benjie** [comment]
At the moment we use the schemas themselves to declare the tables to be exported (e.g. I commonly use app_public for the tables to be exported to GraphQL, app_hidden for things not to be exported, and app_private for utilities/etc that may require elevated privileges to execute). It's possible to remove tables from the schema by extending; see: https://www.graphile.org/postgraphile/extending/#removing-things-from-the-schema

It would not be much work to add the functionality to the relevant plugins to skip over the tables you don't want using smart comments (e.g. `comment on table app_public.ignore_me is E'@skip\nThis table will not be exported via GraphQL';`); I've not implemented it yet but it's on the cards.

**Comment by benjie** [comment]
Ref: https://github.com/graphile/graphile-build/issues/186

**Comment by hmaurer** [comment]
Close @benjie ?

**Comment by benjie** [comment]
This is now possible via smart comments https://www.graphile.org/postgraphile/smart-comments/

**Comment by alexisrolland** [comment]
Hi @benjie ,
I have one more question in this context. Is it possible to hide table in GraphiQL documentation but still allow queries and mutations on these tables? It seems the `@omit` smart comment entirely hides the table from the GraphQL schema while I just would like to hide tables from GraphiQL.
Thank you
Alexis

**Comment by benjie** [comment]
No, that's not how GraphQL works. If a field/type exists in a schema then it comes up in introspection; if it comes up in introspection then GraphiQL can display it.
