### ISSUE TITLE
readCache/writeCache as functions

### ISSUE THREAD

**Issue by SomeHats** [graphile/postgraphile#703]
I'm submitting a ... 

* [ ] bug report
* [x] feature request
* [ ] question 

It might be useful for `readCache`/`writeCache` to accept functions:
```js
type WriteCacheFn = (SchemaCache) => Promise<void>;
type ReadCacheFn = () => Promise<SchemaCache>;
```

For me, the use case is generating the schema cache in a build step. I want postgraphile to connect to my db, write the schema cache, and then exit. Functions like this would give me hooks to write the cache file myself and then call `process.exit`. People could also store the cache somewhere other than a local file too with this but I'm not sure why anyone would want to.

An alternative would be a option/command line flag like `--exit-after-cache-write`. 

Happy to submit a PR for either of these options if you'd accept it :D

Thanks for all your work on postgraphile ✨

**Comment by benjie** [comment]
Going out today is the —no-server option which’ll achieve what you need 🤘

**Comment by benjie** [comment]
Just went out: https://github.com/graphile/postgraphile/releases/tag/v4.0.0-beta.0
