### ISSUE TITLE
Docker for PostGraphile

### ISSUE THREAD

**Issue by benjie** [graphile/postgraphile#704]
Hey @angelosarto could you help me set up the docker stuff for PostGraphile please? I lost the instructions you gave me last time 😳 but I've created the Docker Hub "graphile" team:

https://hub.docker.com/u/graphile/dashboard/

Not sure if the repo rename is going to cause issues?

Thanks! 🙏

**Comment by hmaurer** [comment]
Is this still a concern? And was this about using Docker for consuming Postgraphile? Or for developing it? I use Docker locally when working with Postgraphile (both to run Postgraphile and to run a Postgresql server), so I can probably help.

**Comment by benjie** [comment]
I could do with a hand 👍 Lets chat on gitter

**Comment by benjie** [comment]
I’ve got it set up but it lags behind npm releases because rather than rebuilding in the container I simply have it install from npm. I’m going to add a webhook or something to trigger from npm publish.

**Comment by benjie** [comment]
I've added a webhook trigger to GitHub so when I publish a new release it'll trigger a new build. I'll just have to be careful to not publish the release on GitHub until after I've pushed it to npm 👍
