### ISSUE TITLE
Will JWT token generated externally work for PostgraphQL?

### ISSUE THREAD

**Issue by Tritpi** [graphile/postgraphile#715]
Does postgraphql confirm if the token was generated by the application itself and not externally? For example if someone figures out the secret and generates a valid JWT token outside of the application, can that token be used in the HTTP header to access data via the GraphiQL interface. Or will it reject the token as it was created externally.

**Comment by benjie** [comment]
How would it know? If you know the secret you can generate any arbitrary JWT token - there’d be no way of knowing.

**Comment by xorander00** [comment]
Protecting your secret that's used to generate the securely signed token would be true of any system, not just PostGraphile.  If you're asking whether or not there are any other factors that are PostGraphile-specific that are used to generate the token (in which case it might be possible to differentiate between an internal and external token), then my guess is no.  @benjie would know far better than I would though, as I am not familiar with the implementation.

**Comment by chromonav** [comment]
I think this is a good thing. We can leverage external auth providers like Auth0 or AWS Cognito and just pass the auth token to Postgraphile.
This would useful as we would not have to do heavy lifting of verification etc operations.
