### ISSUE TITLE
Restrict the query execution time in PostgraphQL

### ISSUE THREAD

**Issue by Tritpi** [graphile/postgraphile#716]
Is there an option/setting in postgraphql which allows us to set the max run time of a query.This is to ensure that someone doesn’t run a query which consumes a lot of resources for a long period of time on the database.

**Comment by benjie** [comment]
I think you can do this via pgSettings; set the statement_timeout

https://www.postgresql.org/docs/9.6/static/runtime-config-client.html
https://www.graphile.org/postgraphile/usage-library/

**Comment by hmaurer** [comment]
Do note some related features are now available under a payed plan c.f. https://www.graphile.org/postgraphile/pricing/. @benjie

**Comment by benjie** [comment]
Not to do with query execution time explicitly though - but this request is solved via pgSettings.
