### ISSUE TITLE
Computed columns don't work when only specific columns are granted

### ISSUE THREAD

**Issue by flux627** [graphile/postgraphile#718]
I'm submitting a ... 

* [x] bug report
* [ ] feature request
* [ ] question 

PostGraphile version:
```
"postgraphile": "^4.0.0-beta.3"`
```

Steps to reproduce:

I'm using PostGraphile as a library. If you create a table and grant a subset of all columns to a role, then attempting to use computed columns raises a `permission denied for relation ____` error. I confirmed this was the problem by granting all columns to the user, which resolved the problem.

If necessary I will provide a minimal SQL example but I don't have time at this moment.

**Comment by benjie** [comment]
I’m afraid that’s just how these computed fields work - we pass the entire row to the function, if you’re not allowed to select all columns then you can’t use computed columns.

I generally recomment granting select on the table directly, and splitting concerns into separate 1-to-1 tables that can have different permissions.

**Comment by flux627** [comment]
I guess I'll just have to wait for smart comments to restrict column access...

**Comment by benjie** [comment]
Or use pgColumnFilter directly (undocumented), or split your concerns into separate tables.

**Comment by flux627** [comment]
It doesn't make sense to separate out a `scope` column used for row level
security into it's own table.

I'm interested in contributing to the smart comment feature. Is there any
direction you'd be able to give to kickstart efforts in that direction?

**Comment by benjie** [comment]
The relevant pieces already have smart tags parsed:

https://github.com/graphile/graphile-build/blob/0a1936fc1b43cf30e854a650583c1fcabbb2511e/packages/graphile-build-pg/src/plugins/PgIntrospectionPlugin.js#L95-L107

We just don't have anything using them yet. You should make a pgColumnFilter function (search the codebase, but basically it's `pgColumnFilter(attr, build, context)`) that filters based on these tags. E.g.:

```js
app.use(postgraphile(DATABASE_URL, schemas, {
  graphileBuildOptions: {
    pgColumnFilter: attr => !attr.tags.omit
  }
})
```

Then to skip the field you might do, for example,

```sql
comment on column my_schema.my_table.scope is E'@omit\nThis should not be present in the GraphQL API';
```

**Comment by benjie** [comment]
Note that this is experimental functionality and is likely to change soon as I solidify it and document it as part of the ongoing work in v4.

**Comment by flux627** [comment]
Thanks Benjie.

Would you entertain a PR that:
1. Adds `pgColumnFilters` which accepts an array of functions, processed in order (replaces `pgColumnFilter` if it is defined)
2. A new directory of column filter functions that hold the default smart comment filters (what ever they may be), which are prepended to any custom `pgColumnFilters`

Now that I think about it though, shouldn't this be all done using PostGraphile plugins? Is there anything that a pgColumnFilter can do that a PostGraphile plugin can't?

**Comment by benjie** [comment]
It’s already exposed via a plugin; if you search the issues you might find instructions on how to expand it with more plugins. Basically just write another function that wraps the original one.

I don’t want to merge any PRs on it right now because I have some plans I want to implement first, but thanks for offering. You’re welcome to implement a plugin that does it though!
