### ISSUE TITLE
graphql dependency

### ISSUE THREAD

**Issue by lifeiscontent** [graphile/postgraphile#720]
I'm submitting a ... 

* [x] bug report
* [ ] feature request
* [ ] question 

PostGraphile version: 4.0.0-beta.3

Minimal SQL file that can be loaded into a clean database:

```sql

```

Steps to reproduce:

Setup react-apollo project.

Current behavior:

the graphql dependency that is in postgraphile is conflicting with the app I'm writing because it's pretty outdated.

Expected behavior:

would like to see the dependency updated so I can continue working on my project.

**Comment by benjie** [comment]
We support `"graphql": ">=0.6 <0.13"` because we can't go higher due to `codemirror-graphql` for GraphiQL; please forward your concerns here:

https://github.com/graphql/codemirror-graphql

**Comment by barbalex** [comment]
done: https://github.com/graphql/codemirror-graphql/issues/247

**Comment by benjie** [comment]
Wow; I recommend using `yarn` - that should clear up a lot of those duplicates for you. Add graphql@0.13.x to package.json or use the yarn resolutions feature.

**Comment by barbalex** [comment]
@benjie

I _do_ use yarn. And the resolutions feature.

But I messed up by updating the graphql version in the dependencies key to v13.2 while leaving its version in the resolution key at 13.0 :-(

Only noticed thanks to your comment. Thanks!

**Comment by benjie** [comment]
Ahhhh; that explains it!

**Comment by james-ff** [comment]
@barbalex Hi, are you able to share your yarn resolutions fix?

**Comment by barbalex** [comment]
@james-ff : this is my package.json file: https://github.com/barbalex/apf2/blob/34f75b9604389e4b9275811d46c3112be3d2b30f/package.json#L94-L96

The treacherous part of this fix is when you update graphql itself: don't forget to also update the resolution!

**Comment by benjie** [comment]
https://github.com/graphql/graphiql/blob/master/package.json

GraphiQL doesn’t yet though 😔

**Comment by james-ff** [comment]
There's always one =P.

I rest hope in this PR https://github.com/graphql/graphiql/pull/728.
