### ISSUE TITLE
option to not use pg.Pool but use pg.Client

### ISSUE THREAD

**Issue by thewillhuang** [graphile/postgraphile#724]
I'm submitting a ... 

* [ ] bug report
* [x] feature request
* [ ] question 

PostGraphile version:
latest

is it possible to run postgraphile not using pg.Pool? Or close the connection after completing an entire set of queries to complete 1 nested graphql request? Connection management is blah for AWS lambda as containers get booted/frozen that is outside the control of the user leaving many idle connections eventually halting the database due to too many connections. the only alternative is to run pgbouncer but thats an extra cost =/

**Comment by benjie** [comment]
You can end a pool with pool.end(); do you get notified when your lambda instance is being hibernated? How are you running latest on lambda, did you compile it? You can pass client to a lower level interface but errors are handled differently so we still expect a client from a pool. Would welcome some input here as I don’t use lambda.

**Comment by thewillhuang** [comment]
> You can end a pool with pool.end()

im using https://github.com/apex/up which basically converts a standard server into a serverless function, i'll explore to figure out how to call pool.end on every request 

> do you get notified when your lambda instance is being hibernated? 

lambda does not notify when its being hibernated/frozen :(

> How are you running latest on lambda, did you compile it? 

https://github.com/graphile/postgraphile/issues/707

> You can pass client to a lower level interface but errors are handled differently so we still expect a client from a pool.

how do i do that?

> Would welcome some input here as I don’t use lambda.

i think a cli flag or option key that would close connection on each graphql request would be the most flexible way since its possible for a graphql request to be nested and use the connection or connections multiple times to get all the data, it would suck if it had to re-open every time for every sql. it would make sense tho at the end of that graphql request to close it since function as a service can only handle one request per invocation

**Comment by benjie** [comment]
Looks like you should just be able to configure the pgPool with `idleTimeoutMillis: 0.001`:

https://github.com/brianc/node-pg-pool/blob/master/index.js#L25-L44

**Comment by thewillhuang** [comment]
let me try that

**Comment by thewillhuang** [comment]
```js
{
  ...,
  idleTimeoutMillis: 0.001
}
```
along with
```sql
SET SESSION idle_in_transaction_session_timeout = 100;
```
seems to have worked
