### ISSUE TITLE
GraphiQL interface options

### ISSUE THREAD

**Issue by Tritpi** [graphile/postgraphile#726]
1)Is there any command in the GraphiQL interface which is equivalent to Insert,update,delete commands from postgres db?
2) Is there an option to use UNION ALL(postgres operator) in GraphiQL interface?
3) How to check that user doesn't have access to all views for particular schema in PostgraphQL?

**Comment by benjie** [comment]
1. We autogenerate CRUD mutations for you, see:  https://www.graphile.org/postgraphile/crud-mutations/

2. You can achieve this via custom queries, see: https://www.graphile.org/postgraphile/custom-queries/

3. I don't quite follow the question, but I'm guessing it relates to security, see: https://www.graphile.org/postgraphile/security/ and you may also be interested in https://github.com/graphile/graphile-build/pull/199

**Comment by benjie** [comment]
There's `--disable-default-mutations` for the CLI https://www.graphile.org/postgraphile/usage-cli/ or `{disableDefaultMutations: true}` for the library https://www.graphile.org/postgraphile/usage-library/

I encourage you to use PostGraphile v4 - v3 will not be receiving any further updates other than critical security issues.

**Comment by Tritpi** [comment]
Please confirm if the --disable-default-mutations option will also prevent the user from manually mutating data in the DB using  the CRUD mutations.

**Comment by benjie** [comment]
The CRUD mutations will not be present in the GraphQL schema, they literally don't exist, so they can't be used.
