### ISSUE TITLE
Accurate postgraphile typescript typings

### ISSUE THREAD

**Issue by estaub** [graphile/postgraphile#730]
The [doc](https://www.graphile.org/postgraphile/v3-migration/) states:

> Flow and TypeScript typings are not to be trusted right now. They might work... They might not. This will be resolved as part of an ongoing refactoring effort.

I don't see this being tracked anywhere, so here's an issue about it.  

FWIW (very little!), I won't be upgrading till the Typescript typings are real.

**Comment by benjie** [comment]
The TypeScript typings are about as good as the v3 ones I think; they’re just based on a severely out of date TypeScript (like the v3 ones are) so they shouldn’t be trusted. I upgraded TypeScript and there were so many errors I just reverted and got back to doing useful things.

If you want to sponsor getting the typings up to date, please get in touch. PRs doing so (that don’t do significant code restructuring) also welcome.

**Comment by estaub** [comment]
Ah, thanks - I misunderstood, thought you were saying the typings didn't reflect v4.
If you've concern that others may interpret similarly, you might want to tweak the doc.

No money for sponsorship, sorry; I'll PR if/when I run into stuff.
Closing.
