### ISSUE TITLE
Int filters like "greaterThan" missing on BigInt

### ISSUE THREAD

**Issue by MikeFair** [graphile/postgraphile#732]
* [x ] feature request

PostGraphile version: Beta v4

----
It seems as if the comparison operators like "greaterThan" that were added for the Int type are missing for the BigInt type.

Would be great to have them.

**Comment by benjie** [comment]
We don't support greaterThan out of the box, are you referring to this plugin?

https://github.com/graphile-contrib/postgraphile-plugin-connection-filter

If so, please raise the issue there. 🙏

**Comment by MikeFair** [comment]
Yes, I am, sorry about the confusion. Will do.
