### ISSUE TITLE
Avoid auto-generation of some CRUD functionality?

### ISSUE THREAD

**Issue by fictorial** [graphile/postgraphile#739]
I'm submitting a ... 

* [ ] bug report
* [x] feature request
* [ ] question 

PostGraphile version:

4.0.0-beta.5

Is there a way to avoid generation of some of the CRUD functionality (e.g. just create) on some of the tables?  I've a case where I'd rather make it obvious that a custom function registerAccount should be used in lieu of the generated createAccount.

Thanks!

**Comment by benjie** [comment]
It will be in about 2 weeks time 👍 See: https://github.com/graphile/graphile-build/pull/199

**Comment by benjie** [comment]
If you need it before then, check out https://www.graphile.org/postgraphile/extending/#removing-things-from-the-schema

**Comment by fictorial** [comment]
Thanks!

**Comment by hmaurer** [comment]
Close this @benjie ?

**Comment by benjie** [comment]
This is now possible via smart comments, as documented here:

https://www.graphile.org/postgraphile/smart-comments/
