### ISSUE TITLE
Schema is not configured for mutations.

### ISSUE THREAD

**Issue by Sahero** [graphile/postgraphile#748]
I am getting the following error while updating:
```
{
  "errors": [
    {
      "message": "Schema is not configured for mutations.",
      "locations": [
        {
          "line": 1,
          "column": 1
        }
      ]
    }
  ]
}
```

postgraphile version ==> 4.0.0-alpha2.28

**Comment by benjie** [comment]
Please upload the log from the terminal that’s running PostGraphile, and if instructed enable the relevant envvars to see errors.

**Comment by Sahero** [comment]
Thanks for the reply. I am not sure where the log file is located. I cannot stop/kill postgraphile. Is there anyway to do that?
I am running the following command in terminal (centos):
`postgraphile -c postgres://user:password@server/db --watch`

**Comment by benjie** [comment]
You'd kill it like any other CLI program - ctrl-c

There's no log file, I mean the log in the terminal itself, the stuff that comes up when you run the command.

**Comment by benjie** [comment]
The error `Error: Type 'UpdateUserInfoPayload' has already been registered!` implies that you've got two things that are resulting in the same name, for example you might have added a `updateUserInfo` mutation function whilst also having a table called `user_info` which will gain this mutation automatically.

**Comment by Sahero** [comment]
Thank you benjie. That was the problem.
