### ISSUE TITLE
Function returning array with custom type?

### ISSUE THREAD

**Issue by standy** [graphile/postgraphile#752]
I'm submitting a ... 

* [x] bug report
* [ ] feature request
* [x] question 

PostGraphile version: 4.0.0-beta.5

Is it possible to return array with custom type items? Im trying like this

```sql
CREATE TYPE test_item AS (id int4, name text, count int);
CREATE OR REPLACE FUNCTION test()
  RETURNS test_item[] AS $BODY$
BEGIN
  RETURN ARRAY[(1, 'name1', 10)::test_item, (2, 'name2', 20)::test_item];
END
$BODY$
  LANGUAGE plpgsql STABLE
  COST 100;
```
Getting exception: `column __local_0__.id does not exist`

**Comment by benjie** [comment]
Great catch 👍
