### ISSUE TITLE
Documentation code hard to read due to horizontal scrolling

### ISSUE THREAD

**Issue by joevandyk** [graphile/postgraphile#765]
The code at https://www.graphile.org/postgraphile/extending/ is hard to read due to the horizontal scrolling.

http://take.ms/vbNcw is what I see. Is it possible to expand the code window, or make the font smaller?

**Comment by benjie** [comment]
Probably best to reformat the code. It’s in this file:

https://github.com/graphile/graphile.github.io/blob/develop/src/pages/postgraphile/extending.md

**Comment by benjie** [comment]
Docs site is now much wider 👍
