### ISSUE TITLE
Set schema before transaction

### ISSUE THREAD

**Issue by ak-il** [graphile/postgraphile#771]
I'm submitting a ... 

* [ ] bug report
* [ ] feature request
* [x] question 

PostGraphile version:

CLI: 4.0.0-alpha2.30

I need to change the schema based on the user's JWT data.  
I'd like to run something like:
```sql
set search_path to current_setting('jwt.claims.project')
```
before starting the transaction to make sure the queries later are executed against this schema.  
In my setup all schemas have the same tables but the data is different in each of them.  
Ideally I would do the changes [here](https://github.com/graphile/postgraphile/blob/d8d131ed0191841456cd41d24d8a4cf86ba3d8d5/src/postgraphile/withPostGraphileContext.ts#L92) but I was thinking of writing a plugin for this.  
Is it possible to do?

**Comment by benjie** [comment]
I suggest you read my response to a similar request here:

https://github.com/graphile/postgraphile/issues/760#issuecomment-393661313

**Comment by ak-il** [comment]
It is indeed a very similar use case however there is the difference where I don't know the number or names of the clients registered to my application. I wonder if writing a middleware to run a postgraphile instance for each of the clients is a good solution: 
1. I have to somehow fetch all schemas before running the server.
2. I have to run new instances when a new client registers during the runtime.

**Comment by benjie** [comment]
You can register them dynamically as you need them (just in time) I think.

**Comment by ak-il** [comment]
I'll give it a try. If I write an express middleware does it mean I have to use postgraphile as a library and not from the cli?

**Comment by ak-il** [comment]
I see, I think that will do so I'm closing the issue for now. Thanks for the help!
