### ISSUE TITLE
exportGqlSchemaPath with option to remove comments?

### ISSUE THREAD

**Issue by james-ff** [graphile/postgraphile#773]
* [x] feature request

PostGraphile version: 4.0.0-beta.10

Hi, It would be nice to have the option to generate schema files without comments included, would this be relatively simple to add?

Many Thanks

**Comment by benjie** [comment]
We just use printSchema from graphqljs currently; it doesn’t have an option to remove comments. You could add a Graphile-Build plugin to strip all the comments but then you’d have no comments in the running schema also.

**Comment by james-ff** [comment]
I'm sure I can work something out with that, thank you.

For anyone else who is curious I worked out the regex for find all and replace: 
`/"{3}(.|\r|\n)*?"{3}/g`

**Comment by james-ff** [comment]
For anyone that wants to remove comments and remove empty lines =]
```
const typeDefsPath = path.join(__dirname, `./generated/schema.graphql`)
  const typeDefs = importSchema(fs.readFileSync(typeDefsPath, 'utf8'))
  const minified = typeDefs
    .replace(/"{3}(.|\r|\n)*?"{3}/g, '')
    .replace(/^\s*\n/gm, '')
  fs.writeFileSync(`./generated/min/schema.graphql`, minified)
```

**Comment by vitaly-t** [comment]
This library used to rely on [pg-minify](https://github.com/vitaly-t/pg-minify) to remove comments from SQL, but not anymore?

**Comment by benjie** [comment]
This issue relates to GraphQL comments rather than SQL comments, but it’s accurate that we don’t use pg-minify any more, for no reason other than that it’s not necessary for our use case so it wasn’t something I re-added when I rebuilt the project. Still appreciate your work @vitaly-t! 🙏
