### ISSUE TITLE
JWT booleans

### ISSUE THREAD

**Issue by benjie** [graphile/postgraphile#775]
PostGraphile used to support booleans within JWTs. Due to some heavy-handed refactoring I did to improve security and validation, it no longer does; that was a breaking change I didn't realise I'd broken at the time. I need to restore booleans being supported in JWTs in the next release, and use a consistent serialization format for them so we know how to check for them in `current_setting('jwt.claims.my_boolean', true)` within PostgreSQL (because all settings are strings in PostgreSQL). Plan is to check out an old version of PostGraphile, see how booleans are handled, and then make that concrete and explicit in the new code. And then add tests and document it :grin:

**Comment by sjmcdowall** [comment]
Hey @benjie -- Just wondering what this Issue is about?  What abut JWT Booleans? :)  Maybe a little use case story ? :)

**Comment by benjie** [comment]
^ Updated. Sorry it was a note to myself.
