### ISSUE TITLE
Issues handling money types

### ISSUE THREAD

**Issue by jclangst** [graphile/postgraphile#800]
I'm submitting a ... 

* [x] bug report
* [ ] feature request
* [ ] question 

PostGraphile version:
4.0.0-rc.2

Minimal SQL file that can be loaded into a clean database:

```sql

```

Steps to reproduce:

Current behavior:
When querying a field marked as money in Postgres 9.6.8, I get this error: ``Float cannot represent non numeric value``

Expected behavior:
I guess money should be treated as a string vs a float? Don't have the time to track down exactly where this is being thrown, but I will follow up soon -- just wanted to mark this so I don't forget.

**Comment by benjie** [comment]
What are your localisation settings? i think we need to add a pgTweak for money, cast to float before returning. I think I last worked on money support before we had the tweak infrastructure, so it should be much easier than using custom parsers now 🎉

**Comment by benjie** [comment]
@jclangst I think this might be solved by #258 (as described above)

**Comment by jclangst** [comment]
I am going to swing around to looking at this and postgraphile in general today, so I'll run a check on my build that was failing earlier.

**Comment by benjie** [comment]
Great; if it doesn't could you try and reproduce it in the test suite? I suspect you're going to need to change the locale settings to get it to fail; you could copy something like this:

https://github.com/graphile/graphile-build/blob/b3c4d0754f03a1319cfd119c542d4a987bc4df2f/packages/postgraphile-core/__tests__/integration/queries.test.js#L134-L136

But for the variable (?) `lc_monetary` ? Or maybe it needs to be done at `initdb` time. I'm not sure.

**Comment by jclangst** [comment]
Can confirm that this is now working with my setup which uses `C.UTF-8` as the `lc_monetary` setting! Thanks for the quick fix.

I have a quick question about the best way to handle money localization: From scanning your patch, we now convert to numeric on the db end rather than try to parse whatever is returned by the money type natively. However, why not just keep the localization and have money types work as string's on the frontend? What do you think?

Obviously, this would be a breaking change so if that ends up being the most appropriate solution, I'd open a separate issue targeting v5 (though since it appears to have been broken for a while, maybe we could just do this now)?

**Comment by jclangst** [comment]
Also, I'll plan to integrate your changes into https://github.com/graphile/graphile-build/pull/249

**Comment by benjie** [comment]
Money has always worked for me, so I think it’s something environmental that caused the issue. I definitely don’t want to return money in s format that changes based on env; however you could easily implement that as a plugin.

**Comment by jclangst** [comment]
Hm, my understanding is the `lc_monetary` would be the only environmental thing affecting money formatting. Perhaps we had different settings for that?

And I see your point. In our use case, keeping the database formatting works best for use as it allows for a "single source of truth" when it comes to the data and it's formatting. However, I can definitely see the loss of flexibility that would cause.

**Comment by jclangst** [comment]
Absolutely! You are right.
