### ISSUE TITLE
@omit read Crashes postgraphile.

### ISSUE THREAD

**Issue by eliecerthoms** [graphile/postgraphile#813]
I'm submitting a ... 

* [x] bug report
* [ ] feature request
* [ ] question 

PostGraphile version:

Library: postgraphile@4.0.0-rc.2

Minimal SQL file that can be loaded into a clean database:

```sql
CREATE TABLE post (	
	id uuid NOT NULL,
	CONSTRAINT post_pk PRIMARY KEY (id),
);
```

Steps to reproduce:

Add this comment on a primary key or unique constraint
```sql
comment on constraint post_pk on post is 
  E'@omit read';
```
Current behavior:
The server crashes, the schema becomes unavailable in Graphiql and the following error appears: `Error: Query root type must be provided.`

Expected behavior:
I think the expected behavior is for the Query.postById to disappear from the GraphQL Schema.

**Comment by benjie** [comment]
It’s correct to throw an error; but it seems the error is swallowed by the build process so you don’t actually see it, instead seeing a downstream error - fhat is not correct. I’ll take a look, thanks for the report.

**Comment by benjie** [comment]
👍  Have improved error reporting around this.
