### ISSUE TITLE
Hide connection tables in n:n relationships

### ISSUE THREAD

**Issue by saerdnaer** [graphile/postgraphile#819]
I'm submitting a ... 

* [ ] bug report
* [x] feature request
* [x] question 

It it possible to hide connection tables in n:n relations ships? In our example we have the tables articles, tags, and the connection table articles_tags. When I want to query all articles via the tag table I have to take the hop over articles_tags:

```graphql
query {
  allTags {
    nodes {
      text
      articlesTagsByTagId {
        nodes {
          articleByArticleId { 
          	rowId
          	title
          	tags
          }
        }
      }
    }
  }
}
```

I'd like to change this to a direct connection without the need to use articlesTagsByTagId, e.g.
```graphql
query {
  allTags {
    nodes {
      text
      articles { 
         rowId
          title
          tags
          }
        }
      }
    }
  }
}
```
or a similar version with nodes + edges...

Q: Is there a way to hide these connection tables? 

My current workaround is not really nice... (and also returns only one row till I have more time to debug)
```sql
CREATE OR REPLACE FUNCTION tags_articles(t tags, 
	"first" integer DEFAULT 5, 
	"offset" integer DEFAULT 0, 
	"order_by" filter_articles_cms_sort DEFAULT 'publication_date DESC'
)
 RETURNS articles
 LANGUAGE sql
 STABLE
AS $$
  SELECT a.* FROM articles a, articles_tags at 
	WHERE t.id = at.tag_id AND at.article_id = a.id
	ORDER BY "order_by"
	LIMIT first OFFSET "offset"
$$;
```

**Comment by benjie** [comment]
That’s the current recommended way; see https://github.com/graphile/postgraphile/issues/91

Change “returns articles” to “returns setof articles” to get more than one row 👍

**Comment by saerdnaer** [comment]
I tried it before, but it did not work then for unknown reason. But it does now:

```pgsql
CREATE OR REPLACE FUNCTION tags_articles(t tags)
 RETURNS SETOF articles
 LANGUAGE sql
 STABLE
AS $$
	SELECT a.* FROM articles a, articles_tags at
	WHERE t.id = at.tag_id AND at.article_id = a.id
	ORDER BY publication_date DESC
	LIMIT 500
$$;
```
