### ISSUE TITLE
All delegation of JWT logic 

### ISSUE THREAD

**Issue by sjmcdowall** [graphile/postgraphile#825]
I'm submitting a ... 

* [ ] bug report
* [X ] feature request
* [ ] question 

PostGraphile version: 4rc3

-- Library usage --

We process and perform our own JWT generation and validation in a middleware call before postgraphile is in the stack.  Hence, there already is a JWT in the context ready for use.. 

There should be an option to allow a "callback" function (or specify an item in the context) that indicates where to find the already decoded JWT that has the claims already done, etc.  

If the other "validation" JWT options are set I guess it could still do all those too -- as it wouldn't hurt -- but I doubt that would be used too often ..

**Comment by benjie** [comment]
That’s what the pgSettings function is for. Here’s an example of using it with Koa:

https://github.com/graphile/examples/blob/master/server-koa2/middleware/installPostGraphile.js#L30

**Comment by sjmcdowall** [comment]
Ah ha!  So many options so little time! And with Koa even!  :)
