### ISSUE TITLE
Please clarify pricing tiers

### ISSUE THREAD

**Issue by avkonst** [graphile/postgraphile#837]
I'm submitting a ...

* [x] question

Subscription plugin requires supporter tier.

[Here](https://www.graphile.org/postgraphile/pricing/) supporter tier starts from $1. [Here](https://www.patreon.com/benjie) supporter tier is $20. Which one is right?

**Comment by benjie** [comment]
The supporter plugin doesn’t require you to select a tier on Patreon, just to give any amount (pay what you want). I can see now that using the term “supporter” for both of these is confusing, I’ll have a think 👍

**Comment by benjie** [comment]
I've modified the Patreon tiers so that none use the term "sponsor" and clarified some wording on the "Go Pro" page - thanks for the issue 👍
