### ISSUE TITLE
TypeError: Failed to fetch

### ISSUE THREAD

**Issue by raja1206** [graphile/postgraphile#846]
we have  below graphiql url and we are getting below error message in screen. please suggest what is the solution for this.

https://10.82.2.118:5515/graphiql

Error message:
TypeError: Failed to fetch

after press f12 on url:

Failed to load resource: net::ERR_CONTENT_LENGTH_MISMATCH graphql:1 
TypeError: Failed to fetch     main.9dde8a2a.js:15 TypeError: Failed to fetch
Failed to load resource: net::ERR_CONTENT_LENGTH_MISMATCH graphql:1

**Comment by sjmcdowall** [comment]
More information I think will be needed -- how exactly are you starting Postgraphile -- what options, etc?

**Comment by benjie** [comment]
Given you are using https I suspect you’ve also got something else in the mix - maybe a proxy server or node app? In addition to what Steve has requested, could you share details of everything between your web browser and the PostGraphile middleware please?

**Comment by benjie** [comment]
Closing due to lack of input; feel free to re-open with additional details.
