### ISSUE TITLE
Setup Postgraphile on my VPS but can't seem to access, firewall opened

### ISSUE THREAD

**Issue by majestique** [graphile/postgraphile#859]
So the firewall is open and it's the same settings as PostgreSQL, I can access PSQL remotely but I can't seem to access myserver:5000/graphiql remotely.

![image](https://user-images.githubusercontent.com/19336285/45911354-e18ba600-bdc6-11e8-82a9-3541b8f31c7f.png)

I went to http://myserverip:5000/graphiql but it shows:
![image](https://user-images.githubusercontent.com/19336285/45911373-36c7b780-bdc7-11e8-94f6-19b9a01ed9b2.png)

![image](https://user-images.githubusercontent.com/19336285/45912568-6b903a80-bdd8-11e8-8642-b6ba8e5fa490.png)

Also, where can we get support? Is this the only place? I can't seem to a find a forum.

Thanks!

**Comment by benjie** [comment]
> -n, --host <string>
> the hostname to be used. Defaults to localhost

^ This is what you need, set it to 0.0.0.0 to expose to all interfaces.

We have chat for support: http://discord.gg/graphile

I’m going to close this as I think it’s solved but feel free to keep asking questions here 👍
