### ISSUE TITLE
Select Granted Needed For Insert

### ISSUE THREAD

**Issue by sstubbs** [graphile/postgraphile#864]
Hi,

I am not able to insert a record with a role who has an insert grant but does not have a select grant.  I am using version 4.0.0-rc.5.1

**Comment by benjie** [comment]
Yes; currently we do `INSERT INTO table VALUES (...) RETURNING *`; which means (because of the returning) that you need a `SELECT` grant. We document this in the "Requirements" article:

https://www.graphile.org/postgraphile/requirements/

Fear not though; this can be worked around.

### Option 1: Custom Mutation

Create a function to perform the insert but return void:

https://www.graphile.org/postgraphile/custom-mutations/

### Option 2: Schema extension

Use [schema extension](https://www.graphile.org/postgraphile/extending/#makeextendschemaplugin) to implement the changes yourself; e.g. something like:

```js
const { makeExtendSchemaPlugin, gql } = require("graphile-utils");

const MyRegisterUserMutationPlugin =
makeExtendSchemaPlugin(build => {
  const { pgSql: sql } = build;
  return {
    typeDefs: gql`
      input UserInput { name: String!, email: String!, bio: String! }
      input CreateUserInput { user: UserInput! }
      type CreateUserPayload { success: Boolean, query: Query }
      extend type Mutation {
        createUser(input: CreateUserInput!): CreateUserPayload
      }
    `,
    resolvers: {
      Mutation: {
        registerUser: async (
          _query,
          args,
          context,
          resolveInfo,
          { selectGraphQLResultFromTable }
        ) => {
          const { pgClient } = context;
          // Start a sub-transaction
          await pgClient.query("SAVEPOINT graphql_mutation");
          try {
            const { rows: [user] } = await pgClient.query(
              `INSERT INTO app_public.users(
                name, email, bio
              ) VALUES ($1, $2, $3)
              RETURNING *`,
              [
                args.input.user.name,
                args.input.user.email,
                args.input.user.bio,
              ]
            );

            await pgClient.query("RELEASE SAVEPOINT graphql_mutation");

            return {
              success: true,
              query: build.$$isQuery,
            };
          } catch (e) {
            // Oh noes! If at first you don't succeed,
            // destroy all evidence you ever tried.
            await pgClient.query("ROLLBACK TO SAVEPOINT graphql_mutation");
            throw e;
          }
        },
      },
    },
  };
});
```

**Comment by bfelbo** [comment]
Are there any plans to support this w/o a custom mutation / schema extension for each table, where this is needed? Could PostGraphile see that there's no `SELECT` access and not do `RETURNING *`?

**Comment by bfelbo** [comment]
I tried to get around this by using `@omit read`, but got the following error `'update,create,delete,all,many' must be omitted when 'read' is omitted. Add 'update,create,delete,all,many' to the @omit clause, or use '@omit' to omit all actions.` so that approach sadly doesn't work.

**Comment by jemikanegara** [comment]
@bfelbo 

I think you can try use row level security:
`CREATE POLICY user_policy ON table
    USING (false)
    WITH CHECK (true);
`

 https://www.postgresql.org/docs/10/ddl-rowsecurity.html

**Comment by benjie** [comment]
You should check out https://github.com/pyramation/graphile-column-privileges-mutations
