### ISSUE TITLE
Readme renders badly on Docker Hub

### ISSUE THREAD

**Issue by benjie** [graphile/postgraphile#886]

**Comment by V1shvesh** [comment]
Hey @benjie!
I'd like to help you out, but this will be my first contribution to this project.

Can I help you out?

**Comment by benjie** [comment]
Sure; that'd be great! Basically the issue is here:

https://hub.docker.com/r/graphile/postgraphile/

It seems Docker's markdown renderer doesn't support the raw HTML tags we're using. So they just need updating to use the markdown equivalent like the ones that are working. Here's the file to edit:

https://github.com/graphile/postgraphile/blob/master/README.md

Let me know if you need any help - thanks!

**Comment by benjie** [comment]
If necessary we can host a PNG somewhere 👍
