### ISSUE TITLE
Hook on GraphQLInputObjectType

### ISSUE THREAD

**Issue by alexppxela** [graphile/postgraphile#887]
I'm submitting a ... 

* [ ] bug report
* [ ] feature request
* [x] question 

PostGraphile version: 4.0.1

I want to obfuscate my database bigserial ids to clients using hashids (https://hashids.org/). So I have built a hook on my output `GraphQLObjectType:fields:field` and now returned ids are string using the hashid implementation. I want my client to call mutations using this hashid instead of database id.
But there is no hook on my input type to call a function on `GraphQLInputObjectType`.

In the documentation https://www.graphile.org/graphile-build/context-object/#fieldwithhooksfieldname-spec-scope-- there is a addDataGenerator for inputs but this function exists only for `GraphQLObjectType`.
Is there a way to have callback on my inputs before sql calls?

If I add a resolver on an GraphQLObjectType field (like in doc), this graphql error is risen:
```
UpdateDataByIdInput.id field type has a resolve property, but Input Types cannot define resolvers
```

**Comment by alexppxela** [comment]
I think I have found a solution mixing hooks and scalars. I have to work more on it to find a clean solution and will share my updates.

**Comment by benjie** [comment]
Yeah, a custom scalar is the way to solve this 👍. We don’t have hooks on input types currently; I really want to add something but haven’t solved the issue in my head sufficiently yet.

**Comment by alexppxela** [comment]
It works well replacing BigInt field id by the scalar below in hooks on
 - GraphQLInputObjectType:fields:field
 - GraphQLObjectType:fields:field

```typescript
const hashids = new HashIds(`My salt`, 42);
const GraphQLHashidScalarType = new GraphQLScalarType({
    name: 'Hashid',
    description: `This scalar type represents a int id hashed using hashids algorithm`,
    serialize(value: any) {
        return hashids.encode(value);
    },
    parseValue(value: any) {
        return hashids.decode(value.value)[0];
    },
    parseLiteral(value: any) {
        return hashids.decode(value.value)[0];
    }
});
```

**Comment by benjie** [comment]
Awesome 👍
