### ISSUE TITLE
folder structure and migrations

### ISSUE THREAD

**Issue by itaied246** [graphile/postgraphile#890]
[ X ] question

I'm just beginning using `postgraphile` and I was wondering how do you structure the files and folders of the project?
How does the migrations comes in as well?
How do you look at the current state of the db and navigate through all of the sql files?

**Comment by benjie** [comment]
There’s a LOT of ways of doing this, and no particular right or wrong way. Personally I use simple up/down migrations and I inspect the state of the DB directly using psql, pgAdmin, or pgcli.

I’m in the process of building a boilerplate based on the approach I’ve been developing but it’s not ready to show yet. Hopefully it will be by the end of the week... if you’re super curious you can see the beginnings here, but there’s not much in the way of documentation yet.

https://github.com/graphile/bootstrap-react-apollo/blob/master/README.md

**Comment by itaied246** [comment]
What do you think about subzero boilerplate?
Do you think it can be integrated with postgraphile?

https://github.com/subzerocloud/subzero-starter-kit

**Comment by benjie** [comment]
You could certainly use large chunks of it 👍

**Comment by itaied246** [comment]
Ok I'll try it, thanks
