### ISSUE TITLE
Async actions in pgSettings

### ISSUE THREAD

**Issue by itaied246** [graphile/postgraphile#891]
Hello,

Can I execute an async operation in `pgSettings`?
I need to validate the `Authorization` header of the request.
I'm using `firebase`, and it is an async operation.

How can I do it?

**Comment by benjie** [comment]
Yes; just return a promise from `pgSettings`, or mark it as `async`:

```js
app.use(postgraphile(process.env.DATABASE_URL, 'app_public', {
  async pgSettings(req) {
    const result = await fetch("http://...");
    //...
    return {
      role: 'app_visitor',
      'jwt.claims.user_id': 27,
      /* ... */
    };
  }
}));
```
