### ISSUE TITLE
Routes with rowId's don't work after `4.1.0-alpha.1`

### ISSUE THREAD

**Issue by tim-field** [graphile/postgraphile#902]
I'm submitting a ... 

* [x] bug report

I've got some routes that use rowId in the URL 

`/schedules/671`

when I upgrade from  `4.1.0-alpha.1` to  `4.1.0-rc.0` these stop working
```GraphQL
query Queries($rowId_0:Int!) {
  paymentScheduleByRowId(rowId:$rowId_0) {
    id
  }
}
```

variables 
```JSON
{"rowId_0":"671"}
````

I'm using [relay classics react  router relay](https://github.com/relay-tools/react-router-relay) which causes the rowId to be passed as a string.  Postgraphile <= 4.1.0-alpha.1 is fine with this, but >= 4.1.0-rc.0  errors 

Variable $rowId_0" got invalid value "671\"; Expected type Int; Int cannot represent non-integer value: "671"

This makes sense, and I guess is the correct behavior, but it is a breaking change.

**Comment by tim-field** [comment]
:+1:

**Comment by benjie** [comment]
It's typically better to pin all the `graphql`'s to the same version:

```json
  "resolutions": {
    "graphql": "^0.13.0"
  },
```
