### ISSUE TITLE
How to enable --no-ignore-indexes in library usage?

### ISSUE THREAD

**Issue by sJJdGG** [graphile/postgraphile#905]
I'm submitting a ... 

* [ ] bug report
* [ ] feature request
* [x] question

PostGraphile version: 4.1.0-rc.1

How is it possible to enable --no-ignore-indexes and/or --no-ignore-rbac when using postgraphile as a middleware?

**Comment by sJJdGG** [comment]
Thank you for the answer.
I was mostly curious about ignoreIndexes. Since i didn't find anything relatable about --no-ignore-indexes in docs I opened this issue. after your answer I double checked the docs and ignoreRBAC was already documented. But no documentation about ignoreIndexes. Also i checked the source code and right now there is missing ignoreIndexes property in interface PostGraphileOptions in [interfaces.ts](https://github.com/graphile/postgraphile/blob/b3e61ea99d1a73ae02bcbe054afbbd5f066ca3d6/src/interfaces.ts) file. BTW is it possible to also export comments to interfaces.d.ts. It would be a really good enhancement. I use VSCode as my editor and it's already able to show comments in suggestions and snippets. Adding the comments reduce the need to check the docs.

**Comment by benjie** [comment]
IgnoreIndexes is in 4.1 which isn’t out yet, hence the delay in docs; I’m leaving this issue open as a reminder to fix it.

As for exposing the comments, PRs are welcome 👍
