### ISSUE TITLE
Connection to redshift: unrecognized configuration parameter "server_version_num"

### ISSUE THREAD

**Issue by drapadubok** [graphile/postgraphile#913]
I'm submitting a ... 

* [x] bug report
* [ ] feature request
* [ ] question 

PostGraphile version: 4.0.1

Minimal SQL file that can be loaded into a clean database: can't yet get to the SQL part, failure is on startup.

```shell
postgraphile -c "postgres://<user>:<password>@<host>:5439/<db>?ssl=1" -s <schema>
```

Steps to reproduce:
`npm install -g postgraphile`
`postgraphile -c "postgres://<user>:<password>@<host>:5439/<db>?ssl=1" -s <schema>`

Current behavior:
```
error: unrecognized configuration parameter "server_version_num"
    at Connection.parseE (/Users/dmitrysmirnov/.nvm/versions/node/v8.6.0/lib/node_modules/postgraphile/node_modules/pg/lib/connection.js:554:11)
    at Connection.parseMessage (/Users/dmitrysmirnov/.nvm/versions/node/v8.6.0/lib/node_modules/postgraphile/node_modules/pg/lib/connection.js:379:19)
    at TLSSocket.<anonymous> (/Users/dmitrysmirnov/.nvm/versions/node/v8.6.0/lib/node_modules/postgraphile/node_modules/pg/lib/connection.js:119:22)
    at emitOne (events.js:115:13)
    at TLSSocket.emit (events.js:210:7)
    at addChunk (_stream_readable.js:266:12)
    at readableAddChunk (_stream_readable.js:253:11)
    at TLSSocket.Readable.push (_stream_readable.js:211:10)
    at TLSWrap.onread (net.js:587:20)
```
Expected behavior:
Expected it to not crash.

I tried to put DEBUG=* in front of connection command to see something else, but get nothing new apart from what was shown already.

**Comment by benjie** [comment]
We use `server_version_num` to determine what version of PostgreSQL we're talking to; because we cannot use the same introspection query against PG11 as against PG9.6. This is one of the [built in settings](https://www.postgresql.org/docs/9.6/runtime-config-preset.html) in PostgreSQL, but it seems that redshift does not support it.

Can you try:

```sql
ALTER DATABASE current_database_name_here SET server_version_num TO '90600';
```

Replacing `current_database_name_here` with `<db>` from your connection string above. That might trick it into working.

**Comment by drapadubok** [comment]
Thank you for the quick answer! Unfortunately, doesn't seem like Redshift supports the command: `ERROR:  SET/RESET commmand in ALTER DATABASE is not supported`.

**Comment by benjie** [comment]
Okay; then I think we need to wrap this line of code in a try/catch:

https://github.com/graphile/graphile-engine/blob/61957931d236b78c0c8791420d052ae8af22aecf/packages/graphile-build-pg/src/plugins/PgIntrospectionPlugin.js#L227-L229

And fall back to 90600 if it errors. Are you able to try this?

**Comment by drapadubok** [comment]
Sure, I can give it a try, thank you! Let me take a look at the project and set it up, I'll try to make the PR :)

**Comment by benjie** [comment]
Awesome; feel free to reach out for help 👍

**Comment by mattbretl** [comment]
It looks like you can still use `VERSION()`. I haven't used Redshift, but I'm guessing it gives something similar to these:

PostgreSQL 9.5.13 on x86_64-pc-linux-gnu, comp ...
PostgreSQL 9.6.9 on x86_64-pc-linux-gnu, compi ...
PostgreSQL 10.0 on x86_64-pc-linux-gnu, compil ...
PostgreSQL 11.1 (Ubuntu 11.1-1.pgdg18.04+1) on ...
I'd suggest something like instead of hard-coding 90600:

```js
const versionResult = await pgClient.query(
            "show version();"
          );
          const serverVersionNum = parseInt(versionResult.split(' ')[1].split('.').map(s => s.padStart(2, '0')).join("").padEnd(6,'0'),10);
```

**Comment by drapadubok** [comment]
Alright! I get 80002 as a version this way, would that work with the introspection query?

**Comment by mattbretl** [comment]
It will execute the introspection query. But depending on the differences in pg_catalog between PG 9.4 (see https://www.graphile.org/postgraphile/requirements/#postgresql-94-not-officially-supported-but-works) and Redshift-flavored 8.0.2, it might (probably will) throw. Only one way to find out.

**Comment by drapadubok** [comment]
Exciting stuff :D But makes sense, I would expect Redshift users to be quite late to any graphql related party. If it fails I can try to take a look and see if I can fix it (I can also just run the query itself first), but in my PR I get errors from prettier that I am not sure how to fix: https://github.com/graphile/graphile-engine/pull/343
If you can give me any pointers - I'd be happy!

**Comment by benjie** [comment]
PostgreSQL themselves do not support any versions below 9.4 any more:

https://www.postgresql.org/support/versioning/

PostgreSQL v11 will be supported until nearly the end of 2023!

**Comment by drapadubok** [comment]
Ok, I can see that Redshift doesn't provide a some of the tables which are queried in the introspection query (e.g. pg_roles), and when I try to run some parts of it, there might also be some syntactic differences (e.g. array[]). So some reworking would be needed to just make it work. What is the minimal data that is needed from such a query to enable the Postgraphile to work? Since Redshift is a bit of a different beast, would it make sense to have some kind of a different plugin for it?

**Comment by benjie** [comment]
The introspection query now accepts arguments:

https://github.com/graphile/graphile-engine/blob/master/packages/graphile-build-pg/src/plugins/introspectionQuery.js

I think we can completely turn off the pg_role stuff if you don't specify `--no-ignore-rbac`. Similarly the pg_index stuff can be disabled unless `--no-ignore-indexes`. This might be the best way forward.

Ultimately the plan is to make the introspection query fully pluggable so plugins can add additional stuff to it; but we're not there yet.

Are you able to figure out what changes are necessary to the introspection query to make it work against Redshift?

Thanks!

**Comment by drapadubok** [comment]
I should be able to, I think, as long as I understand what is the usage of the results of this query down the line, e.g. if I disable some parts, I might break something down the line that I don't know yet about. I will try to look into it, thank you!

**Comment by benjie** [comment]
Just worry about the introspection query itself; I'll try and clean up the code to support it 👍

**Comment by benjie** [comment]
It seems that Redshift does not have support for JSON:

https://docs.aws.amazon.com/redshift/latest/dg/c_unsupported-postgresql-datatypes.html

Without JSON, PostGraphile will not operate. Sadly, I think this means that we cannot support Redshift. I think the reason for this is that redshift forked from PostgreSQL too early; the minimum PostgreSQL version we work on is v9.4. Sorry @drapadubok!

@drapadubok, can you confirm this lack of JSON support in redshift? Namely we use `to_json(...)` and `json_build_object(...)` a lot.

**Comment by benjie** [comment]
You’re welcome 🙂
