### ISSUE TITLE
Hooks on auto-generation CRUD function

### ISSUE THREAD

**Issue by bingzheaaa** [graphile/postgraphile#915]
I'm submitting a ... 

* [ ] bug report
* [x] feature request
* [] question 

PostGraphile version:4.0.1

in some auto-generation CRUD function i need to do some more work, like add push message

**Comment by benjie** [comment]
Totally. You can do that already via [resolver wrapping](https://www.graphile.org/postgraphile/extending-raw/#wrapping-an-existing-resolver), but it's not as easy as it could be. I've got adding a helper for that on my todo list:

https://github.com/graphile/graphile-engine/issues/342

I'm closing this in favour of the above issue, but thanks for reporting 👍
