### ISSUE TITLE
how to raise error from postgraphile with custom response status code

### ISSUE THREAD

**Issue by srghma** [graphile/postgraphile#929]
I'm submitting a ... 

* [ ] bug report
* [ ] feature request
* [x] question 

PostGraphile version: 4.0.1

______________________________________________

I want to be able to signal client application that current user is not authenticated using 403 status code (because 401 status code is already used to signal that jwt is expired)
https://github.com/graphile/postgraphile/blob/39eb0449831c97c9c38d7ff7a9492cf460ef978d/src/postgraphile/withPostGraphileContext.ts#L290-L295

Minimal code to reproduce:

```sql
create or replace function app_public.current_user_id_required() returns integer as $function$
  -- will
  -- raise error 'Not authenticated' using errcode = 'insufficient_privilege'
  -- work?

  select current_setting('jwt.claims.user_id', false)::integer;
$function$ LANGUAGE sql stable;

comment on function app_public.current_user_id_required() is
  '@omit
Get current user id or raise error that returns 403 status code';

grant execute on function app_public.current_user_id_required() to public;
```

Expected:

403 status code

Actual:
200 status code

![2018-11-26-14 16 27-screenshot](https://user-images.githubusercontent.com/7573215/49013587-f5b4a080-f185-11e8-91be-7afa4eb94023.png)

**Comment by benjie** [comment]
In my opinion, that's not really the GraphQL way to do things; the reason is that your query (or mutation) can contain multiple actions, and it's possible for some to succeed whilst others fail. This "partial success" feature is one of the founding principles of GraphQL. It's the reason that GraphQL is nullable by default, and rather than having just an error response, it has a list of errors and the path to the fields that threw them.

If the user is not allowed to do anything unless they are authenticated then this is an application-level concern in my opinion; and I'd solve this with a piece of Node.js middleware that runs before the GraphQL is resolved and aborts if the user is not authenticated.

If, however, the user may perform certain actions but not others then that should be handled using the GraphQL errors functionality - since the errors will be local to what the user was not allowed to do, rather than the entire request.

The above is only my opinion; if I've failed to convince you and you'd still like to know how to change the status code, let me know - there are definitely ways to accomplish this with PostGraphile.

**Comment by srghma** [comment]
@benjie you haven't failed to convince me, but still please tell me a way to accomplish this

_______________

re `Node.js middleware that runs before the GraphQL is resolved and aborts if the user is not authenticated.`
- this doesn't work for me, I don't want to 403 ALL requests to graphql, I want to 403 them only if some of them call `current_user_id_required` function

**Comment by benjie** [comment]
You can accomplish this using the `handleErrors` function; it's poorly documented but here's where it's called:

https://github.com/graphile/postgraphile/blob/d66537febb6a16d122e8bb272251f12285da5922/src/postgraphile/http/createPostGraphileHttpRequestHandler.ts#L719

As you can see, it's passed the list of errors generated from GraphQL, and the `req` and `res` objects. So you can do:

```js
handleErrors: (errors, req, res) => {
  if (errors.some(error => isForbiddenError(error))) {
    res.statusCode = 403;
  }
  return errors;
}
```

Note that if you use handleErrors then the other error handling functionality is bypassed; if you need that you will need to reimplement it:

https://github.com/graphile/postgraphile/blob/d66537febb6a16d122e8bb272251f12285da5922/src/postgraphile/http/createPostGraphileHttpRequestHandler.ts#L199-L221

**Comment by srghma** [comment]
Tnx for help, i decided not to return 403 for all request, my use case (currentUser shouldn't be null, but it's null) is really client error, you was right

**Comment by machineghost** [comment]
Just a note: the only documentation of `handleErrors` is in this ticket :+1: 

You won't even find the callback's signature anywhere in the docs ...

    handleErrors: (errors, req, res) => {
      if (errors.some(error => isForbiddenError(error))) {
        res.statusCode = 403;
      }
      return errors;
    }

... but it would be nice if you could :)

**Comment by benjie** [comment]
Here’s an example handleErrors function: https://github.com/graphile/starter/blob/main/%40app/server/src/utils/handleErrors.ts

The errors themselves come from GraphQL-js wrapping whatever errors were thrown. They each have an originalError property for the unwrapped error: https://github.com/graphql/graphql-js/issues/251

**Comment by machineghost** [comment]
That's great, thank you, but I'm not sure it addresses the ticket.  Obviously source code `!==` documentation, so I still think documentation is needed.  Perhaps more importantly though, I don't see the parameters passed to the custom function in this list:

        "code",
        "severity",
        "detail",
        "hint",
        "positon",
        "internalPosition",
        "internalQuery",
        "where",
        "schema",
        "table",
        "column",
        "dataType",
        "constraint",

**Comment by benjie** [comment]
Those properties come from the errors generated by the `pg` module, if you can find reference to their documentation within the pg module a link out to them would be appreciated. They're based on the [error and notice message fields](https://www.postgresql.org/docs/current/protocol-error-fields.html) that PostgreSQL provides.

It would be incredibly helpful if you opened a pull request to the documentation with what you've learned and what you feel is useful for others to know. The documentation repo is here: https://github.com/graphile/graphile.github.io and you'll notice at the top of every page in the documentation is a "suggest improvements to this page" link which will guide you through the process to update that specific page in the docs.
