### ISSUE TITLE
Add hint when a foreign key relation is skipped due to missing index

### ISSUE THREAD

**Issue by ValeriaVG** [graphile/postgraphile#942]
I'm submitting a ... 

* [ ] bug report
* [x] feature request
* [ ] question 

PostGraphile version: 4.1.0
Pg version: 9.6.6

Minimal SQL file that can be loaded into a clean database:

```sql
CREATE TABLE app_test.entity (
	id serial,
	name varchar(255),
	categoryId integer,
	CONSTRAINT entity_pk PRIMARY KEY(id)
); 
CREATE TABLE app_test.category (
	id serial,
	name varchar(255),
	CONSTRAINT category_pk PRIMARY KEY(id)
);
ALTER TABLE app_test.entity ADD CONSTRAINT entity_category_fkey FOREIGN KEY (category_id) REFERENCES app_test.category ON DELETE SET NULL ON UPDATE CASCADE;
-- Adding an index on category_id fixes the issue
```

Steps to reproduce:
```js
const http = require('http')
const { postgraphile } = require('postgraphile')
const port = process.env.PORT
http
  .createServer(
    postgraphile(
      process.env.DATABASE_URL,
      {
        watchPg: true,
        graphiql: true,
        dynamicJson: true,
        ignoreIndexes: false, // Setting this to true fixes the issue
        exportGqlSchemaPath: './schema.graphql',
        enhanceGraphiql: true,
      }
    )
  )
  .listen(port)
console.log(`Listening on http://localhost:${port}/graphiql`)
```

Current behavior (generated schema):
```
type Entity implements Node {
  """
  A globally unique identifier. Can be used in various places throughout the system to identify this single value.
  """
  nodeId: ID!
  id: Int!
  name: String
  categoryId: Int
}
```

Expected behavior:

```
type Entity implements Node {
  """
  A globally unique identifier. Can be used in various places throughout the system to identify this single value.
  """
  nodeId: ID!
  id: Int!
  name: String
  categoryId: Int
  categoryByCategoryId: Category
}
```

UPD: After further thinking, I believe that instead of implementing support for that it's be better to see a warning: `Skipping relation "relation_name" because index was not found ...`

**Comment by benjie** [comment]
This is definitely not a bug - it is exactly what `ignoreIndexes: false` is supposed to do, because foreign keys don’t have indexes by default and using them without an index can be expensive. I think I agree that it should tell you it skipped it though... but we shouldn’t take it too far, e.g. telling you about every orderBy that’s been omitted due to lack of index would be overwhelming.

**Comment by ValeriaVG** [comment]
@benjie totally agree. The warning should appear only in case the relation is skipped

**Comment by benjie** [comment]
Turns out we already had this behind a DEBUG flag; I'm going to raise it to a perma-console.log and if people complain we can discuss ways to reduce the logging.

**Comment by tinymarsracing** [comment]
I came here to complain about all the logging which I wanted to reduce. :-P No, but seriously, I was gonna ask if there was an additional flag to turn off the logging because I get tons of warnings for all my "enum tables" that are just for validating a single field.

**Comment by benjie** [comment]
@tinymarsracing If you wanted to open a PR for this (against `graphile-engine`) which made a flag that skipped these errors, I'd be happy to give you guidance. If you want to do this, the first step would be to open an issue against Graphile Engine stating your intent :)

Another way to turn the errors off is to mark the relevant things as `@omit`-ed with smart comments. (At least I think that would work; untested.)
