### ISSUE TITLE
Custom logger

### ISSUE THREAD

**Issue by sdwvit** [graphile/postgraphile#947]
I'm submitting a feature request

PostGraphile version: 4.2.0

Hello, I would like to request a feature, which is custom logger instead of console.log.
If you look at createPostGraphileHttpRequestHandler.js, it uses standard console.log/error to print info about executed queries. Would be cool to have ability to provide custom logger to send logs elsewhere except for stdout (in my case - logstash). 

Right now the only way around is to monkey-patch standard console methods.

PS: thank you so much for this library, I enjoy learning graphql with it <3

**Comment by benjie** [comment]
You should disable the default logging and instead add your own logging solution as middleware before mounting PostGraphile as an Express or similar middleware. There are hundreds of logging middlewares available for Express so I’m sure you can find one that suits your needs.

If this solution is not to your taste, could you expand on the type of logging you need?

**Comment by sdwvit** [comment]
@benjie ok this works too, thanks. Would be nice to have a paragraph in docs which says what you just said.

**Comment by benjie** [comment]
If you can, press the “suggest improvements to this page” link at the top of the relevant page and submit a PR - that’d be much appreciated 👍
