### ISSUE TITLE
Issues integrating with gatsby-source-graphql

### ISSUE THREAD

**Issue by jeremyeng** [graphile/postgraphile#949]
I'm submitting a ... 

* [x] bug report
* [ ] feature request
* [ ] question 

PostGraphile version: 4.1.0

Steps to reproduce:

0. Create a Gatsby project and install the gatsby-source-graphql plugin
1. Run postgraphile through the CLI
2. In a Gatsby project, add the following to gatsby-config.js:
`{
      resolve: "gatsby-source-graphql",
      options: {
        typeName: "PostGraphile",
        fieldName: "postgraphile",
        url: "http://localhost:5000/graphql",
      },
    },`
3. Run command `gatsby develop`

When I attempt to integrate my postgraphile GraphQL API with Gatsby using the gatsby-source-graphq plugin as shown above, I get the error `Schema must contain unique named types but contains multiple types named "Query".`

However, when I use the  [gatsby-source-pg](https://github.com/graphile/gatsby-source-pg) plugin, everything seems to work fine.

**Comment by benjie** [comment]
This is an issue with gatsby-source-graphql; namely it does not rename the operation object types. Try using gatsby-source-pg instead, this works around the issue 😁
