### ISSUE TITLE
Warn user when they pass `undefined` schema in library mode

### ISSUE THREAD

**Issue by marshall007** [graphile/postgraphile#951]
I'm submitting a ... 

* [x] bug report
* [ ] feature request
* [ ] question 

**PostGraphile version:** `v4.1.0`

**Steps to reproduce:**

```ts
import postgraphile from 'postgraphile';
import { createServer } from 'http';

const {
  PORT,
  POSTGRES_DB,
  POSTGRES_PASSWORD,
  POSTGRES_USER,
  POSTGRES_HOST,
  POSTGRES_SCHEMA,
} = process.env;

const POSTGRES_CONNECTION_STRING = `postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}/${POSTGRES_DB}`;

const app = createServer(
  postgraphile(POSTGRES_CONNECTION_STRING, POSTGRES_SCHEMA, {
    graphiql: true,
    enhanceGraphiql: true,
  }),
);

const port = PORT || 5000;

app.listen(port, (err?: Error) => {
  if (err != null) console.error(err);
  console.log(`Listening on http://localhost:${port}`);
});
```

**Current behavior:**

When using as a library (as demonstrated above), if the second argument to `postgraphile` is `undefined`, the server _appears_ to start successfully and responds to requests at `/graphql`, but does not serve the UI at `/graphiql`.

In this case, it took me a while to realize I was not setting the `POSTGRES_SCHEMA` environment variable and that it was causing the problem.

**Expected behavior:**

Invalid configuration should immediately throw and prevent the server from starting all together.

**Comment by benjie** [comment]
Could you expand on “does not serve the UI”? Do you get an error?

PostGraphile will fall back to the “public” schema if no schema is passed, this is the desired behaviour. So you should see a (empty schema’d?) GraphiQL when you visit. Seeing no GraphiQL at all is definitely unexpected, hence the request to clarify. Feel free to attach screenshot.

**Comment by marshall007** [comment]
@benjie right, the GraphiQL UI is not served up at all in this case. Visiting `/graphiql` results in the standard Node HTTP 404 error:

```
Cannot GET /graphiql
```

I would also argue that while using the `public` schema is desirable default behavior via other configuration mechanisms, library usage where schema is the second parameter should probably at least warn, if not error, when the second parameter is `undefined`. In this scenario, it's much more likely that the user _accidentally_ passed an `undefined` value (as I did), not `undefined` explicitly.

**Comment by benjie** [comment]
I think I agree with you, IFF the third argument is specified. Definitely an error at least.

**Comment by benjie** [comment]
postgraphile@next (4.3.1) is now out; please see if this is solved and report back 👍
