### ISSUE TITLE
Add a hook for custom logging of successful requests and errors

### ISSUE THREAD

**Issue by bfelbo** [graphile/postgraphile#962]
I'm submitting a ...

* [ ] bug report
* [x] feature request
* [ ] question

PostGraphile version (library): 4.2

First of all, thanks for an amazing project! We're using postgraphile in production and loving it.

One issue we have is that we want to log whether a request was successfully processed or if it failed. For this purpose, we'd love to have hooks/callback functions that we can supply to Postgraphile and that'll then be called when sending a response.

For logging/debugging purposes, it would be great to have the status code and message being sent (incl. data). The simplest thing I can think of is to call the callback function with the response object in [line 786 of createPostGraphileHttpRequestHandler.ts](https://github.com/graphile/postgraphile/blob/master/src/postgraphile/http/createPostGraphileHttpRequestHandler.ts#L786) and the response value (`returnArray ? results : results[0]!`). This should hopefully require minimal maintenance as the response object is unlikely to change.

Some users might want the additional info in the built-in query log [here](https://github.com/graphile/postgraphile/blob/master/src/postgraphile/http/createPostGraphileHttpRequestHandler.ts#L732-L737), but for our purposes at least, that's not needed. It might be too expensive to prettify the query etc. so we'd prefer not to have the callback/hook get this information.

Would this implementation make sense? If so, should I just add an additional key to the options object with a callback function?

**Comment by benjie** [comment]
@bfelbo Do you think these hooks will be sufficient? (#970)

https://github.com/graphile/postgraphile/pull/970/commits/8749ddd94988aa3b83654cd41a77937b322c4e9d

You can read about writing server plugins here:

https://www.graphile.org/postgraphile/plugins/#writing-your-own-plugins

You could make a plugin that exposed this in a convenient way, or that just logged out using your preferred architecture.

**Comment by bfelbo** [comment]
@benjie Yes, those hooks look great. Thanks!

I'm looking into making a plugin right now.

**Comment by bfelbo** [comment]
Actually, could we also pass `req` to the hook here https://github.com/graphile/postgraphile/blob/722428b91203d35d5769cd4742282c985f385547/src/postgraphile/http/createPostGraphileHttpRequestHandler.ts#L793 ? We save the request UUID, user ID etc. in the request object, which we need for logging.

**Comment by benjie** [comment]
Absolutely 👍

**Comment by benjie** [comment]
Added in latest commit.

**Comment by benjie** [comment]
postgraphile@next (4.3.1) is now out; please see if this is solved and report back 👍

**Comment by bfelbo** [comment]
It works, thanks. Could this be pushed after `res.end` (i.e.  https://github.com/graphile/postgraphile/blob/244c1cbd8346fc5ee8813efa68e65a5897da36ed/src/postgraphile/http/createPostGraphileHttpRequestHandler.ts#L814)?

This would prevent any logic that the hook has from slowing down the response and causing issues.

**Comment by benjie** [comment]
We’d have to add another hook for that; this one allows you to modify the HTTP results should you need to. But TBH you can just put your code in a setImmediate, so I probably wouldn’t add another hook.

**Comment by bfelbo** [comment]
Good point. However, I think a separate hook would make sense. For instance, suppose I want to add a 3rd party logging plugin to my postgraphile setup. It'd be great if I could set it up to use a post-response hook so I know with certainty that:

1) This logging plugin can never mess with my response sending.
2) This logging plugin will only ever be called after sending response, i.e. I'll have certainty the response was sent.
3) This logging plugin won't be able to cause latency issues for my API.

I wouldn't like to rely on the plugin's authors having used setImmediate (or similar), especially as they might change their implementation in a later release without me noticing when updating.

**Comment by bfelbo** [comment]
Yep, I'm hooking on `postgraphile:http:handler` as well. You can see the current state of the plugin here: https://github.com/RuneAI/postgraphile-callback-plugin (very much WIP).

**Comment by bfelbo** [comment]
I only need this for requests handled by postgraphile though so I'll need to clean up whatever is sent to the `on-finished` callback. It won't be as clean as a hook, but I guess it works :)

**Comment by benjie** [comment]
Try `req.res` :)
