### ISSUE TITLE
Intelligently order execution of mutations

### ISSUE THREAD

**Issue by marshall007** [graphile/postgraphile#966]
I'm submitting a ... 

* [ ] bug report
* [x] feature request
* [ ] question 

**Current behavior:**

When multiple mutations are called in the same GraphQL query, these mutations are performed in parallel in separate transactions.

**Expected behavior:**

In the following example, `posts` has a foreign key to the `users` table, and the `user` must be inserted first in order to avoid FK violations.

```gql
mutation CreateUserAndPost(
  $auid: String!
  $body: String!
) {
  user: createUser(input: {
    user: {
      auid: $auid
    }
  }) {
    user {
      nodeId
    }
  }

  post: createPost(input: {
    post: {
      userId: $auid
      body: $body
    }
  }) {
    post {
      nodeId
    }
  }
}
```

Briefly looking at the code, I think we should be able to detect multi-mutation queries against related entities, intelligently sort them, and execute all of them under a single transaction.

**Comment by benjie** [comment]
The current behaviour follows the GraphQL spec: the fields in the root selection set are resolved one at a time in order (not in parallel). This achieves the goal you desire (ordering) and is also spec compliant. You can read the relevant part of the GraphQL spec here:

https://facebook.github.io/graphql/draft/#sec-Mutation

**Comment by benjie** [comment]
I think this issue is the result of a miscommunication on my part in chat, so I shall close it 👍

**Comment by marshall007** [comment]
@benjie the request was more around being able to wrap multiple mutations in a single transaction (intelligent execution order being a nice addition), but I agree it looks like this couldn't be done in a spec-compliant way since each mutation is expected to have side-effects.

The use case is the ability to easily retry mutation queries without having to parse out a potential partial success response and only retry failed portions.

**Comment by benjie** [comment]
The GraphQL way to deal with this is to handle related actions in a single mutation field only. The PostGraphile way typically employed to achieve this is to use custom mutations; the built in CRUD mutations are a convenience but they are not intended to handle all use cases in a complex app, this is why we have such strong support for PostgreSQL functions 👍
