### ISSUE TITLE
Create a Rest API with Postgraphile as building block

### ISSUE THREAD

**Issue by madflow** [graphile/postgraphile#967]
I'm submitting a ... 

* [ ] bug report
* [ ] feature request
* [x ] question 

I am evaluating Postgraphile for our company project.  We have an existing REST Api - which I would like to migrate as well and get rid of a lot of boilerplate code. I cannot use Postgrest.

I am planning on using Express with Postgraphile mounted as middleware.

Postgraphile would live under `/graphql` and the Rest API under `/rest/{endpoint}`

When I have a table "customers" and a table "projects" (the customer projects) this query:

```
{
  allCustomers {
    nodes {
      name
      projectsByCustomerId {
        nodes {
          name
        }
      }
    }
  }
}

{
  "data": {
    "allCustomers": {
      "nodes": [
        {
          "name": "Mega Corp",
          "projectsByCustomerId": {
            "nodes": [
              {
                "name": "Mega Corp Project"
              }
            ]
          }
        },
        {
          "name": "Super Corp",
          "projectsByCustomerId": {
            "nodes": [
              {
                "name": "Super Corp First Project"
              },
              {
                "name": "Super Corp Second Project"
              }
            ]
          }
        }
      ]
    }
  }
}

```

would translate into

GET `/customers`

```JSON
{
    "rows": [
        {
            "name": "Mega Corp",
            "customer_id":1,
            "_links": {
                "_self": "/customers/1",
                "projects": "/projects/?customer_id=1"
            }
        },
        {
            "name": "Super Corp",
            "customer_id":2,
            "_links": {
                "_self": "/customers/1",
                "projects": "/projects/?customer_id=2"
            }
        }
    ]
}
```
And

`GET /projects/?customer_id=1`

```JSON
{
    "rows": [
        {
            "name": "Mega Corp Project",
            "project_id":1,
            "_links": {
                "_self": "/projects/1",
                "customer": "/customers/1"
            }
        }
    ]
}
```

As far as I can see Postgraphile and Express have all the building blocks to do this - But I could be mistaken.

Is there a way I can access the introspection and query layer from Postgraphile to accomplish something like this?

I had the idea when comparing Prisma (https://www.prisma.io/with-rest/) which simply provides an ORM layer for such a task.

**Comment by madflow** [comment]
@benjie Thanks! This makes sense... I think this is more than enough to get me started ;)

**Comment by benjie** [comment]
Let me know how it goes!
