### ISSUE TITLE
introspection

### ISSUE THREAD

**Issue by nahmias** [graphile/postgraphile#971]
I'm submitting a ... 

* [ ] bug report
* [ ] feature request
* [x] question

PostGraphile version: 4.0.1

Is there a way to disable introspection?

**Comment by benjie** [comment]
Database introspection can be disabled with the readCache option.

GraphQL introspection can be prevented by mounting an Express (or similar) middleware before PostGraphile and detecting introspection requests and preventing them. Personally I’d use persisted queries instead:

https://www.graphile.org/postgraphile/production/#simple-query-whitelist-persisted-queries

**Comment by nahmias** [comment]
thanks a lot

**Comment by ssnavalakha** [comment]
how do I detect introspection requests?

**Comment by benjie** [comment]
Introspection requests use the `__type` or `__schema` field. Walk the GraphQL document and look for one of these field names (NOT ALIASES).
