### ISSUE TITLE
Inflection error when running jest and mocking postgraphile

### ISSUE THREAD

**Issue by jeremie-stratumn** [graphile/postgraphile#973]
I'm submitting a ... 

* [x] bug report
* [ ] feature request
* [ ] question 

PostGraphile version: 4.3.0

Steps to reproduce:
```javascript
// plugin.ts
import { makePluginHook } from 'postgraphile';
import PostGraphileSupporter from '@graphile/supporter';

export default makePluginHook([PostGraphileSupporter]);
```
```javascript
// plugin.test.ts
import { mocked } from 'ts-jest/utils';
import { makePluginHook } from 'postgraphile';
import PostGraphileSupporter from '@graphile/supporter';

jest.mock('postgraphile');
const mockMakePluginHook = mocked(makePluginHook);

describe('my plugin', () => {
  it('initialize correctly', () => {
    require('.');
    expect(mockMakePluginHook).toBeCalled();
    expect(mockMakePluginHook).toBeCalledWith([PostGraphileSupporter]);
  });
});
```

Current behavior:
when running the above test I get the following error:
`Passing an inflector via PostGraphile options was deprecated in v4.0.0-beta.7; instead please write an inflector plugin: https://www.graphile.org/postgraphile/inflection/`
I suspect this is coming from the `jest.mock('postgraphile')` line.

Expected behavior:
This test was working with v4.1.0 that I was using previously.

**Comment by benjie** [comment]
This is fixed in master; this is the main reason 4.3.0 is not postgraphile@latest.

**Comment by benjie** [comment]
postgraphile@next (4.3.1) is now out; please see if this is solved and report back 👍

**Comment by jeremie-stratumn** [comment]
Yep works like a charm! thanks a lot

**Comment by benjie** [comment]
Thanks @jeremie-stratumn
