### ISSUE TITLE
documentation search is broken

### ISSUE THREAD

**Issue by stlbucket** [graphile/postgraphile#977]
I'm submitting a ... 

* [X ] bug report
* [ ] feature request
* [ ] question 

the search box on the help page appears broken:

![image](https://user-images.githubusercontent.com/2467892/51794581-7c87f880-218a-11e9-97f7-010cbc225711.png)

no matter what i select, nothing happens:

![image](https://user-images.githubusercontent.com/2467892/51794585-97f30380-218a-11e9-8cda-45eae4d5cb02.png)

search does nothing whether i hit return or click on a topic

i've verified this on chrome and firefox

**Comment by benjie** [comment]
Thanks for the report 👍
