### ISSUE TITLE
Handling ARRAY of TEXT (and of other data types)

### ISSUE THREAD

**Issue by sfkeller** [graphile/postgraphile#985]
I'm submitting a ... 

* [ ] bug report
* [x] feature request
* [x] question

PostGraphile version: 4.0.0

Is it possible to handle arrays? 

Tags e.g. are sometimes stored in an attribute of type array (of text) in PosgreSQL, like this "create table foo (id int, tags text[]);". Basically, in PG, any data type can be an array by adding "[]"

And I'd like to have a JSON query result in like this:
```
{
    "id": 1,
    "tags": ["aaa", "bbb"]
}

```

**Comment by casmadtt** [comment]
Yes it is. Currently handling tags the exact same way through custom mutations. Working perfectly!

postgraphile: ^4.0.1
postgres 10+

**Comment by benjie** [comment]
Have confirmed this already works using your SQL snippet.

```
createdb issue-985
psql issue-985 -c "create table foo (id int, tags text[]);"
postgraphile -c issue-985 -X --export-schema-graphql ./985.graphql
```

```graphql
# ...
type Foo {
  id: Int
  tags: [String]
}
# ...
input FooInput {
  id: Int
  tags: [String]
}
# ...
```
