### ISSUE TITLE
watchPg option break fastify in http2 mode

### ISSUE THREAD

**Issue by nemesisqp** [graphile/postgraphile#994]
When using Postgresphile with `watchPg: true` with fastify `http2: true` I got this error 
`TypeError [ERR_HTTP2_INVALID_CONNECTION_HEADERS]: HTTP/1 Connection specific headers are forbidden: "connection"`
culprit:
https://github.com/graphile/postgraphile/blob/419280d6afc7d12813a461350aaf11561b273eb3/src/postgraphile/http/setupServerSentEvents.ts#L22
I am temporary abort Postgresphile stream
```javascript
fastify.use(function blockPostgraphileStream(req, reply, next) {
    if (req.originalUrl === '/graphql/stream' || req.originalUrl === '/_postgraphile/stream') {
        reply.writeHead(405);
        return;
    }
    next();
});
```

**Comment by benjie** [comment]
We don't currently have explicit support for HTTP2, and frustratingly our test library does not support HTTP2:

https://github.com/visionmedia/supertest/issues/429

**Comment by benjie** [comment]
Fixed in https://github.com/graphile/postgraphile/pull/1009
