### ISSUE TITLE
Permission denied for database when database is correct

### ISSUE THREAD

**Issue by brynbeaudry** [graphile/postgraphile#996]
I'm submitting a ... 

* [ ] bug report
* [ ] feature request
* [x ] question 

PostGraphile version:
4.2.0

Using as library and following forum example

Permission denied for database when remote connection with valid string used as rootPgPool connection string:

from forum example: 
console.log(`Connection String : ${process.env.AWS_CONNECTION_URL}`)
const rootPgPool = new pg.Pool({
  connectionString: process.env.AWS_CONNECTION_URL,
});

can confirm connection string connects using:
psql "<process.env.AWS_CONNECTION_URL>"

One difference from the forum example is that I am using JWTS, and have got them to correctly protect resources locally with the setup. Now I am using a remote database. 

in installPostGraphile.js:
...
jwtSecret: process.env.JWT_SECRET,
      jwtPgTypeIdentifier: 'app_public.jwt_token',
      jwtVerifyOptions: {
        audience : ['agora']
      },

      // Given a request object, returns the settings to set within the
      // Postgres transaction used by GraphQL.
      pgSettings(req) {
...

I have used a modified setup .sh and some other scripts to connect to the remote database successfully, creates the schemas, tables, roles and permissions on that database.

But running 'yarn start' within the project now gives the following error when I actually want to run the process to start server graphql.

Current behavior:
Loaded watch fixtures ✅
Ignore the "Failed to setup watch fixtures" warning
A fatal error occurred when building the initial schema, so the process will now exit. Error details:

Error: Could not find JWT type '"app_public"."jwt_token"'
    at PgJWTPlugin.builder.hook (/Users/brynbeaudry/agora/node_modules/graphile-build-pg/src/plugins/PgJWTPlugin.js:43:13)
    at SchemaBuilder.hook [as applyHooks] (/Users/brynbeaudry/agora/node_modules/graphile-build/src/SchemaBuilder.js:268:20)
    at SchemaBuilder.applyHooks [as createBuild] (/Users/brynbeaudry/agora/node_modules/graphile-build/src/SchemaBuilder.js:325:10)
    at SchemaBuilder.createBuild (/Users/brynbeaudry/agora/node_modules/graphile-build/src/SchemaBuilder.js:331:26)
    at SchemaBuilder.buildSchema (/Users/brynbeaudry/agora/node_modules/graphile-build/src/SchemaBuilder.js:389:32)
    at process.internalTickCallback (internal/process/next_tick.js:77:7)

Expected behavior:
Serve graphql and graphiql at localhost:port

**Comment by benjie** [comment]
Can you share your full `postgraphile` library code, particularly the call to `postgraphile` itself and the definition of any variables used? The `rootPgPool` is not normally what is used with PostGraphile because its privileges are too elevated (hence "root") - typically you use rootPgPool for authentication tasks like Passport.js.

**Comment by brynbeaudry** [comment]
This is the call to postgraphile. The connection string has root as the user for now.

`const { postgraphile } = require("postgraphile");
const PassportLoginPlugin = require("../plugins/PassportLoginPlugin");
const {
  library: { connection, schema, options },
} = require("../../.postgraphilerc.js");``
const jwt = require("jsonwebtoken");

module.exports = function installPostGraphile(app, { rootPgPool }) {
  app.use((ctx, next) => {
    // PostGraphile deals with (req, res) but we want access to sessions from `pgSettings`, so we make the ctx available on req.
    ctx.req.ctx = ctx;
    return next();
  });

  app.use(
    postgraphile(connection, schema, {
      // Import our shared options
      ...options,

      // Since we're using sessions we'll also want our login plugin
      appendPlugins: [
        // All the plugins in our shared config
        ...(options.appendPlugins || []),

        // Adds the `login` mutation to enable users to log in
        PassportLoginPlugin,
      ],
      jwtSecret: process.env.JWT_SECRET,
      jwtPgTypeIdentifier: 'app_public.jwt_token',
      jwtVerifyOptions: {
        audience : ['agora']
      },

      // Given a request object, returns the settings to set within the
      // Postgres transaction used by GraphQL.
      pgSettings(req) {
        //console.log(`-------------------------------------------------------------------`)
        //console.log(JSON.stringify(req.headers))
        let authHeader = req.headers["authorization"]
        //console.log(`AuthHeader: ${authHeader}`)
        let token = (authHeader && authHeader.startsWith("Bearer ")) ? authHeader.substring(7, authHeader.length) : null
        //console.log(`Token: ${token}`)
        let jwt_user = (token) ? jwt.verify(token, process.env.JWT_SECRET) : null;
        //console.log(jwt_user)
        return {

          "jwt.claims.user_id": jwt_user && jwt_user.user_id,
          // Todo, include whether a user is an admin in their token
          'role': (jwt_user && jwt_user.user_id) ? 'agora_user' : 'agora_visitor',
          //'role': 'agora_admin',
          //'http.headers': `${req.headers['x-something'] || ''}`,
          'http.method': `${req.method}`,
          'http.url': `${req.url}`,
        };
      },

      // The return value of this is added to `context` - the third argument of
      // GraphQL resolvers. This is useful for our custom plugins.
      additionalGraphQLContextFromRequest(req) {
        return {
          // Let plugins call priviliged methods (e.g. login) if they need to
          rootPgPool,

          // Use this to tell Passport.js we're logged in
          login: user =>
            new Promise((resolve, reject) => {
              req.ctx.login(user, err => (err ? reject(err) : resolve()));
            }),
        };
      },
    })
  );
};
`

**Comment by brynbeaudry** [comment]
So if the call to postgraphile its not using the connection string for rootPgPool for much else besides extending the plugins (which I do use), which conneciton string does it use for finding the jwtPgTypeIdentifier, and where can that be configured?

**Comment by benjie** [comment]
Trimming this down to the relevant parts:

```js
const {
  library: { connection, schema, options },
} = require("../../.postgraphilerc.js");
// ...
 app.use(
    postgraphile(connection, schema, {
```

You're telling PostGraphile to use the `module.exports.library.connection` entry from `.postgraphilerc.js`. I suspect this value either isn't present or has the incorrect value.

The `rootPgPool` is not passed directly to the `postgraphile(...)` call, instead it is used in your `additionalGraphQLContextFromRequest` callback, so PostGraphile doesn't know about it.

**Comment by brynbeaudry** [comment]
You're right Benjie, thank you. I found it!
The url for AUTH_DATABASE_URL wasn't updated.
Thanks so much for your prompt reply.

**Comment by benjie** [comment]
👍 Please consider [backing me on Patreon](https://www.patreon.com/benjie) - every little helps!
